### ISSUE TITLE
circos.genomicLink reorders input data

### ISSUE THREAD

**Issue by mcieslik-mctp** [jokergoo/circlize#10]
I may be missing something... so please excuse if this is my lack of understanding.

The function circos.genomicLink should add links between two paired regions: region1 and region2. In the process of doing this it reorders region1 and region2 - loosing the linkage and producing a false plot.

circos.genomicLink calls normalizeToDataFrame which does

```
data = data[order(data[[1]], data[[2]]), , drop = FALSE]
```

**Comment by jokergoo** [comment]
Thanks a lot for reporting this! I have fixed this bug and updated the package on GitHub.

**Comment by mcieslik-mctp** [comment]
thanks for the fix

**Comment by KrithikaB472** [comment]
@mcieslik-mctp - I am trying to understand the circos.genomicLink() function better and came across this issue you posted in 2015. You said "The function circos.genomicLink should add links between two paired regions: region1 and region2. " .  What do you mean by paired regions ? Do you mean adding a link between the first row in region 1 and the first row in region 2, second row in region 1 and the second row in region 2, and so on ? 
I did a small example and it seems like it is doing the links this way, but I wanted to confirm to make sure my understanding was correct.  Thanks.

> thanks for the fix

**Comment by jokergoo** [comment]
Yes, you understand it correctly.
