### ISSUE TITLE
Points are out of plotting region in sector

### ISSUE THREAD

**Issue by jgarces02** [jokergoo/circlize#101]
Hi (again) @jokergoo, 

I'm doing a representation for allele frequency with the following code:
```
circos.initializeWithIdeogram(species = "hg19", plotType = c("ideogram", "labels"))

circos.track(factors = df2$X.CHR, x = df2$COORDINATE, y = df2$MM6_MO.VARIANT.FREQUENCY,
             panel.fun = function(x, y) {
               circos.points(x = df2$COORDINATE, y = df2$MM6_MO.VARIANT.FREQUENCY, pch = "·")
             })
```
Input data: 
```
      GENE X.CHR COORDINATE MM6_MO.VARIANT.FREQUENCY MM65_PM.VARIANT.FREQUENCY PB_VARIANT_FREQUENCY
3  SLC35E2  chr1    1663722                        0                0.00000000           0.00000000
2  DNAJC16  chr1   15897474                        0                0.02564103           0.00000000
23   NBPF1  chr1   16889430                        0                0.03448276           0.00862069
14 KLHDC7A  chr1   18812455                        0                0.00000000           0.00000000
```
`circlize` is notifying this error for each chromosome: `Note: 10 points are out of plotting region in sector 'chr2', track '3'` (number of "outliers" points increase iteratively, I guess because there's  kind of displacement that pushes forward this points) and it draws this plot with points between the plot regions gaps:
![image](https://user-images.githubusercontent.com/27858969/48268095-5c228a80-e434-11e8-9be9-85eedf239166.png)
I know, according `circos.par` [help](https://www.rdocumentation.org/packages/circlize/versions/0.4.4/topics/circos.par), that 
> since each cell is in fact not a real plotting region but only an ordinary rectangle, it does not eliminate points that are plotted out of the region. So if some points are out of the plotting region, `circlize` would continue drawing the points and printing warnings.

But I plotted my data inside a normal plot and none point seems to go outside it... so I cannot understand because there're points out of the plot. Could you explain me the reason, please? Is there any way to fix it this (or at leas hide those points out of the plotting regions)?

Thanks (again) for your help.

**Comment by jokergoo** [comment]
`panel.fun` is applied to each sector iterately, which means, when `panel.fun` is applied to chr1, it should only use the data points for chr1. You may observe `panel.fun` needs to argument `x` and `y`. They are x and y values for the data points in "current chromosome" and they ae subsetted automatically from `df2` in `circos.track()`.

So the correct way to add points is:

```
circos.track(factors = df2$X.CHR, x = df2$COORDINATE, y = df2$MM6_MO.VARIANT.FREQUENCY,
             panel.fun = function(x, y) {
               circos.points(x = , y = y, pch = "·")
             })
```

**Comment by jgarces02** [comment]
Yes, you're right, (silly) fail mine... thanks!

**Comment by jgarces02** [comment]
Sorry (I think you already hate me), but changing this line as you suggested don't make the error disappears and moreover none point is drawn! 😳❓

**Comment by jokergoo** [comment]
Check following code:

```{r}
df2 = read.table("df2.txt", header = T, stringsAsFactors = FALSE)
df2 = df2[ df2$X.CHR != "MT", ]
df2$X.CHR = paste0("chr", df2$X.CHR)

circos.initializeWithIdeogram(species = "hg19", plotType = c("ideogram", "labels"))
circos.track(factors = df2$X.CHR, x = df2$COORDINATE, y = df2$MM62_MO.VARIANT.FREQUENCY,
             panel.fun = function(x, y) {
               circos.points(x = x, y = y, pch = "·")
             })
```
