### ISSUE TITLE
Remove y-axis line

### ISSUE THREAD

**Issue by royfrancis** [jokergoo/circlize#107]
I would like to have a y-axis without the y-axis line. I do that by setting `lwd=0`. That works for PNG files but does not work for PDF. See example below.

```
png("test.png",height=5,width=5,units="in",res=300)
#pdf("test.pdf",height=5,width=5)
circos.clear()
circos.par(gap.degree=20)
circos.initialize(factors="chrA",xlim=c(1,1000))
circos.track(ylim=c(0,1),panel.fun=function(x,y) {
  chr=CELL_META$sector.index
  xlim=CELL_META$xlim
  ylim=CELL_META$ylim
},bg.col="grey90",bg.border=F,track.height=0.06)
circos.track(track.index = get.current.track.index(), panel.fun = function(x, y) {
  circos.axis(h="top")
},bg.border=F)

cov <- data.frame(chr="chrA",x=sample(1:1000,100),y=sample(seq(0,1,by=0.01),100))
circos.track(cov$chr, cov$x, cov$y, panel.fun = function(x, y) {
  circos.points(x, y)
},track.height=0.3,bg.border=F)

circos.yaxis(lwd=0,tick.length=0)
dev.off()
```

PNG output: Y-axis line is hidden correctly.
![test](https://user-images.githubusercontent.com/5083500/52872834-c3e02400-314d-11e9-9f3c-052ca912decb.png)

PDF output: Y-axis line is still visible.
[test.pdf](https://github.com/jokergoo/circlize/files/2870105/test.pdf)

Is there some way to remove the y-axis line from the PDF? Thanks.

```
R version 3.5.2 (2018-12-20)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS
circlize_0.4.6 
```

**Comment by jokergoo** [comment]
Maybe you can set `col` to `#00000000` (eight zeros)

**Comment by royfrancis** [comment]
Tried that. Doesn't seem to have any effect in PDFs.

**Comment by jokergoo** [comment]
Then how about setting `col = NA`. If that doesn't work neither, actually you can add the axis labels by hand:

```r
# assume this is the first track and the first sector
circos.text(rep(CELL_META$cell.xlim[1], 6), c(0, 0.2, 0.4, 0.6, 0.8, 1), 
    labels = c(0, 0.2, 0.4, 0.6, 0.8, 1), adj = c(1, 0.5))
```

**Comment by royfrancis** [comment]
Manually placing the text worked. This is also fixed another issue where some of the y-axis labels (close to the y-axis limits) were not displayed. Thanks!
