### ISSUE TITLE
genomicLabels text direction is not consistent

### ISSUE THREAD

**Issue by royfrancis** [jokergoo/circlize#108]
In the figure below I am plotting gene names using `genomicLabels()`, some labels read right-left while other read left-right. Sometimes it switches a lot especially at the top and bottom. Is there an option to force them all to read in the same direction.

`circos.genomicLabels(genes,labels.column=5,side="inside")`

![test](https://user-images.githubusercontent.com/5083500/52950011-33d4f100-337e-11e9-8f68-be7861bc037f.png)

Full code for this figure below.

```
png("test.png",height=5,width=5,units="in",res=300)
circos.clear()
circos.par(gap.degree=20)
circos.initialize(factors="chrA",xlim=c(1,1000))
circos.track(ylim=c(0,1),panel.fun=function(x,y) {
  chr=CELL_META$sector.index
  xlim=CELL_META$xlim
  ylim=CELL_META$ylim
},bg.col="grey90",bg.border=F,track.height=0.06)
circos.track(track.index = get.current.track.index(), panel.fun = function(x, y) {
  circos.axis(h="top")
},bg.border=F)


genes <- data.frame(chr="chrA",start=replicate(50,sample(1:1000,1)),stringsAsFactors=F)
genes$end <- genes$start+sample(2:20,nrow(genes),replace=T)
genes$value1 <- 1
genes$gene <- replicate(50,paste(sample(letters,4),collapse=""))

circos.genomicLabels(genes,labels.column=5,side="inside")

dev.off()
```

**Comment by jokergoo** [comment]
I added `facing` and `niceFacing` arguments to `circos.genomicLabels()` function. Now you can set `niceFacing = FALSE` to suppress this auto-adjustmnet. You can update the package from github.

The aim of this adjustment is to make e.g. the labels on the top right circle and the top left circle to face to the bottom so that it is easy to read.

**Comment by royfrancis** [comment]
Awesome! Yes, I do understand the logic behind the different directions. And the default probably works fine is most situations. But, sometimes it's good to have finer control. Thanks a lot!

**Comment by jokergoo** [comment]
Hi, I update the package again. You may notice on the top part of the circle (~ 810), two linking lines intersect. Now in the new version, they do not intersect anymore.
