### ISSUE TITLE
Highlight.sector()   `chr` contains index that does not beling to available sectors.

### ISSUE THREAD

**Issue by Smriti1990** [jokergoo/circlize#111]
Hi 

I am facing issue with highlight.sector() function. I am getting an error `chr` contains index that does not beling to available sectors. I have used following code snippet
sn = paste(combined$p[l], combined$c[l], sep = "|")
  #print(sn)
  #print(!all(sn %in% sectors))
  highlight.sector(sn,track.index = 1, col = col_pathways[pathway], 
                   text = pathway, niceFacing = TRUE)

and have checked using following command
sectors = get.all.sector.index()
intersect(sectors,sn)

and getting following output
![image](https://user-images.githubusercontent.com/23184365/54556776-a10c8e00-49df-11e9-8bd5-32b3123158d9.png)

Can you please help me

**Comment by jokergoo** [comment]
Can you post the complete code and attach the example dataset?

**Comment by timxymo** [comment]
Had similar problems multiple times and had a good feeling this has to do with one of the sector is too small to show. Probably wanna check out [this section](https://jokergoo.github.io/circlize_book/book/the-chorddiagram-function.html#reduce) in manual
