### ISSUE TITLE
how to speed up circlize ?

### ISSUE THREAD

**Issue by gongyh** [jokergoo/circlize#112]
For e. coli, circlize used ~15 minutes to draw axes, genes, gc curve, gc-skew, and 3 coverage lines.
Is there any plan to accelerate it by optimizing the code or using parallel computation?

**Comment by jokergoo** [comment]
Do you have a lot of data points to draw or a lot of categories? e.g. a lot of genes?

Unfortunately, the plotting functions cannot be executed in parallel.

**Comment by gongyh** [comment]
@jokergoo Thank you! I have optimized my code to ~3 min, but intuitively it should be faster. 
Maybe rewrite some core funcitons using Rcpp?

**Comment by calpan** [comment]
Plotting can often be faster if you send the output to an image file instead of to the screen, e.g.:
```
pdf('output.pdf')
# plotting commands go here
dev.off()
```

**Comment by jokergoo** [comment]
Yes, that is right.
