### ISSUE TITLE
Color assignments in genomicLabels

### ISSUE THREAD

**Issue by pryabinin** [jokergoo/circlize#116]
I am trying to label gene locations on a circos plot with different colors, but I am not getting the results I expect. Here is the code I am using:
```
library(circlize)

bed <- data.frame(CHR=c("chr14","chr11","chr4","chr8","chr8"),
                  start=c(23653041,63678193,95373403,145649435,102218365),
                  end=c(23653041,63678193,95373403,145649435,102218365),
                  gene=c("SLC7A8","MARK2","PDLIM5","VPS28","ZNF706"),
                  color=c("orange","orange","orange","purple","purple"),stringsAsFactors = F)

png("test.png")
circos.initializeWithIdeogram(plotType = "labels",chromosome.index=paste0("chr",1:22),species="hg19")
circos.genomicLabels(bed, labels = bed$gene, side = "outside",
                     col = bed$color, line_col = bed$color)
circos.genomicIdeogram()
dev.off()
```

I am expecting that SLC7A8, MARK2, and PDLIM5 will be orange which VPS28 and ZNF706 will be purple. However, instead VPS28, ZNF706, and PDLIM5 are orange while MARK2 and SLC7A8 are purple:

![test](https://user-images.githubusercontent.com/16544244/56247194-e5c82b00-6058-11e9-8fca-0a5601607a6e.png)

I am using R 3.5.0 and circlize version 0.4.6.

**Comment by jokergoo** [comment]
Ah, it is a bug that I forgot to reorder the `col` vector based on the reordering of regions (so you can see the three oranges texts are for the first three regions, on chr4 and chr8). I will fix it very soon.

**Comment by jokergoo** [comment]
Updated on Github:

![image](https://user-images.githubusercontent.com/449218/56294261-fb0d8a00-612a-11e9-9787-c8b7db2225f3.png)

**Comment by pryabinin** [comment]
Thank you very much, this fixed it for me.
