### ISSUE TITLE
change direction of coordinates inside sectors to be counterclockwise

### ISSUE THREAD

**Issue by assafwww** [jokergoo/circlize#118]
Dear Circlize developer,
is it possible to change direction of coordinates inside sectors to be counterclockwise ?
I think this is a convention of representation of mitochondrial genomes for example, but I don't find a way to change it in circlize.
thanks, Assaf

**Comment by jokergoo** [comment]
No, you cannot change the direction of the coordinate inside the sector. It is fixed.

**Comment by timxymo** [comment]
@assafwww the easiest way to change the direction would be changing the order of your matrix I think.

**Comment by jokergoo** [comment]
Or you can manually convert the orientation of the axes:

```r
rev_x = function(x) {
	xrange = CELL_META$xlim
	xrange[2] - x + xrange[1]
}

par(mfrow = c(1, 2))

circos.initialize(factor = letters[1:8], xlim = c(1, 10))
circos.track(ylim = c(1, 10), panel.fun = function(x, y) {
	circos.points(1:10, 1:10)
	circos.xaxis()
})
text(0, 0, "normal x-axis")


circos.initialize(factor = letters[1:8], xlim = c(1, 10))
circos.track(ylim = c(1, 10), panel.fun = function(x, y) {
	circos.points(rev_x(1:10), 1:10)
	breaks = seq(2, 10, by = 2)
	circos.xaxis(major.at = rev_x(breaks), labels = breaks)
})
text(0, 0, "reversed x-axis")
```
![image](https://user-images.githubusercontent.com/449218/56562159-1a803900-65a9-11e9-8dfb-2bbb57147b04.png)

**Comment by NicoBueno666** [comment]
Dear Circlize developer,
Following the question of @assafwww , I wonder i is it possible to change direction of x-coordinates inside of **particular** sectors. In synteny analysis, it is common when comparing two homologous genomes to invert the direction of one of them to order the relations between them ant to easly see the invertions.
Regards, Nico.
