### ISSUE TITLE
colorRamp2 error when specifying HLS color space

### ISSUE THREAD

**Issue by bioinfomagician** [jokergoo/circlize#119]
https://github.com/jokergoo/circlize/blob/5379e853e0154e116278d58983eaeee100d119d2/R/utils.R#L261

Noticed that I get an error when trying to set the space as `HLS` even though it is listed as an option in the documentation. Looking at the code, it appears that this error check needs to be updated.

**Comment by jokergoo** [comment]
Thanks! I forgot that!

Now I have updated.
