### ISSUE TITLE
Highlight.sector() `chr` contains index that does not beling to available sectors.

### ISSUE THREAD

**Issue by timxymo** [jokergoo/circlize#121]
I notice there is another issue opened with the same problem, but that wasn't very helpful and I didn't want to use his post so I opened my own. So I got this error message and ran with debug and it says ```!all (sector.index %in% sectors)``` Then I went to compare what's in both ```sector.index``` and ```sectors``` and indeed one of the sectors is missing.  
The interesting thing is the missing sector is in my matrix but somewhere down the line it's missing, and it's not zero.  I guess my question is where does sector.index inherit the sector names?   
Another interesting thing is I have another plot built based on another matrix (colnames and rownames of matrix are exactly the same), which has the same missing sector but it's not causing any trouble. I wish I can share more info and example data, but it's rather sensitive.

**Comment by jokergoo** [comment]
Can you also attach the data objects so that I can test it? Thanks!

**Comment by timxymo** [comment]
@jokergoo do you mind sending an email to timxymo@gmail.com and I can send you the data and the script, since the data is somewhat sensitive thanks for understanding!

**Comment by microbluvrsarah** [comment]
Hi, what was the resolution for this error?
