### ISSUE TITLE
Question regarding circos.genomicLink

### ISSUE THREAD

**Issue by KrithikaB472** [jokergoo/circlize#123]
I'm interested in using circos.genomicLink() function that add lines between two genomic regions input as two data frames.
Question - Does the function plot a line from:
   FirstLine of DataFrame1  to  FirstLine of DataFrame2
   SecondLine of DataFrame1  to  SecondLine of DataFrame2 ....
and so on ?

**Comment by jokergoo** [comment]
Hi you need to call circos.genomicLin() twice:

```r
circos.genomicLink(
    data.frame(df1[, 1], df1[, 2], df1[, 2]),
    data.frame(df2[, 1], df2[, 2], df2[, 2])
)
circos.genomicLink(
    data.frame(df1[, 1], df1[, 3], df1[, 3]),
    data.frame(df2[, 1], df2[, 3], df2[, 3])
)
```

**Comment by KrithikaB472** [comment]
Thank you for responding. Just to make sure I understand how this function works. 
If I write the code like this, how does this the function work ? Assume df1 and df2 have 5 rows which indicate 5 genomic positions. Thank you.
`circos.genomicLink(df1, df2)`

**Comment by NicoBueno666** [comment]
Hello @KrithikaB472,
You are right, the relation between the two data.frames is given by the row number. For example, try this:

`#libraries
library(circlize)
library(dplyr)
#making the dataframes with 5 lines
set.seed(1)
df1 = generateRandomBed(nr = 5)
df2 = generateRandomBed(nr = 5)
#df2 <- arrange(df2, desc(chr)) #COMENT AND UNCOMENT THIS LINE AND SEE THE EFFECT
#drawing
circos.initializeWithIdeogram()
circos.genomicLink(df1, df2, col = rand_color(nrow(bed1), transparency = 0.5),
                   border = NA)`

**Comment by KrithikaB472** [comment]
Excellent example @NicoBueno666  ! Makes perfect sense. Thanks so much !

**Comment by KrithikaB472** [comment]
Last question. @NicoBueno666
In an example like in the above one, what is the significance of the "value" column in both df1 and df2 ? What do these values represent ?

**Comment by NicoBueno666** [comment]
Dear @KrithikaB472 . This value is automatically generated by the function `generateRandomBed`.

> The BED format consists of one line per feature, each containing 3-12 columns of data, plus optional track definition lines. The required fields (first three columns) have the chromosome name and the postition (start and end). Then, you have the optional fields (like expression level, evalues, or what ever you want to represent). [Reference.](https://www.ensembl.org/info/website/upload/bed.html)

In this case, the `generateRandomBed` function simulates one random value. In this example, this value is not used, but, you can use this value for example to define the colors of the chords in you plot.

**Comment by KrithikaB472** [comment]
I'm looking to represent a correlation analysis in the form of a circos plot.  I have values A and B on which i did correlation and a correlation value. When I create my two data frames - A and B , should i put the correlation value as "value1 " and "value2" ? 
Example : Correlation between A and B os 0.7 
A looks like this `chr1 1000 1001 0.7` , 
B looks like this `chr5 4000 4001 0.7`

**Comment by jokergoo** [comment]
`chr1 1000 1001` is used for the positions of links while `0.7` is for mapping to colors. The code looks like:

```r
col_fun = colorRamp2(c(-1, 0, 1), c("green", "white", "red"))
circos.genomicLink(df1, df2, col = col_fun(your_correlation_vector))
```

**Comment by KrithikaB472** [comment]
Thanks so much @jokergoo and  @NicoBueno666 for the quick responses ! I was able to get the code working. 

In case its helpful to others: I input `df1` and 'df2` with only 3 columns each - `chr, start, end`.  And added the correlation value based on the code shown in above example. And it works ! 

PS - in case this is helpful for the developers, I was able to get the plot working with `circlize::circos.initializeWithIdeogram()` code. When I try `circlize::circos.initializeWithIdeogram(species="hg38"), it does not work.

Code below:
`
> head(df1)
    chr    start      end
1  chr7 16500000 20900000
2  chr7 16500000 20900000
3 chr10 75900000 80300000
4  chr7 28800000 34900000
> head(df2)
   chr    start      end
1 chr7   726700   786475
2 chr7  2234290  2242198
3 chr7 15611211 15686812
4 chr7   726700   786475
circos.clear()
circlize::circos.initializeWithIdeogram() 
col_fun = colorRamp2(c(-1, 0, 1), c("blue", "white", "red"))
circos.genomicLink(region1 = df1, region2 = df2,
                   col = col_fun(your_correlation_vector))  #color based on correlation vector
`

**Comment by jokergoo** [comment]
For hg38, there are some contigs that cannot be distinguished from normal chromosomes. You can manually specify the chromosomes you want to draw:

```r
circlize::circos.initializeWithIdeogram(species="hg38", chromosome.index=paste0("chr", c(1:22, "X", "Y")))
```

**Comment by jokergoo** [comment]
Now I have updated the package that `circos.initializeWithIdeogram(species="hg38")` won't give any error.

**Comment by KrithikaB472** [comment]
Awesome ! Thanks so much !
