### ISSUE TITLE
Draw a chromosome in reverse clockwise

### ISSUE THREAD

**Issue by NicoBueno666** [jokergoo/circlize#124]
Dear Circlize developer, I decided to add this like a new issue.
I wonder i is it possible to change direction of x-coordinates inside of particular sectors. In synteny analysis, it is common when comparing two homologous genomes to invert the direction of one of them to order the relations between them ant to easly see the invertions.
[Example.](https://i.stack.imgur.com/qSAbT.png)
Regards, Nico.

**Comment by jokergoo** [comment]
I found you come from issue #118 . Yes you can choose to reverse the axis by 
checking the current sector index:

```r
rev_x = function(x) {
	xrange = CELL_META$xlim
	xrange[2] - x + xrange[1]
}
circos.initialize(factor = letters[1:8], xlim = c(1, 10))
circos.track(ylim = c(1, 10), panel.fun = function(x, y) {
    if(CELL_META$sector.index %in% c("a", "b", "c", "d")) {
		circos.points(rev_x(1:10), 1:10)
		breaks = seq(2, 10, by = 2)
		circos.xaxis(major.at = rev_x(breaks), labels = breaks)
	} else {
		circos.points(1:10, 1:10)
		breaks = seq(2, 10, by = 2)
		circos.xaxis(major.at = breaks, labels = breaks)
	}	
})
```

![image](https://user-images.githubusercontent.com/449218/60402511-123c0f80-9b91-11e9-9f0a-36318e9eb402.png)

**Comment by NicoBueno666** [comment]
Hello, @jokergoo.

Thank you very much. I had this problem for many months!. I will studied the code that you gave me and I will try to make a little tutorial for the users that need to draw an inverted chromosome.

Best regards, Nico.

**Comment by NicoBueno666** [comment]
@jokergoo, sorry to reopen this line, but I had a problem.
Suppose you have the following example where one of the chromosomes needs to be drawn in reverse clockwise. How do you edit the code to achieve this?

> chromosomes <- data.frame(chr= c(1,2), start= c(1,1), end= c(100,100))
> relations <- data.frame(chr1= c(1,1), start1= c(1, 80), end1= c(20,100), chr2= c(2,2), start2= c(1,80), end2= c(20,100))
> library(circlize)
> circos.clear()
> circos.genomicInitialize(chromosomes)
> circos.genomicLink(relations[,1:3], relations[,4:6], col = "#FF000050")

![Sin nombre](https://user-images.githubusercontent.com/52336300/60405832-ff254180-9b88-11e9-8c15-355c0305a720.png)

**Comment by jokergoo** [comment]
You need to convert all positions corresponding to chr1.

First we define `rev_x()` function:

```r
rev_x = function(x, xrange = CELL_META$xlim) {
	xrange[2] - x + xrange[1]
}
```

In `rev_x()`, the second argument is the range in the current cell. By default it is the internal range on x-axis, but it can be self-defined that we will use in later code.

We initialize the circular plot without drawing anything because we will add the axis manually.

```r
chromosomes <- data.frame(chr= c(1,2), start= c(0, 0), end= c(100,100))
relations <- data.frame(chr1= c(1,1), start1= c(1, 80), end1= c(20,100), chr2= c(2,2), start2= c(1,80), end2= c(20,100))
library(circlize)
circos.clear()
circos.par(gap.degree = 5)
circos.genomicInitialize(chromosomes, plotType = NULL)
```

We create a small track where we put the axes:

```r
circos.track(ylim = c(0, 1),panel.fun = function(x, y) {
	major.by = seq(0, 100, by = 5)
	if(CELL_META$sector.index == "2") {
		circos.axis(major.at = major.by, labels = paste0(major.by, "bp"),
			labels.cex = 0.4 * par("cex"))
	} else {
		circos.axis(major.at = rev_x(major.by), labels = paste0(major.by, "bp"),
			labels.cex = 0.4 * par("cex"))
	}
}, bg.border = NA, track.height = uh(2, "mm"), cell.padding = c(0, 0, 0, 0))
```

in `relations`, all positions on chr1 should be reversed, both in the first set of regions (the first three columns) and the second set of regions (the last three columns). We explicitly specify the range
for chr1 by `get.cell.meta.data("xlim", sector.index = "1")`. Since `rev_x()` is called outside `panel.fun()`, `CELL_META` cannot be directly used, that why we use the `get.cell.meta.data()`
function which can get `xlim` data for a specified sector.

Note in `df`, the original start positions are now the end positions in `df` because the positions are reversed and start should always be no larger than the end positions.

```r
df = relations
l = df$chr1 == 1
df$end1[l] = rev_x(relations$start1[l], get.cell.meta.data("xlim", sector.index = "1"))
df$start1[l] = rev_x(relations$end1[l], get.cell.meta.data("xlim", sector.index = "1"))

l = df$chr2 == 1
df$end2[l] = rev_x(relations$start2[l], get.cell.meta.data("xlim", sector.index = "1"))
df$start2[l] = rev_x(relations$end2[l], get.cell.meta.data("xlim", sector.index = "1"))
```

And with the converted `df`, we can use `circos.genomicLink()` to add links:

```r
circos.genomicLink(df[, 1:3], df[, 4:6], col = "#FF000050")
```

![image](https://user-images.githubusercontent.com/449218/60426103-3ed54300-9bf4-11e9-8785-42aa1a3aebe9.png)

**Comment by NicoBueno666** [comment]
Ok, here you can see how to perform syntenic relations in circlize drawing one (or more) reference chromosomes in reverse clockwise. This detail is very important because highlights the chromosomal inversions or rearrangements.

In the next graph all the homologous chromosomes of tree species are drawn in the same orientation. As you can see, is difficult to visualize the inversion of the genes 2 and 3 between the species A (reference) and C.

![1](https://user-images.githubusercontent.com/52336300/60999191-ed822d80-a330-11e9-954e-5b62c8708090.png)

In this plot the chromosome of the species A was drawn in the opposite direction, so, is esasy to see that the gene order between the species A and B are the same, meanwhile there is an inversion between the species A and C.

![2](https://user-images.githubusercontent.com/52336300/60999177-e4915c00-a330-11e9-809c-ab21514ce550.png)

The mayor part of the papers does not use this focus or their plots, that is why I decided to make a little tutorial for you.

Fist of all, lest make some data:
```
chromosomes <- data.frame(chr= c("Species A","Species B","Species C"),
                          start= c(0, 0, 0), end= c(100,100, 200))
relations <- data.frame(chr1= c("Species A","Species A","Species A",
                                "Species A", "Species A", "Species A",
                                "Species A", "Species A"),
                        start1= c(10, 30, 50, 80, 10, 30, 50, 80),
                        end1= c(20, 40, 60, 90, 20, 40, 60, 90),
                        chr2= c("Species B", "Species B", "Species B", "Species B",
                                "Species C", "Species C", "Species C", "Species C"),
                        start2= c(10, 30, 50, 80, 40, 130, 100, 180),
                        end2= c(20, 40, 60, 90, 50, 140, 110, 190))
labels <- data.frame(chr1 = c(rep("Species A", 4), rep("Species B", 4), rep("Species C", 4)),
                     start1 = c(rep(c(10,30,50,80),2),40,130,100,180),
                     end1 = c(rep(c(20,40,60,90),2),50,140,110,190),
                     label = c(rep(c("Gene 1", "Gene 2", "Gene 3", "Gene 4"),2),
                     "Gene 1", "Gene 3", "Gene 2", "Gene 4"))

```

Now lets define the reference chromosome (inv) and the function that will help us to reverse all the coordinates of this chromosome.

```
inv <- "Species A"
rev_x = function(x, xrange = CELL_META$xlim) {
  xrange[2] - x + xrange[1]
}
```

To plot the gene labels, we first have to initialize the circos plot without the rules. We are going to put them later.

```
library(circlize)
circos.clear()
circos.par(gap.degree = 5)
circos.genomicInitialize(chromosomes, plotType = "labels")

```
The plot is now initialized, so we can use the `get.cell.meta.data` function to obtain information for reverse the coordinates of the reference chromosome

```
# Invert relations
relations.rev = relations
l = relations.rev$chr1 == inv
relations.rev$end1[l] = rev_x(relations$start1[l], get.cell.meta.data("xlim",
                                                                      sector.index = inv))
relations.rev$start1[l] = rev_x(relations$end1[l], get.cell.meta.data("xlim",
                                                                      sector.index = inv))
# Invert labels
labels.rev = labels
l = labels.rev$chr1 == inv
labels.rev$end1[l] = rev_x(labels$start1[l], get.cell.meta.data("xlim",
                                                                      sector.index = inv))
labels.rev$start1[l] = rev_x(labels$end1[l], get.cell.meta.data("xlim",
                                                                      sector.index = inv))

# Gene labels
circos.genomicLabels(bed = labels.rev, labels.column = 4, side = "outside",
                     cex = 0.7 * par("cex"), connection_height = convert_height(3, "mm"),
                     labels_height = convert_height(5, "mm"),
                     padding = convert_height(0, "mm"))

```
Ok, now lets draw the rules. For this, we are going to use the `if` function to differentiate the reference rule and the rest of them. This part is a little complicated, because we have to manually define the divisions of the rules and the units of their labels. I have also added an empty plot region to avoid collisions between the rule labels and the chromosome labels. Don't be scared. Maybe there is a better way to do this last thing.

```
# Rules
circos.track(ylim = c(0, 1), track.margin = convert_height(c(0,0), "mm"),
             bg.border = NA, cell.padding = c(0, 0, 0, 0),
             track.height = uh(3, "mm")) 
circos.track(ylim = c(0, 1), bg.border = NA, cell.padding = c(0, 0, 0, 0),
             track.height = uh(3, "mm"), panel.fun = function(x, y) {
  if(CELL_META$sector.index == inv) {
    major.by = seq(chromosomes[which(chromosomes$chr == inv), 2],
                     chromosomes[which(chromosomes$chr == inv), 3],
                     by = 20) #number of divission of he rule
    circos.axis(major.at = major.by, labels = paste0(major.by, "bp"),
                labels.cex = 0.4 * par("cex"))
  } else {
    major.by = seq(chromosomes[which(chromosomes$chr ==
                                         CELL_META$sector.index), 2],
                     chromosomes[which(chromosomes$chr == CELL_META$sector.index),
                                 3], by= 20) #number of divissions of the rule
    circos.axis(h= "bottom", major.at = major.by,
                labels = paste0(major.by/10, "MB"),
                labels.pos.adjust = F, labels.cex = 0.5 * par("cex"),
                track.index = 4)
  }})

```

Finally, lets draw the relations with the circos.genomicLink fuction.

`circos.genomicLink(relations.rev[, 1:3], relations.rev[, 4:6], col = "#FF000050")
`

I want to thak very much to @jokergoo from GitHub that did all the job.
