### ISSUE TITLE
Circos.text fails to iterate through labels inside circos.track panel.fun

### ISSUE THREAD

**Issue by acnash** [jokergoo/circlize#125]
I understand this may be down to my lack of understanding of the package, however, I would appreciate some assistance. 
I'm trying to add a unique 'label' in each cell using circos.text:

```
  circos.par("track.height"=0.15)
  circos.initialize(factors = categories,xlim=xMatrix)
  circos.par(points.overflow.warning = FALSE)
  circos.track(factors=categories, ylim=c(0,1), bg.col=drugColors, 
               panel.fun=function(x,y) {
                 circos.text(CELL_META$xcenter,CELL_META$cell.ylim[2]+uy(2.5,"mm"),CELL_META$sector.index, adj = c(0, degree(0)),facing = "clockwise")
                 circos.text(CELL_META$xcenter,CELL_META$cell.ylim[2]-uy(2.9,"mm"),labels=initialRates)
  })


> initialRates
 [1] 2837 1987   27  119    9   75    1  189  545    1  118    9   11   24  126
> 
```

The first circos.text call works fine. However, the second circos.text only every uses the first element from initialRates.

<img width="668" alt="Screenshot 2019-07-03 at 15 51 45" src="https://user-images.githubusercontent.com/20614766/60601766-8c93ac00-9daa-11e9-895d-17a8a2f4cb8e.png">

Thanks!

**Comment by jokergoo** [comment]
Hi, in `panel.fun`, it only draws in the current cell. In your code, 

```r
panel.fun=function(x,y) {
    ....
    circos.text(CELL_META$xcenter,CELL_META$cell.ylim[2]-uy(2.9,"mm"),labels=initialRates)
}
```

I guess you want to draw every value in `initialRates` to every cell, then you can do:

```r
panel.fun=function(x,y) {
    ....
    circos.text(CELL_META$xcenter,CELL_META$cell.ylim[2]-uy(2.9,"mm"),
        labels=initialRates[CELL_META$sector.numeric.index])
}
```

**Comment by acnash** [comment]
Good morning! Thank you so much. A very simple fix indeed! I'm surprised I didn't spot it myself. 
By the way, if I am having trouble understanding the R package is this the best forum to use/
Thanks again.

**Comment by jokergoo** [comment]
Yes, of course!

**Comment by acnash** [comment]
Hi jokergoo. I have a further question, I hope appending to my existing post is ok. 

I'm trying to use the nested zoom function:

But I get the following error:

**Error in try({ : Cannot map 'correspondance' to sectors in 'f2()'.
Error in circos.nested(secondDrugCircle, firstDrugCircle, drugCorrespondance) : 
  Cannot map 'correspondance' to sectors in 'f1()'.**

The drugCorrespondance dataframe was defined to match the correspondance dataframe in your tutorials:

`drugCorrespondance <- data.frame(cate=secondDrugCompleteDF$cate,start=secondDrugCompleteDF$start,end=secondDrugCompleteDF$end,name=secondDrugCompleteDF$name,start.1=secondDrugCompleteDF$start,end.1=secondDrugCompleteDF$end)`
 
I call the nested code using:

`circos.nested(secondDrugCircle, firstDrugCircle, drugCorrespondance)`

The respective functions are:

`firstDrugCircle <- function() {
    circos.par("track.height"=0.15, gap.degree = 1, cell.padding = c(0.02, 0.02, 0.02, 0.02), points.overflow.warning = FALSE)
    par(mar = c(3, 3, 3, 3))
    circos.initialize(factors = categories,xlim=xMatrix)
    circos.track(factors=categories, ylim=c(0,1), bg.col=drugColors) 
  }`

The data for this function:

> categories
 [1] amitriptyline propranolol   metoprolol    topiramate    timolol       candersartan  methysergide  lisinopril   
 [9] atenolol      nadolol       venlafaxine   valproate     ergotamine    etoricoxib    indomethacin 

> xMatrix
      [,1] [,2]
 [1,]    0   12
 [2,]    0   11
 [3,]    0    5
 [4,]    0    7
 [5,]    0    4
 [6,]    0    7
 [7,]    0    1
 [8,]    0    8
 [9,]    0   10
[10,]    0    1
[11,]    0    7
[12,]    0    4
[13,]    0    4
[14,]    0    5
[15,]    0    7  


  `secondDrugCircle <- function() {   
    circos.par("track.height"=0.15, gap.degree = 1, cell.padding = c(0.02, 0.02, 0.02, 0.02), points.overflow.warning = FALSE)
    circos.initialize(factors = as.factor(secondDrugCompleteDF$name),xlim=as.matrix(secondDrugCompleteDF[,2:3]))
    circos.track(factors=secondDrugCompleteDF$name, ylim=c(0,1)) 
  }`

> head(secondDrugCompleteDF)
                                              name    start      end          cate
1                 propranolol:(0,6.55609756097561] 0.000000 6.556098 amitriptyline
2   metoprolol:(6.55609756097561,6.67317073170732] 6.556098 6.673171 amitriptyline
3   topiramate:(6.67317073170732,9.21951219512195] 6.673171 9.219512 amitriptyline
4      timolol:(9.21951219512195,9.24878048780488] 9.219512 9.248780 amitriptyline
5 candersartan:(9.24878048780488,9.48292682926829] 9.248780 9.482927 amitriptyline
6 methysergide:(9.48292682926829,9.51219512195122] 9.482927 9.512195 amitriptyline

And finally, the correspondance dataframe:

> head(drugCorrespondance)
           cate    start      end                                             name  start.1    end.1
1 amitriptyline 0.000000 6.556098                 propranolol:(0,6.55609756097561] 0.000000 6.556098
2 amitriptyline 6.556098 6.673171   metoprolol:(6.55609756097561,6.67317073170732] 6.556098 6.673171
3 amitriptyline 6.673171 9.219512   topiramate:(6.67317073170732,9.21951219512195] 6.673171 9.219512
4 amitriptyline 9.219512 9.248780      timolol:(9.21951219512195,9.24878048780488] 9.219512 9.248780
5 amitriptyline 9.248780 9.482927 candersartan:(9.24878048780488,9.48292682926829] 9.248780 9.482927
6 amitriptyline 9.482927 9.512195 methysergide:(9.48292682926829,9.51219512195122] 9.482927 9.512195
.....

If each circle is called on its own, then they are displayed. But when combined nested, they do not.

**Comment by acnash** [comment]
I'm trying to rectify the problem with my code using the example in your tutorial, however, I'm afraid I'm a little unclear with this instruction:
**"The correspondance between the original sectors and the zoomed intervals are in correspondance. The value is a data frame with six columns. _The value is the position of the intervals in the second circular plot in the first plot_."**

**Comment by jokergoo** [comment]
I noticed there are also some errors on the webpage of the `circos.nested()` function. Can you send me the objects you used in the code?

**Comment by jokergoo** [comment]
I have improved the `circos.nested()` function a little bit that unnecessary code that might cause errors are removed. You can rerun your code with the newest version from GitHub.

**Comment by acnash** [comment]
Thanks Jokergoo! I've very overwhelmed at work but this is currently part of a medical manuscript. When I get back to that section I'll send you what I have. Thanks.
