### ISSUE TITLE
Is there an upper limit to the number of lines circos.genomicLink() can draw

### ISSUE THREAD

**Issue by KrithikaB472** [jokergoo/circlize#126]
Is there an upper limit to the number of lines circos.genomicLink() can draw ? 
When I plot with 200 lines, it works great. But when I try 500 lines it give me an error  
`"Error in circos.genomicLink(region1 = df1, region2 = df2,  : 
  nrow of region1 and region2 differ.)`

I tested the number of rows of `df1 `and `df2` and they match. 

I don't know what else could be wrong.

**Comment by jokergoo** [comment]
I think there is no limit. Can you attach `df1` and `df2`?

**Comment by KrithikaB472** [comment]
`circos.clear()
circlize::circos.initializeWithIdeogram(species="hg38")
col_fun = colorRamp2(c(-1, 0, 1), c("blue", "yellow", "red"))
circos.genomicLink(region1 = df1, region2 = df2,
                   col = col_fun(masterGCC$V3),
                   directional=1, arr.type = "triangle", arr.length = 0.05)  `

[df1_df2.zip](https://github.com/jokergoo/circlize/files/3364003/df1_df2.zip)

Note - I tried taking the top 200 rows from df1 and df2, and the plot works

**Comment by jokergoo** [comment]
Line 331 in df2.tsv contains all NAs.

**Comment by KrithikaB472** [comment]
Thanks for catching that ! Seems like one of my genes did not get matching genomic regions. I will investigate.
