### ISSUE TITLE
circos.genomicHeatmap deal with NA values

### ISSUE THREAD

**Issue by lgxqzz** [jokergoo/circlize#129]
Hi 
I was trying to plot heatmap with NA values in my dataframe.
It returned: 
Error in res_col[l] <- .get_color(x[l], breaks[i], breaks[i + 1], colors[i,  : 
  NAs are not allowed in subscripted assignments
Is there any way I can work around this error?

Thanks!

**Comment by jokergoo** [comment]
Sorry for the late reply. I was on vocation.

I assume you were using `circos.genomicHeatmap()` function.

Can you please try the newest version of circlize (0.4.7 from CRAN or 0.4.8 from Github)? I tried with the current version and there is no error.

If you use 0.4.8, you can control the color for NA values by `na_col` argument in `circos.genomicHeatmap()`.

**Comment by jokergoo** [comment]
See updates on https://github.com/jokergoo/circlize/issues/135#issuecomment-544242714
