### ISSUE TITLE
question on bending text spacing

### ISSUE THREAD

**Issue by gjabel** [jokergoo/circlize#131]
Is there a way to control the spacing between the text when using a bending option in `highlight.sector()` of `circos.text()`? 

Most of the time when I use a bending option I run into issues like this... 

![image](https://user-images.githubusercontent.com/2735201/63870948-48441700-c9bb-11e9-9c03-22c01d589cc8.png)

... the bending labels are too long due to excessive spaces between letters. They look odd and  lead to problems with overlapping labels.

**Comment by jokergoo** [comment]
En, this is weird. The spacing between letters should not be that big. Can you attach some code you use? I didn't see it when I tested the `circos.text() function.

**Comment by gjabel** [comment]
I think I figured it out... happens when I use `dev.copy2pdf()` but not when I use `pdf()` ... not to worry.
