### ISSUE TITLE
Is there anyway to avoid connection_height in circos.genomicHeatmap() while plotting heatmaps

### ISSUE THREAD

**Issue by Swap90** [jokergoo/circlize#135]
[Picture 1.pdf](https://github.com/jokergoo/circlize/files/3732400/Picture.1.pdf)
Is there anyway to avoid connection_height in circos.genomicHeatmap() to plot heatmap without connection height so that I do not have gaps in-between tracks of heatmap ?

Basically I would like to avoid the gaps between three inner grey tracks (heatmaps)

The image has been generated with the following code:
circos.genomicHeatmap(merge_df, numeric.column = 10, col = col_fun2, side = "inside", connection_height = convert_height(0.001, "mm"), heatmap_height = 0.06, line_col = "white")

**Comment by jokergoo** [comment]
The connection lines show where are the regions in the chromosome that you visualize as heatmaps. If no connection line is drawn, how do you know where are these heatmap regions from?

Anyway, I have updated the package, now you just set `connection_height = NULL` in `circos.genomicHeatmap()` function and no connection lines will be drawn.

Please update it from GitHub (`devtools::install_github("jokergoo/circlize")`).

**Comment by Swap90** [comment]
Thanks for the solution. 
I am trying to hide connection_height because the number of genes in heatmap are large hence the connection lines merge and dosee not provide much information. Its good for small set of genes.

Apart from this, I have another query. I am trying to colour "NA" in dataset to white instead of default=grey, but its not changing to any other colour. Could you please advise on the same.

**Comment by jokergoo** [comment]
The color of what? in the heatmap or something else? It might be something I haven't been careful enough. 

Anyway, a quick fix is to set the color to `#00000000` (full transparent color)

**Comment by jokergoo** [comment]
Yes, that was a bug. Now `na_col` is correctly used in the newest version.

```r
circos.initializeWithIdeogram(plotType = c("labels", "axis"))
bed = generateRandomBed(nr = 100, nc = 4)
bed[1, 4:7] = NA
col_fun = colorRamp2(c(-1, 0, 1), c("green", "black", "red"))
circos.genomicHeatmap(bed, col_fun, side = "inside", border = "white")
circos.genomicHeatmap(bed, col_fun, side = "outside", na_col = "purple",
    line_col = as.numeric(factor(bed[[1]])))
```

![image](https://user-images.githubusercontent.com/449218/67158669-61be6b00-f33b-11e9-941c-681a2376531b.png)

**Comment by jezreel-me** [comment]
I followed your code, and adapted it to show no connections:
circos.initializeWithIdeogram(plotType = c("labels", "axis"))
bed = generateRandomBed(nr = 100, nc = 4)
col_fun = colorRamp2(c(-1, 0, 1), c("green", "black", "red"))
circos.genomicHeatmap(bed, col_fun, side = "inside", border = "white", connection_height = NULL)

But I got this error:
Error in if (track.start - track.height - track.margin[2] < 0 || track.start -  : 
  missing value where TRUE/FALSE needed

I even updated from Github as you recommended, but got another error:
Error in fetch(key) : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/circlize/help/circlize.rdb' is corrupt

**Comment by jokergoo** [comment]
I think you need to restart your R session and re-install circlize.
