### ISSUE TITLE
"Cannot find track error" for circos.trackHist()

### ISSUE THREAD

**Issue by KeelyDulmage** [jokergoo/circlize#136]
Hi, I'm trying to plot a circos plot for a custom genome and I'm running into an issue with just the circos.trackHist() function which I am using to plot frequency of translocation events. Here is my code:

```
    tsplot$ref1 <- (gsub("chr", "", tsplot$ref1))
    tsplot$ref2` <- (gsub("chr", "", tsplot$ref2))
    vcom <- vcon[vcon$Name != "-" & vcon$Name != "MT",]
    vdata <- data.frame(name = (as.character(vcom$Name)), start = 1, end = (as.integer(vcom$`Size (Mb)`)*1000000), stringsAsFactors = F) %>% droplevels()
    png(file = "results/temp.png", width = 4, height = 4, units = "in", res = 300)
    circos.genomicInitialize(vdata, sector.names = (as.character(vdata$name)), labels.cex = 0.5, plotType = "labels", track.height = 0.2)
    circos.track(ylim = c(0,1), panel.fun = function(x,y){
      chr = CELL_META$sector.index
      xlim = CELL_META$xlim
      ylim = CELL_META$ylim
      circos.rect(xlim[1], 0, xlim[2], 1, col = "gray50")
    }, track.height = 0.075, bg.border = NA)
    if(nrow(tchr) >= 0.0001 * nrow(svcov)){
      circos.trackHist(factors = tsplot$ref2, x = tsplot$pos2, col = "dodgerblue4", bin.size = 2000000)
       }
    circos.genomicLink(region1 = tsplot[,c(1,2,2)],
                     region2 = tsplot[,c(3,4,4)],
               col = mycols)
    invisible(dev.off())
```

I get this error: 
> Error in get.cell.meta.data("cell.xlim", sector.index, track.index) : Cannot find track: 3.

I only have 111 events (at 10 unique sites) to plot with the histogram and I have also had errors in the past plotting human data with only a handful of unique events. I suspect that this might be the issue because of the following:

If I artificially make a larger dataset with 1000 unique events
`tsplot <- data.frame(ref1 = 7, pos1 = sample(1:5000000, size = 1000), ref2 = sample(vdata$name, size = 1000, replace = T), pos2 = sample(1:5000000, size = 1000))`
It works fine. But if I make one that has just 10 unique events
`tsplot <- data.frame(ref1 = 7, pos1 = sample(1:5000000, size = 10), ref2 = sample(vdata$name, size = 10, replace = T), pos2 = sample(1:5000000, size = 10))`
I get the same error:
> Error in get.cell.meta.data("cell.xlim", sector.index, track.index) : 
  Cannot find track: 3.

If I just leave off the histogram I get the correct plot so I'm fairly confident that the problem is just with the histogram itself.  

For reference, here are the first few rows of the dataframes that I am plotting:

Translocation hotspots
```
>head(tsplot)
  ref1     pos1 ref2     pos2
1    1 11111111   12 25505980
2    1 11111111   12 25505979
3    1 11111111   12 25505976
4    1 11111111   12 25505976
5    1 11111111   12 25505976
6    1 11111111   12 25505976
```
Chromosome coordinates
```
> head(vdata)
  name start      end
1    1     1 1.26e+08
2    2     1 9.00e+07
3    3     1 9.20e+07
4    4     1 9.10e+07
5    5     1 7.50e+07
6    6     1 5.00e+07
```
I am using circlize version 0.4.6

Thank you!  I do really appreciate the package, these figures are super helpful for showing intra-chromosomal translocation events.

-Keely

**Comment by jokergoo** [comment]
It might be the problem of `circos.trackHist()` because I don't use it very often and there might be some bugs in it.

If you can send me the R objects you use in your code, then I can have a test on your code.

**Comment by KeelyDulmage** [comment]
Here's a test set for you:
[circosTrackHist_test.zip](https://github.com/jokergoo/circlize/files/3756881/circosTrackHist_test.zip)

**Comment by jokergoo** [comment]
Yes, that was a bug when `factors` in `circos.trackHist()` does not include all sectors. I have fixed this bug and you can try the newest version from GitHub.

![image](https://user-images.githubusercontent.com/449218/67429210-fb0dab80-f5df-11e9-8b17-0e914fdf5958.png)

**Comment by KeelyDulmage** [comment]
Perfect!  Works fine with my data now.  Thank you for the quick reponse!
