### ISSUE TITLE
Add an example of visualizing HiC dataset

### ISSUE THREAD

**Issue by jokergoo** [jokergoo/circlize#137]

**Comment by jezreel-me** [comment]
What do you mean by HiC datasets? Highly Complex datasets?

I'm actually adjusting your package to summarize the multiple outputs of my multi-Omics code to study drug interactions. A couple limitations that I encounter when I use my HiC datasets with your package are:
1. If your dataframe has a column with numeric values and NAs, you cannot plot the tracks, even if such column is not part of factors, x, region, y, or value. Temporary solution: Assign a value to the NAs using a function such as log2(1) to put 0s.
2. If you're to use circlize to from expression datasets from any Omics to show differential expression between groups, you have to re-structure your datasets to assign x positions, and that sometimes gives irregular patterns for the links that look unintuitive.

I want to upload some examples if I understood what HiC meant. 
Please feel free to contact me or leave your email to see how we can collaborate for both my figures or want to hear my insights about using multi-Omics datasets with circlize.

Thanks, 

Jezreel Pantaleon Garcia, MD
(jezreel.me@gmail.com)

**Comment by jokergoo** [comment]
Hi, "HiC" is a technology which can measure the interactions between genomic regions. https://en.wikipedia.org/wiki/Chromosome_conformation_capture#Hi-C_(all-vs-all)

and a Hi-C heatmap looks like 
![image](https://user-images.githubusercontent.com/449218/72244382-746cd700-35ee-11ea-819d-4231dd03d032.png)

But never mind, thanks for your thought. I will move your suggestion to a new issue.

**Comment by MichelMoser** [comment]
Hi, 

I would be super interested in circular Hi-C visualization and could contribute to code and testing. 

Was this closed because you already have working examples? 

Michel

**Comment by jokergoo** [comment]
No, I moved this discussion to #149

**Comment by jokergoo** [comment]
Hi, this is the circular HiC data visualization (the heatmap):

https://twitter.com/mpi_ie/status/1217364540305952769?s=20
