### ISSUE TITLE
chordDiagram() error

### ISSUE THREAD

**Issue by julianqz** [jokergoo/circlize#138]
While in most cases I have been able to use `chordDiagram` without issue, I noticed that in select cases where there is a lot of sparsity in the adjacency matrix, `chordDiagram` could break. Here is an example:

My adjacency matrix is essentially as follows:
```
sectors = LETTERS[1:4]
chordMat = matrix(NA, nrow=4, ncol=4, dimnames=list(sectors, sectors))
chordMat["A", ] = c(NA,5,0,0)
chordMat["B", ] = c(NA,NA,0,0)
chordMat["C", ] = c(NA,NA,NA,0)
```
That is:
```
chordMat
   A  B  C  D
A NA  5  0  0
B NA NA  0  0
C NA NA NA  0
D NA NA NA NA
```
Based on the adjacency matrix, I would expect a single link between sectors `A` and `B`.
However, when trying to plot this, an error arose:
```
chordDiagram(chordMat)
Error in rgb(rgb_mat, maxColorValue = 255, alpha = (1 - transparency) *  : 
  alpha level NA, not in 0:255
```

Is there a fix to this? Thanks!

**Comment by julianqz** [comment]
`circlize` v0.4.8 in R v3.6.0 on MacOS v10.14.5

**Comment by jokergoo** [comment]
Sorry for the late reply. It is because the dimension of the matrix has been decreased somewhere in the package (you only have one  value in the matrix). Now I have fixed it.

![image](https://user-images.githubusercontent.com/449218/70424333-7e3f6f80-1a6f-11ea-9e20-f2137a21eafe.png)
