### ISSUE TITLE
Circular heatmap outside plotting area

### ISSUE THREAD

**Issue by somakray** [jokergoo/circlize#139]
Hi,

Which parameters are to be adjusted for the heatmap being printed outside the plotting area? Example link given below. 

https://i.stack.imgur.com/3yXm2.png

secondly how to put row/column labels in the heatmap?

Thanks

**Comment by jokergoo** [comment]
1. you should set something like `circos.par(canvas.xlim = c(-2, 2), canvas.ylim = c(-2, 2))` to increase the margins of the circle (remember the circle is always drawn in a unit circle).

2. You need to go to each track and use `circos.text()` to add the labels. There is no function which adds row labels for heatmaps automatically.
