### ISSUE TITLE
Bug in numeric.column with a list of bedfiles

### ISSUE THREAD

**Issue by edurand** [jokergoo/circlize#14]
The following code fails: 
bedlist = list(generateRandomBed(nc=2), generateRandomBed(nc=2))
circos.initializeWithIdeogram()
circos.genomicTrackPlotRegion(bedlist, numeric.column = c(4, 5),
    panel.fun = function(region, value, ...) {
    i = getI(...)
    circos.genomicPoints(region, value, col = i, ...)
})

Error in circos.genomicTrackPlotRegion(bedlist, numeric.column = c(4, : Some of your `numeric.column` are not numeric.

**Comment by jokergoo** [comment]
since you specified the first argument as a list of data frame, each element in `numeric.column` corresponds to each data frame in `bed_list`. For example, in your case, if `numeric.column` is set to `c(4, 5)`, it means to use column 4 in `bed_list[[1]]` and column 5 in `bed_list[[2]]`.
