### ISSUE TITLE
A question about labeling a circle plot from a different dataframe with heatmap

### ISSUE THREAD

**Issue by amjass12** [jokergoo/circlize#141]
Hi all,

I have carried out some clustering through dist and hclust. This works well and I am happy with the results produced but i was wondering if there is a way of plotting the clustering PLUS annotating the plot with the samples that cause the clustering...

Context

This is hierarchical clustering of neuron activations in a layer obtained from a neural network. I would like to cluster the neuron activations together to see which are activated similarly. I would like to visualize which of my samples cause those neuron activations (and how highly)...

```
dend <-dend %>% 
  set("branches_k_color", k = 3) 

circlize_dendrogram(dend, facing = c("outside", "inside"),
  labels = T
  , labels_track_height = 0.1, dend_track_height = 0.5)
```

I have attached a plot of the results of the hierarchical clustering. the plot doesn't have
to be circular, it could be a normal dendogram...

But for each group (on the outside of the circle) i would like to be able to annotate the samples that actually cause that clustering and also maybe with some form of heatmap show the neuron activation score for those samples.

Has anybody done anything similar to this/ know a way of annotating a plot like this with the samples that cause the clustering and the scores that per sample that are causing this clustering? any suggestions would be highly appreciated!

Additionally, the dendogram is produced from a similarity matrix of a 100 x 100 marix.

the labelling exists in a separate data.frame of 140 by 100 (140 is the sample number) with their respective scores for how much they activate a node)... so the labelling and neuron score comes from a different dataframe for labelling... I am not sure how to implement the labelling and activation scores from a different data frame.

any insight would be much appreciated!

many thanks!!
[circle plot.pdf](https://github.com/jokergoo/circlize/files/3932912/circle.plot.pdf)

**Comment by jokergoo** [comment]
Maybe you can check following link that draws a heatmap with a dendrogram:

https://jokergoo.github.io/circlize_book/book/high-level-plots.html#heatmaps

In that example, the heatmap is manually drawn (I mean it is generated by the `circos.rect()` function). For your case, if the annotation you want to add is heatmap-like, you can use similar code as that draws the heatmap. And for the labels, you can use `circos.text()`, but you need to be careful of the ordering (because row/columns are reordered by hierarchical clustering).

**Comment by amjass12** [comment]
thank you! I have carried out the following code but am unsure of where to add circos.text in: 

I also get a peculiar error which is: 

`Error in order.dendrogram(dend) : 
  'order.dendrogram' requires a dendrogram`

The code above this line runs without issue and the clustering works fine:

```
mat = df[,3:100]
col_fun = colorRamp2(c(-2, 0, 2), c("green", "black", "red"))
factors = dense3$organ
mat_list = list(a = mat[, factors ])
dend_list = list(a = as.dendrogram(hclust(dist(t(mat_list[["a"]])))))
                 
circos.par(cell.padding = c(0, 0, 0, 0), gap.degree = 5)
circos.initialize(factors, xlim = cbind(c(0, 0), table(factors)))
circos.track(ylim = c(0, 10), bg.border = NA, panel.fun = function(x, y) {
    sector.index = CELL_META$sector.index
    m = mat_list[[sector.index]]
    
    dend = dend_list[[sector.index]]
    m2 = m[, order.dendrogram(dend)]
    col_mat = col_fun(m2)
    nr = nrow(m2)
    nc = ncol(m2)
    for(i in 1:nr) {
        circos.rect(1:nc - 1, rep(nr - i, nc), 
            1:nc, rep(nr - i + 1, nc), 
            border = col_mat[i, ], col = col_mat[i, ])
    }
})                 
```

I appreciate your help!

**Comment by jokergoo** [comment]
As the message tells, `dend` is not a `dendrogram` object. You need to check the value of `dend_list[[sector.index]]`. Since `dend_list` is a list of dendrogram, you need to check the value of `sector.index` which is encoded in `factors` (or `dense3$organ`).
