### ISSUE TITLE
PDF page circlize?

### ISSUE THREAD

**Issue by Manishbhaskar786** [jokergoo/circlize#142]
Can we read a pdf file (single page), circlize it and save the circlized pdf?

**Comment by jokergoo** [comment]
Maybe you can check the support for importing raster image?

https://jokergoo.github.io/circlize_book/book/graphics.html#raster-image

**Comment by Manishbhaskar786** [comment]
Thanks for this. :)
I read this raster section already. Raster is good for screen rendering. what I am lookig for is to read a vector PDF (publication quality) , circlize it and write a circlized vector PDF.

**Comment by jezreel-me** [comment]
circlized PDFs get easily vectorized when you import them to Illustrator. From there you can export to other formats such as SVG.
