### ISSUE TITLE
Overlapping regions in chordDiagram()

### ISSUE THREAD

**Issue by levvim** [jokergoo/circlize#143]
Hi all, 

I am trying to make a diagram showing shared and unshared regions between samples (using the unequal widths option to show the amount shared between samples). However, when I use the two width option without scaling, the regions overlap and are entirely out of place (see left diagram). The regions do not overlap when `scale=TRUE` or when using a single width option.

![Screen Shot 2019-12-13 at 2 59 02 PM](https://user-images.githubusercontent.com/6922460/70828519-83772400-1db9-11ea-8778-1fd9de0ccce3.png)

The code to reproduce this example is as follows:

```
c2=data.frame(from =c("R_shared", "R_private", "S_shared", "S_private", "L_shared", "L_private"),
        to = c("S_shared", "R_private", "L_shared", "S_private", "R_shared", "L_private"),
        value = c(1461525, 112730 , 182391 , 924901 , 1373387, 185977),
        value2 = c(168662 , 112730 , 1363928, 924901 , 1569266, 185977))

grid.col=c(R_shared = "goldenrod", R_private = "goldenrod", S_shared = "tomato2", S_private = "tomato2", L_shared = "cadetblue2", L_private = "cadetblue2")
col=adjustcolor(c("cadetblue3","NA","tomato","NA","goldenrod","NA"), alpha.f=.6)

chordDiagram(c2[,1:4], grid.col=grid.col, col=col, small.gap=1,
        link.sort=TRUE, link.decreasing=TRUE, link.overlap=FALSE, 
        scale=FALSE, symmetric=FALSE, self.link=1)
circos.clear()
```

Is there any way to fix this s.t. the width connected to each region correlates to the shared amount? Thanks!

using R version 3.6.0, circlize_0.4.8, macOS High Sierra 10.13.6

**Comment by jokergoo** [comment]
Hi, this is a bug in the package, currently you need to sort the data frame first by `to` column then by `from` column. I will fix it soon.

```r
chordDiagram(c2[order(c2$to, c2$from),1:3])
```

![image](https://user-images.githubusercontent.com/449218/72254616-ebad6580-3604-11ea-9728-2d6f40af050b.png)

**Comment by jokergoo** [comment]
Sectors in `to` have overlap to `from` and this is what I haven't tested.

**Comment by jokergoo** [comment]
Hi, this functionality is new and lack of testing. I have updated the package and can you update it and try your code again?

![image](https://user-images.githubusercontent.com/449218/72259211-2ec10600-3610-11ea-80d8-d36764cf2adc.png)

**Comment by levvim** [comment]
Hi @jokergoo, it works now! Thank you.
[circlize.pdf](https://github.com/jokergoo/circlize/files/4055642/circlize.pdf)
