### ISSUE TITLE
connectograms with chordDiagram

### ISSUE THREAD

**Issue by GerardYu** [jokergoo/circlize#145]
ChordDiagrm draws edges that comes out from a node, emerging from different origins which are tightly packed within the node.
is it possible to have these edges to come out from a single origin. Such that each node will only have one origin when the edges will emerge, and the width of the nodes are equal, regardless of the number of edges coming out of it?
here's an example of what I mean
![image](https://user-images.githubusercontent.com/34126910/71497861-fcd04580-2894-11ea-9fea-27aac179671d.png)

**Comment by jokergoo** [comment]
It is more like a network/graph instead a chord diagram. It is possible to draw it with _circlize_, but I am not sure whether _circlize_ is the best tool to visualize it. Maybe you can try other network tool like Cytoscape?

Following is a simple example to generate such a circular network:

```r
library(digest)
library(circlize)


mat = matrix(sample(c(0, 1), 80*80, p = c(95, 5), replace = TRUE), nrow = 80)
rownames(mat) =  sapply(rnorm(80), digest, "crc32")
colnames(mat) =  rownames(mat)


circos.initialize(fa = rownames(mat), xlim = c(0, 1))
circos.track(ylim = c(0, 1), panel.fun = function(x, y) {
	circos.text(CELL_META$xcenter, CELL_META$ycenter, 
		CELL_META$sector.index, facing = "clockwise",
		niceFacing = TRUE, adj = c(0, 0.5), cex = 0.6)
}, bg.border = FALSE, track.height = uh(2, "mm"), cell.padding = c(0, 0, 0, 0))

for(nm1 in rownames(mat)) {
	for(nm2 in colnames(mat)) {
		if(nm1 == nm2) next

		if(mat[nm1, nm2]) circos.link(nm1, 0.5, nm2, 0.5)
	}
}
```

![image](https://user-images.githubusercontent.com/449218/72260220-a728c680-3612-11ea-8761-19ba087c1886.png)
