### ISSUE TITLE
Half-transparent color lines for links

### ISSUE THREAD

**Issue by jezreel-me** [jokergoo/circlize#146]
Hi, 

This post is regarding the automatic line formatting of links from one sector to multiple sectors. I notice that the automatic line of the links is solid when my beds connect a few number of sectors (1 or 2), while the automatic line of links is half-transparent when my beds connects a greater number of sectors (4+). This works with any color, and it is a really cool feature to visualize links between multiple sectors when the number of links is very high. See pictures.

![Solid lines for links](https://user-images.githubusercontent.com/58693150/71795208-b43e2800-300a-11ea-9cf1-0dba80be6450.jpeg)
![Half-transparent links](https://user-images.githubusercontent.com/58693150/71795215-b902dc00-300a-11ea-95ed-a88669f2b949.jpeg)

A couple of questions:
1. Why does this happen? 
2. Are these lines or arrows or something else?
3. How can I implement that manually instead of being automatic? (Because I would like to implement that for plots with small number of sectors)
4. Can I apply that half-transparency as a half-color in lines? (I saw a previous post that this was not quite possible)

Thank you very much, 

Jezreel

My code for generating the links is:
df1 is the df with 3 sectors, and df2 is the one with 8 sectors, and their respective beds

circos.clear()
circos.par("track.height" = 0.1)
circos.genomicInitialize(data = df1 or df2, 
                         plotType = NULL)
circos.genomicTrackPlotRegion(data = c.all.DEMs.df)

circos.genomicLink(region1 = bed1.df1 or bed1.df2,
                   region2 = bed2 or bed1.df2,
                   border = NA)
circos.clear()

**Comment by jokergoo** [comment]
I guess it is because you set `border = NA` in `circos.genomicLinks()`. For those regions which are very small compared to the chromosome, they will become invisible (The links are actually polygons, when the plygon border is not drawn, the polygon will be transparent or invisible when the polygon is very thin). 

It would be great if you can attach the data objects you used for testing.
