### ISSUE TITLE
Cannot map colors to cytobands

### ISSUE THREAD

**Issue by psur9757** [jokergoo/circlize#147]
I am trying to draw a Circos plot for a non-model fungal organism. We only have scaffold level data. I generated the bed file from my annotation gff3.

BED file
```
      chrom chromStart chromEnd  name score
1 Sc0000000      11021    12299 g1549  0.34
2 Sc0000000      13368    19496 g1550  0.40
3 Sc0000000      23483    25346 g1551  0.47
4 Sc0000000      37456    43663 g1552  0.07
5 Sc0000000      47060    50774 g1553  0.47
6 Sc0000000      53851    59018 g1554  0.07
```

R Code
```
library(circlize)
cytoband.df = read.table("augustus.hints.gene.sorted.bed", colClasses = c("character", "numeric", "numeric", "character", "character"), col.names = c("chrom", "chromStart", "chromEnd", "name", "score"))
circos.initializeWithIdeogram(cytoband.df)
```

Error
```
Warning message:
Cannot map colors to cytobands. The ideogram won't be drawn. 
```

What do I need to change? Thank you for your help.

**Comment by jokergoo** [comment]
I think the cytoband data are only available for some species, such as human, mouse. In your case, you don't have cytoband for your species, and thus, you can just ignore this warning message, or you use `circos.genomicInitialize()`:

```r
circos.genomicInitialize(cytoband.df)
```

**Comment by psur9757** [comment]
Hi @jokergoo 

Thank you for getting back to me. Is it possible to create ideogram for my data?

When I run  `circos.genomicInitialize(cytoband.df)`, I get 
<img width="469" alt="Current Result" src="https://user-images.githubusercontent.com/37357172/72309928-7c9f4200-36d4-11ea-8398-e022d5d69397.png">

I want to get something like below, with the bands representing genes.
<img width="469" alt="Desired Outcome" src="https://user-images.githubusercontent.com/37357172/72310218-4f06c880-36d5-11ea-8018-8df9ae25adf4.png">

**Comment by jokergoo** [comment]
You mean the "scaffold"? How many are there? The `circos.genomicIdeogram()` is a simple function which actually uses `circos.genomicRect()` to draw the graph (you can read the source code of this function). If you have the color defined for each scaffold, you just create a new track and add rectangles there:

```r
circos.genomicInitialiez(...)
# and something like follows
circos.genomicTrackPlotRegion(df, ylim = c(0, 1), bg.border = NA, track.height = track.height,
	panel.fun = function(region, value, ...) {
		col = cytoband.col(value[[2]])
		circos.genomicRect(region, value, ybottom = 0, ytop = 1, col = col, border = NA, ...)
		xlim = get.cell.meta.data("xlim")
		circos.rect(xlim[1], 0, xlim[2], 1, border = "black")
	}, cell.padding = c(0, 0, 0, 0), track.margin = track.margin
)
```

**Comment by psur9757** [comment]
No I am trying to create a track with gene locations within a scaffold. The width of the rectangles will represent the length of the gene and the coloraturas will represent the function/pathway for the gene. For now I am working with just 1 scaffold to figure out the code needed. Then I will expand to all my 50+ scaffolds.

Scaffold1 is 6.5MB in length and has about 1500 genes. I want to represent it similar to Figure 8.2.

BED file
```
  scaffoldName geneStart geneEnd geneName geneColor
1    Scaffold1     11021   12299    g1549   #008000
2    Scaffold1     13368   19496    g1550   #000000
3    Scaffold1     23483   25346    g1551   #FF0000
4    Scaffold1     37456   43663    g1552   #008000
5    Scaffold1     47060   50774    g1553   #000000
6    Scaffold1     53851   59018    g1554   #FF0000
```

Code
```
library(circlize)
region=df[,2:3]
value=df[,4:5]
track.margin = c(0, 0)
track.height = 0.05
circos.genomicInitialize(df)
circos.genomicTrackPlotRegion(df, ylim = c(0, 1), bg.border = NA, track.height = track.height,
                              panel.fun = function(region, value, ...) {
                                col = cytoband.col(value[[2]])
                                circos.genomicRect(region, value, ybottom = 0, ytop = 1, col = col, border = NA, ...)
                                xlim = get.cell.meta.data("xlim")
                                circos.rect(xlim[1], 0, xlim[2], 1, border = "black")
                              }, cell.padding = c(0, 0, 0, 0), track.margin = track.margin
)
```

I get a blank track instead of something like Fig 8.2
<img width="469" alt="Current Result" src="https://user-images.githubusercontent.com/37357172/72403621-eb4cd000-37a6-11ea-9c77-e4e7a74b01b1.png">

I am constantly going through your manual but I really cannot figure it out for my case. Thank you for helping out.

**Comment by jokergoo** [comment]
Can you attach your `df` here as a file?

I think it is because this line:

```r
 col = cytoband.col(value[[2]])
```

`cytoband.col()` is only used for real cytoband data (e.g. with name `gpos100`, `gpos25`, ...). Since you don't have it, all the colors are returned as white.

If you want a colorful gene track, you need to define colors for genes.

**Comment by psur9757** [comment]
Thank you this worked. I will use the same system to add more tracks.

**Comment by ghost** [comment]
Hi @psur9757 , I am trying to do more or less the same as you but I cannot create the track as in Fig 8.2. Could you please share how you achieved it? Thanks!
