### ISSUE TITLE
Add GitHub Releases to match Cran versions

### ISSUE THREAD

**Issue by dgabbe** [jokergoo/circlize#148]
Hi Zuguang,

This is a suggestion regarding the tracking of the GitHub circlize code.  I stumbled on it by chance.  https://jokergoo.github.io/circlize_book/book/ as of today, displays _This is the documentation of the circlize package. Examples in the book are generated under version 0.4.9._

CRAN lists version 0.4.8.  Ok, next version has not been released.

But when I look at https://github.com/jokergoo/circlize/releases, only 0.2.5 is listed.  That makes it hard to compare 0.4.8 to 0.4.9 to see the changes.

I frequently find myself needing to look at the source code to figure out what I'm not understanding or what changed, but is not in the release notes.

The other advantage of using releases is I can install a specific version quite easily w/this R call:
```{r}
devtools::install_github("jokergoo/circlize@0.2.5") 
```

Thanks,

**Comment by jokergoo** [comment]
I normally directly release the package to CRAN. The one release on Github was only for testing purpose (as you can see it was added nearly 5 years ago). But, that is a good idea! I will also release the same version next time when I update the package to CRAN.
