### ISSUE TITLE
Link from a zoomed specific small region to other chromosomes

### ISSUE THREAD

**Issue by gp79** [jokergoo/circlize#154]
Hi,
I've managed to used the zoom function to zoom a single or multiple chromosomes.
Is it possible to zoom in further? I would like to zoom in on a specific gene to show some links going to several other chromosomes.
Thank you in advance!

**Comment by jokergoo** [comment]
No, I don't think so. I think circlize only supports one-level zooming.

**Comment by gp79** [comment]
Thanks a lot.
