### ISSUE TITLE
Is is possible to remove connection line for heatmap?

### ISSUE THREAD

**Issue by ShixiangWang** [jokergoo/circlize#156]
I am new to this tool and find it is very useful!

![image](https://user-images.githubusercontent.com/25057508/75564973-14d86700-5a88-11ea-847f-648798964880.png)

I want to remove the connection line in the heatmap and create a plot similar to

![image](https://user-images.githubusercontent.com/25057508/75565310-ae077d80-5a88-11ea-8737-67ccda294e28.png)

Is it possible?

**Comment by jokergoo** [comment]
The two heatmaps are different. In the first heatmap, the rectangles in the heatmaps are not in the original positions, so you need lines to connect to the original positions, while in the second plot, the rectangles are in the corresponding positions and thus you don't need connection lines here.
