### ISSUE TITLE
question about colors

### ISSUE THREAD

**Issue by corneliabuus** [jokergoo/circlize#157]
![Skærmbillede 2020-03-02 kl  16 04 46](https://user-images.githubusercontent.com/50442541/75688324-96eea880-5c9f-11ea-94ba-e59461bb09e6.png)
Hey

I don't think this is necessarily an issue, but i have problem finding the dokumentation for it. I've tried plotting different genomic data, at different timepoints, where the placement at the y-axis is the quantile of the frequency. I've managed to color by the 4 groups of frequencies, but i can't seem to change the colors of the points manually. Is is it possible to change these colors to e.g. a selfchosen vector of colors rather than the four default colors?

**Comment by corneliabuus** [comment]
I solved the problem by making a palette with the amount of colors i needed, and then used this code inside circos.genomicTrack(): 
i = getI(...)
circos.genomicPoints(region, variant, pch = 16, cex = 0.5, col =palette[i], ...)

**Comment by jokergoo** [comment]
Yes, in `circos.genomicPoints()` you used, the `col` argument can be a vector with the same length as the input regions.

**Comment by jokergoo** [comment]
You can replace `palettep[i]` to a vector of colors with the same length as `region`.
