### ISSUE TITLE
Chord intersection diagram

### ISSUE THREAD

**Issue by aosavi** [jokergoo/circlize#158]
Does the circlize package somehow allow the creation of chord intersection diagrams? This would be a strong way of visualizing more complex set intersection. This is what I mean:

- There are multiple sets, with multiple items in each set.
- If an item is in two sets (one intersection), there is a link between the item in both sets.
- If an item is in more sets (multiple intersections), there are multiple links from the item to the same items in the other sets.
- An item is not replicated in a single set (nor is the width of the item changed or the width of the links changed), so if there is an item with multiple lines going to the same item in other sets, _those lines overlap at the origin_.
- Preferably, the items in each set are somehow grouped such that multiple items that share the same intersection are grouped.

I hope this description is sufficient. Thank you!

NB. Previously, I posted it as a question on stackoverflow: https://stackoverflow.com/questions/54488154/how-to-create-a-chord-intersection-diagram-in-r.

**Comment by jokergoo** [comment]
Hi, thanks for your comments and sorry for the late reply. I totally missed this one!

Yes, these are very nice suggestions. `chordDiagram()` was originally designed for two sets. It is also possible for more than two sets, but I think we need to have another high-level function which wraps `chordDiagram()`. I will think about it and try to write something on it.

**Comment by jokergoo** [comment]
Today I tried to implement your idea. Not sure whether this is what you want:

Three sets:

![image](https://user-images.githubusercontent.com/449218/115027894-91b0e500-9ec4-11eb-9249-07fb006a552e.png)

10 sets:

![image](https://user-images.githubusercontent.com/449218/115028020-b3aa6780-9ec4-11eb-9af8-a7405b955263.png)

I also put the code here:

```r

n = 10
lt = sapply(1:n, function(i) {
	sample(letters, sample(5:15, 1))
})
names(lt) = LETTERS[1:n]

tb = sapply(lt, length)

m = list_to_matrix(lt)

lt2 = lapply(seq_along(lt), function(i) {
	lt[[i]][ order(rowSums(m)[ m[, i] > 0 ][lt[[i]]]) ]
})
names(lt2) = names(lt)

circos.initialize(sectors = names(lt2), xlim = cbind(rep(0.5, length(lt2)), tb + 0.5))
circos.track(ylim = c(0, 1), panel.fun = function(x, y) {
	el = lt2[[CELL_META$sector.index]]
	circos.text(1:length(el), 0.5, el)

	h = (rowSums(m[el, ])-1)/length(lt)
	circos.rect(seq_along(h) - 0.4, 0, seq_along(h) + 0.4, h, col = "#00000040", border = NA)
})


for(i in seq_len(nrow(m))) {
	if(sum(m[i, ]) > 1) {
		add_link(m[i, ], el = rownames(m)[i])
	}
}

add_link = function(x, el) {
	ind = which(x == 1)
	mm = combn(ind, 2)
	for(i in seq_len(ncol(mm))) {
		j1 = mm[1, i]
		j2 = mm[2, i]
		sector1 = names(lt2)[j1]
		sector2 = names(lt2)[j2]
		x1 = which(lt2[[j1]] == el)
		x2 = which(lt2[[j2]] == el)
		circos.link(sector1, x1, sector2, x2)
	}
}
```
