### ISSUE TITLE
df or bed file problem for circos.genomicDensity plot

### ISSUE THREAD

**Issue by daphnehoh** [jokergoo/circlize#159]
Hi @jokergoo,

I can't seem to understand why plotting `circos.genomicDensity` with my [bed file](https://github.com/jokergoo/circlize/files/4393790/tt1.bed.txt) (name: tt)
gives the following plot: 
![Rplot](https://user-images.githubusercontent.com/37231136/77763842-a8e12280-7076-11ea-8874-8edab9c0a0a9.png)
the code was:
```
circos.genomicInitialize(tt)
circos.genomicDensity(tt, col = "#0000FF80")
circos.clear()
```

So I try playing with `generateRandomBed` as below:
```
bed = generateRandomBed(1000, fun = rnorm)

circos.genomicInitialize(bed)
circos.genomicDensity(bed, col = "#0000FF80")
circos.clear()
```
gives the plot showing density, which is what I wanted:
![Rplot01](https://user-images.githubusercontent.com/37231136/77765107-bdbeb580-7078-11ea-8227-7b49614ff090.png)

So, I assumed something wrong with my bed file, and I compared both bed files 
```
head(bed) ; summary(bed) ; mode(bed) ; range(bed$value1)

   chr    start      end     value1
1 chr1   810521  2314677  0.7813694
2 chr1  2827623  4115027 -0.8536605
3 chr1  4431566 10164592 -1.7268942
4 chr1 11647454 11852166 -0.8847608
5 chr1 12086091 15964544  0.4475775
6 chr1 18672191 19251614  1.1001991
     chr                start                end                value1         
 Length:1005        Min.   :    24186   Min.   :   322829   Min.   :-2.901183  
 Class :character   1st Qu.: 30829588   1st Qu.: 32491244   1st Qu.:-0.727892  
 Mode  :character   Median : 66973382   Median : 68158763   Median : 0.008587  
                    Mean   : 76038481   Mean   : 77622412   Mean   :-0.014130  
                    3rd Qu.:110787146   3rd Qu.:112087101   3rd Qu.: 0.704155  
                    Max.   :246515848   Max.   :246620914   Max.   : 3.014366  
[1] "list"
[1] -2.901183  3.014366
```
```
head(tt) ; summary(tt) ; mode(tt) ; range(tt$value1)

    chr   start     end value1
1 chr07 3700000 3710000  0.000
2 chr07 3710000 3720000  0.156
3 chr07 3720000 3730000  0.000
4 chr07 3730000 3740000  0.000
5 chr07 3740000 3750000  0.000
6 chr07 3750000 3760000  0.000
      chr          start              end              value1       
 chr08  :387   Min.   :      0   Min.   :  10000   Min.   :0.00000  
 chr09  :362   1st Qu.: 710000   1st Qu.: 720000   1st Qu.:0.00000  
 chr10  :356   Median :1470000   Median :1480000   Median :0.00000  
 chr11  :280   Mean   :1571899   Mean   :1581870   Mean   :0.07838  
 chr12  :273   3rd Qu.:2350000   3rd Qu.:2360000   3rd Qu.:0.00000  
 chr13  :208   Max.   :3870000   Max.   :3875999   Max.   :7.80400  
 (Other):135                                                        
[1] "list"
[1] 0.000 7.804
```
Both data looked ... similar? at least in terms of data structure.
I am guessing the problem might come from the value from `range(tt$value1)`?

Please advice :)

**Comment by jokergoo** [comment]
The input for `circos.genomicDensity()` should be a list of discrete regions, then `circos.genomicDensity()` will split each chromosome into windows with fixed width and calculates what percent of each window is overlapped by the input regions.

For your case, I think your bed file already has the value of "genomic density", thus, you don't need to use `circos.genomicDensity()`, while you can directly use `circos.rect()` or `circos.genomicRect()` to draw rectangles where bar heights correspond to the values (the fourth column) in the bed file:

```r
library(circlize)

bed = read.table("https://github.com/jokergoo/circlize/files/4393790/tt1.bed.txt", head = TRUE, stringsAsFactors = FALSE)
bed = bed[bed[, 4] > 0, ]  # to reduce the data frame
bed[, 1] = gsub("chr0+", "chr", bed[, 1])

circos.initializeWithIdeogram()

circos.genomicTrack(bed, 
    panel.fun = function(region, value, ...) {
        circos.genomicRect(region, value, ytop.column = 1, ybottom = 0, border = "red", col = "red", ...)
})
```

![image](https://user-images.githubusercontent.com/449218/77769236-d82a6c00-7043-11ea-927c-ac4f02f9930b.png)

**Comment by daphnehoh** [comment]
Thank you very much for the clarification! 
Also, thank you for this awesome R package! 
:D
