### ISSUE TITLE
chordDiagram: change the width of one track

### ISSUE THREAD

**Issue by SalvatoreRa** [jokergoo/circlize#162]
Hi,
I have a dataframe and I want to da a chordDiagram. In this data frame I have a specific sector (just one) that is connected to the all the others.

```r
library(circlize)
df = data.frame(from = "A", to = LETTERS[1:12], value = sample(5:50, 12, replace=T))
chordDiagram(df)
circos.info()
```

when I execute this code, what I am obtaining is that there are two track 1, with A that is occupying 50 % of the circle and the other in the other size. I have tried to scale

```r
chordDiagram(df, scale = TRUE)
```

but all the sector are the same. what I would like to do is to reduce the sector A and enlarging the other sectors but I would like to mantain the fact that the other sectors are proportional to the value column

**Comment by jokergoo** [comment]
You can check this link: https://jokergoo.github.io/circlize_book/book/the-chorddiagram-function.html#unequal-width-of-the-link-ends

You need to add one more column in `df`.

```r
df = data.frame(from = "A", to = LETTERS[1:12], value1 = sample(5:50, 12, replace=T))
df$value2 = df$value1*2
chordDiagram(df)
```

![image](https://user-images.githubusercontent.com/449218/80872425-2f120980-8cb2-11ea-8905-b409521b870c.png)

**Comment by SalvatoreRa** [comment]
thank you for the help
