### ISSUE TITLE
Make chemokine/cytokine-receptor interaction plot from Seurat onject

### ISSUE THREAD

**Issue by happar73** [jokergoo/circlize#163]
Hi,

I am wondering whether we can extract the chemokine/cytokine and receptor data from Seurat object,  and make the circlize plot?

I know how to get the data, I am wondering whether it is OK for you to write the code, editor the data frame for us to make the plot.

### get the interasting genes
genes <- c("Ccl4", "Ccl5", "Cxcr6",  "Cxcl2", "Ccr1", "Ccr5",  "Cxcl16")

### get the matrix data from seurat object with interesting cytokines and receptors
A <- as.data.frame(seurat_object[["RNA"]]@data[genes, ])

### add cluster information
B <- rbind.data.frame(A, seurat_object$seurat_clusters)

The data frame has chemokines/receptors, receptors and cluster information, but all the information for the circlize plot are on the rows. Then how can I make the chemokine/cytokine-receptor interaction plot with cluster names?
like the following plot, first layers including different cytokines and receptor from same cluters, sceond layers are clusters. Then the cytokines and receptors will be connected according to the some correlation correlation coefficient.

![image](https://user-images.githubusercontent.com/50378244/80286662-8710a500-86e1-11ea-9af1-12498b79871a.png)

Thanks,
Yale

**Comment by jokergoo** [comment]
Hi,

This is a very specific case for a research field. circlize aims to provide a general solution for circular visualization and it won't implement for very specific usages. It is better for users who are working in the field, e.g. your colleagues, to write code for this. They can refer to the following link to get a clue of how to implement it:

https://jokergoo.github.io/circlize_book/book/advanced-usage-of-chorddiagram.html#multiple-group-chord-diagram
