### ISSUE TITLE
unable to assign numeric.column to dataframe list

### ISSUE THREAD

**Issue by alleny1** [jokergoo/circlize#165]
Hi, 
I followed the vignette of circlize to insert a lists of dataframe and to specify numeric.column at the same time. Although the length of numeric.column was the same as the number of dataframes, which was two in my case, the result showed  "Some of your `numeric.column` are not numeric".  

The codes are as follows:
```

bed_list = list(generateRandomBed(nr = 30, nc = 3), generateRandomBed(nr = 30, nc = 3))


circos.par("track.height" = 0.1)
circos.initializeWithIdeogram(plot = NULL)

# column 4 in the first bed and column 5 in the second bed
circos.genomicTrack(bed_list, numeric.column = c(4,5),
    panel.fun = function(region, value, ...) {
        i = getI(...)
        circos.genomicPoints(region, value, col = i, ...)
})


circos.clear()
```
I would truly appreciate your help if you can help me assign numeric.column to dataframe list. Thank you!

**Comment by jokergoo** [comment]
I think `numeric.column` does not work when the input is a data frame list. It only works when the input is a data frame with multiple data columns.

**Comment by alleny1** [comment]
Hi, 
Thank you for your kind assistance!

The problem I am facing is how to plot specific columns (i.e. column number 4 in the first data frame and number 5 in the second data frame) from each data frame in the data frame list.

According to page 48 of the reference manual, the default value for numeric.column is a vector with the same length as the number of data frames and with the value of the first numeric column (generally column number 4 in every data frame). 

Also, based on the information in section 10.1.2 named "Input is a list of data frames" of the circlize vignette, the length of numeric.column can only be one or the number of data frames. 

Therefore, what solutions would you suggest if I want to extract information other than column number 4 or different columns between data frames in a data frame list? Thank you!

**Comment by jokergoo** [comment]
Hi, that was a bug. Now I have fixed it. Please update from GitHub.
