### ISSUE TITLE
Add text labels inside blank track?

### ISSUE THREAD

**Issue by bhanratt** [jokergoo/circlize#166]
Hi,

So I realized that adding gene labels with `circos.genomicLabels()` cannot be used at the same time with hg19 ideogram that labels the chromosomes and adds coordinate axis ticks. So I thought to add the chromosome numbers inside of a blank track I initialized instead. I can't figure out how to move the text labels to be within the boxes. I've attached a picture that shows what I am trying to do and below is demo code I am using. When I use `circos.txt()` it just kind of places it outside of the plot and I have tried tweaking the settings but can't figure out how to place it inside of the track I initialized. =

```
circos.par("track.height" = 0.1)
circos.initializeWithIdeogram(plotType = NULL)
#circos.genomicLabels(snv, labels.column = 4, side = "outside")
circos.genomicIdeogram()
circos.track(ylim = c(0, .1))
circos.text(1, 1, "Chr1", facing = "inside", cex = 0.8, track.index=1)
circos.clear()
```

![chrlabels](https://user-images.githubusercontent.com/15003472/81339454-1499b080-9063-11ea-8f63-9f998d723db7.png)

**Comment by jokergoo** [comment]
You can do:

```r
circos.initializeWithIdeogram(plotType = NULL)
circos.genomicIdeogram()
circos.track(ylim = c(0, 1), panel.fun = function(x, y) { # values of ylim is not important here
	circos.text(CELL_META$xcenter, CELL_META$ycenter,
		CELL_META$sector.index, facing = "inside", cex = 0.8)
})
circos.clear()
```

![image](https://user-images.githubusercontent.com/449218/81692347-91ab9800-945e-11ea-98b1-c059fd76bfa5.png)

**Comment by bhanratt** [comment]
Brilliant. Thanks!
