### ISSUE TITLE
fill wrong colors with a for loop

### ISSUE THREAD

**Issue by YiweiZhu** [jokergoo/circlize#167]
Hi,
I aim to create ractangles with variable colors using a for loop. However, the colors are mistaken. The reactagles would be filled with the right color if I create one rectangle at one time. 

my code of the for loop was:
`for (i in 1:9){
  circos.rect(xleft = region1$start[i],ybottom = 0.1,ytop = 0.9,xright = region1$end[i],sector.index = "a",track.index = 1,col=region1$color[i])
} ` 

the data frame was:
>   start end   color
1    10  20 #ffffb3
2    20  60 #bebada
3    60  65 #8dd3c7
4    65  75 #fb8072
5    75  80 #8dd3c7
6    80  90 #fb8072
7    90  95 #8dd3c7
8    95 105 #fb8072
9   105 110 #8dd3c7

the wrong colors of rectangles: 
![Rplot01](https://user-images.githubusercontent.com/41197115/81396991-0cbc3800-9159-11ea-8d17-2495833d9f7f.png)

How to solve it?

**Comment by YiweiZhu** [comment]
I find it is due to the factor class of region1$color[i]. 
change the code `col=region1$color[i])` to `col=as.character(region1$color[i])`, solve the problem.

**Comment by jokergoo** [comment]
I think from R-4.0.0, you won't have this problem because in the data frame, the character column will not be converted to a factor by default.

**Comment by YiweiZhu** [comment]
Hi, Zuguang! Thanks for your further information!
