### ISSUE TITLE
Regression: circos.track() takes wrong order

### ISSUE THREAD

**Issue by rickhelmus** [jokergoo/circlize#169]
Hello,

I just updated to the 0.4.9 release and noticed point graphs are in reverse order. Example code:

```R
library(circlize)
library(data.table)

set.seed(999)
mat = matrix(sample(18, 18), 3, 3) 
rownames(mat) = paste0("S", 1:3)
colnames(mat) = paste0("E", 1:3)

df = data.frame(from = rep(rownames(mat), times = ncol(mat)),
                to = rep(colnames(mat), each = nrow(mat)),
                value = as.vector(mat),
                stringsAsFactors = FALSE)

cdf <- chordDiagram(df, preAllocateTracks = 1)

allLabels <- union(df[[1]], df[[2]])
vals <- data.table(label = c(rep(paste0("S", 1:3), each = 5), rep(paste0("E", 1:3), each = 25)))
vals[grepl("S", label), x := rep(1:5, 3)]
vals[grepl("E", label), x := rep(1:25, 3)]
vals[, y := x]

circlize::circos.track(factors = vals$label, x = vals$x, y = vals$y,
                       ylim = c(0, 25), track.index = 1,
                       panel.fun = function(x, y)
                       {
                           x <- x / (max(x) / circlize::get.cell.meta.data("xrange"))
                           circlize::circos.points(x, y, cex = 0.5, col = "blue", pch = 16)
                       })


circos.clear()
 ```

Desired result: the graphs with more points (1:25) should be on top of E1-E3.
Actual result: the graphs with more points are with S1-S3.

![image](https://user-images.githubusercontent.com/37015911/81934519-5d1b1600-95ef-11ea-9e11-3bf6850367d1.png)

On previous releases of circlize the result is:
![image](https://user-images.githubusercontent.com/37015911/81934844-efbbb500-95ef-11ea-8d5a-78791435286b.png)

Any workarounds? Or are things supposed to work differently now?

Thanks,
Rick

**Comment by jokergoo** [comment]
Thanks for reporting! Now, this bug is fixed and you can update from GitHub. I will update to CRAN after a careful check.

![image](https://user-images.githubusercontent.com/449218/82329286-5f131980-99e1-11ea-9402-303e9feadbd6.png)
