### ISSUE TITLE
Error in if (ncut) { : argument is not interpretable as logical

### ISSUE THREAD

**Issue by royfrancis** [jokergoo/circlize#17]
Here is a working example of my error

```
df_genome <- data.frame(name=c("a","b","c"),start=c(1,1,1),end=c(10,20,50))
df_genes <- data.frame(name=c("a","a","a","b","b","c"),start=c(3,4,9,6,14,20),end=c(5,7,10,10,18,40))
#adding a column value since it is needed in circos.genomicTrackPlotRegion
df_genes$value <- rep(1,nrow(df_genes))

circos.genomicInitialize(df_genome)
circos.genomicTrackPlotRegion(df_genes, panel.fun = function(region, value, ...) {
  circos.genomicLines(region, value, type = "segment", lwd = 2, ...)
})
```
`
Error in if (ncut) { : argument is not interpretable as logical`

**Comment by jokergoo** [comment]
Hi,

You need to manually set `ylim` option. In following function, by default if `ylim` is not set, the value will be calculated from the 4th column in `df_genes`. In your case, the 4th column contains values all equal to 1, which means, the range is c(1, 1) which is actually invalid for `ylim`.

I think it is a good idea to check this scenario and throw errors with more informative message.

Following two pieces of code works:

```
circos.genomicInitialize(df_genome)
circos.genomicTrackPlotRegion(df_genes, ylim = c(0, 2), panel.fun = function(region, value, ...) {
  circos.genomicLines(region, value, type = "segment", lwd = 2, ...)
})
```

or if values in the 4th column in `df_genes` are not the same:

```
circos.genomicInitialize(df_genome)
df_genes$value[3] = 2
circos.genomicTrackPlotRegion(df_genes, panel.fun = function(region, value, ...) {
   circos.genomicLines(region, value, type = "segment", lwd = 2, ...)
})
```

**Comment by royfrancis** [comment]
That works. Thanks!
