### ISSUE TITLE
How to do circos.link with a table

### ISSUE THREAD

**Issue by manighanipoor** [jokergoo/circlize#170]
Hi,

I have a table with 4 columns with this format (first 2 rows shown): 
     NC_006088.5    7402    NC_006103.5     2184966    
     NC_006088.5    8461    NC_006105.5     11273457

For each row, I want to link the first two columns (chr name & position) with the second two columns. In other words, I do not want to write circos.link for each row. I your book you did not explain how we can do it.

**Comment by jokergoo** [comment]
You can use `circos.genomicLink()` function. This function needs two data frames (like in bed format) as input. For your table, you should convert it into two data frames. Let's say, the variable `tb` contains your four-column table. The two data frames can be defined as:

```r
df1 = tb[, c(1, 2, 2)] # chr, start, end
df2 = tb[, c(3, 4, 4)] # chr, start, end
```

Then you send `df1` and `df2` to `circos.genomicLink()`:

```r
circos.genomicLink(df1, df2)
```

**Comment by manighanipoor** [comment]
Thanks for quick response, I did that but it did not work. I got this error:

Error in names(sector.data) <- colnames(.SECTOR.DATA)[-1] : 
  'names' attribute [6] must be the same length as the vector [0]

could you please have a look at my code and let me know what is wrong ?

Here is the first rows of my tables:

Genome (chr, start, end):
NC_006088.5     1      197608386

bed (chr, position, chr, position):
NC_006088.5      7402           NC_006103.5            2184966

and here is my code:

library(tidyverse)
library(circlize)
Genome <- read_tsv("Genome", col_names = FALSE)
chr_names <- c(1:28, 30:33, "W", "Z")
bed <- read_tsv("bed", col_names = FALSE)
bed_1 <- bed[, c(1, 2, 2)]
bed_2 <- bed[, c(3, 4, 4)]

circos.par(start.degree = 90)
circos.genomicInitialize(Genome, chr_names, axis.labels.cex = 0.3*par("cex"), labels.cex = 0.7*par("cex"))

circos.track(ylim = c(0, 1), panel.fun = function(x, y) {
  xlim = CELL_META$xlim
  circos.rect(xlim[1], 0, xlim[2], 1, col = rand_color(1))},
  track.height = 0.05, bg.border = NA)

circos.genomicLink(bed_1, bed_2)

**Comment by jokergoo** [comment]
Please also attach the two files ‘Genome’ and ‘bed’

**Comment by manighanipoor** [comment]
I changed "read_tsv" to "read.delim" and it resolved the issue.
Thanks
