### ISSUE TITLE
how to find maximum frequency (peak height) of histogram in circos.trackHist

### ISSUE THREAD

**Issue by manighanipoor** [jokergoo/circlize#174]
Hi, 
In order to compare different histograms obtained by circos.trackHist, I need to know the maximum frequency (maximum number of datapoints per bin) for each plot. Could you please let me know how I can get this ?

Cheers,
Mani

**Comment by jokergoo** [comment]
Sorry, you cannot directly get this information, but you can get the maximal value on the y-axes for the whole histogram track by, e.g.

```r
x = rnorm(1600)
factors = sample(letters[1:16], 1600, replace = TRUE)
circos.initialize(factors = factors, x = x)
circos.trackHist(factors = factors, x = x, col = "#999999", border = "#999999")
get.cell.meta.data("ylim", sector.index = "a", track.index = 1)
## [1]  0 38
```

You can treat 38 is the maximal frequency of the histograms (although it is a little bit higher than that).

Once you have a maximal value for all histograms in all plots, you can set this value to the `ylim` argument in `circos.trackHist()`:

```r
circos.trackHist(..., ylim = c(0, max_value))
```

To use the `ylim` argument, you need to install the newest version from Github.
