### ISSUE TITLE
error in circos.genomicLink when loading dataframe with read_tsv

### ISSUE THREAD

**Issue by manighanipoor** [jokergoo/circlize#176]
Hi, I closed this issue before, because when I use read.delim instead, it worked but I realized that the position of the last 4 chromosomes have changed in the graph. Following is my initial code where I used read_tsv, but get this error :
"
Error in names(sector.data) <- colnames(.SECTOR.DATA)[-1] : 
  'names' attribute [6] must be the same length as the vector [0]    "
But when I used read.delim instead, it works but the position of the last 4 chromosomes changes (e,g. chr 32 is actually chr "Z" and chr "W" is actually chr 32 and chr "Z" is actually chr "W"). Could you please have a look at the code and files to see if we can resolve the problem of using read_tsv.

Cheers
Mani

Here is my code when using read_tsv (I attached the files): 

```r
library(tidyverse)
library(circlize)
chickenGenome <- read_tsv("chickenGenome.txt", col_names = FALSE)
chr_names <- c(1:28, 30:33, "W", "Z")
chicken_tra <- read_tsv("sniffles_chicken_TRA_chr_position_link_RE_2_more.txt", col_names = FALSE)
Tra_1 <- chicken_tra[, c(1, 2, 2)]
Tra_2 <- chicken_tra[, c(3, 4, 4)]

circos.par(start.degree = 90)
circos.genomicInitialize(chickenGenome, chr_names, axis.labels.cex = 0.3*par("cex"), labels.cex = 0.7*par("cex"))

circos.track(ylim = c(0, 1), panel.fun = function(x, y) {
  xlim = CELL_META$xlim
  circos.rect(xlim[1], 0, xlim[2], 1, col = rand_color(1))},
  track.height = 0.05, bg.border = NA)

circos.genomicLink(Tra_1, Tra_2, col = rand_color(nrow(Tra_1)), h.ratio = 0.7)
circos.clear()
```

[chickenGenome.txt](https://github.com/jokergoo/circlize/files/4673646/chickenGenome.txt)
[sniffles_chicken_TRA_chr_position_link_RE_2_more.txt](https://github.com/jokergoo/circlize/files/4673647/sniffles_chicken_TRA_chr_position_link_RE_2_more.txt)

**Comment by jokergoo** [comment]
I ran your code without any error. Maybe you should try with the newest version of the package.

![image](https://user-images.githubusercontent.com/449218/82758859-62dfdb00-9de9-11ea-942a-d1ab672d99f9.png)

**Comment by manighanipoor** [comment]
I just updated Circlize package in Rstudio but I still get that error. Is there any other way I can get new version ?

**Comment by jokergoo** [comment]
```r
library(devtools)
install_github("jokergoo/circlize")
```

**Comment by manighanipoor** [comment]
Thanks a lot for your help. It worked.
