### ISSUE TITLE
R circlize chordDiagram producing poor image quallity.

### ISSUE THREAD

**Issue by Lamm-a** [jokergoo/circlize#177]
I am attempting to make a chord diagram of a fairly large 18*65 table (not every cell has a value).

I have generated the image I want but the quallity of it is nothing like what is shown on the [github](https://jokergoo.github.io/circlize_book/book/the-chorddiagram-function.html#basic-usage-1) seen below: 
![image](https://user-images.githubusercontent.com/49655395/82869582-c9224600-9f2e-11ea-9d01-f2d08268bfa3.png)

I figure maybe the number of cells needing to be plotted may cause problems but otherwise I am not sure why i get such a difference:

```
circos.par(gap.after = c(rep(2, ncol(chord_data)-1), 10, rep(2, 8-1), 5, rep(2, 10-1), 5, rep(2, 5-1), 5, rep(2, 3-1), 5, rep(2, 1), 5, rep(2, 12-1), 5, rep(2, 10-1), 5, rep(2, 6-1), 5, rep(2, 7-1), rep(2, 3-1), 10))

    png(file = "antismash_by_type.png", width = 800, height = 800)
    chordDiagram(chord_data,
                 grid.col = grid.col,
                 order = order, 
                 annotationTrack = "grid",
                 preAllocateTracks = 1)

    circos.track(track.index = 1, panel.fun = function(x, y) {
      circos.text(CELL_META$xcenter, CELL_META$ylim[1], CELL_META$sector.index, 
                  facing = "clockwise", niceFacing = TRUE, adj = c(0, 0.5))
    }, bg.border = NA)
    dev.off()
```
![image](https://user-images.githubusercontent.com/49655395/82869637-e1926080-9f2e-11ea-90e9-c0a2ec224abd.png)

Secondly my chords do not appear to be scaling to the value of the cell which ranges from 0-100 and [from what I read](https://jokergoo.github.io/circlize_book/book/the-chorddiagram-function.html#scaling) this is meant to occure by default but does not appear to be.

EDIT:

I have tested with a smaller version of the datset and still get low quallity images:
![image](https://user-images.githubusercontent.com/49655395/82891852-bddf1280-9f4e-11ea-8081-1b0afd49df32.png)

**Comment by jokergoo** [comment]
I think you should save the PNG with higher resolution (set the `res` argument in `png()`), you can save the image in PDF or SVG.

**Comment by Lamm-a** [comment]
I have tried this but get odd results, the defult I believe is 72 and the following are with `res = 800`:
![image](https://user-images.githubusercontent.com/49655395/82893887-0815c300-9f52-11ea-9334-d610641a0a60.png)
 And `res = 200`:
![image](https://user-images.githubusercontent.com/49655395/82893930-18c63900-9f52-11ea-8c8b-9b79d06e937f.png)

It seems to mostly affect the label size and streches the image in weird ways whilst still keeping it low quallity. The low quallity image also appears when i don't write the output to a png but just tot he Rstudio gui output.

**Comment by jokergoo** [comment]
1. I think when you set the `res` of png, you should also increase the image size accordingly, e.g.

```r
factor = 2
png(..., width =width*2, height = height*2, res = 72*factor)
```

2. for `pdf()`, the unit of the figure size is inch, so the value should be:

```r
pdf(file = "antismash_by_type.pdf", width = 7, height = 7)
```

**Comment by Lamm-a** [comment]
Ah okay i will give that a try then, thanks. Is there a way to make only column lables be shown and not row lables?

**Comment by askol-lurie** [comment]
I'm having the same issue, but when using circos.genomicLink. And genomicRect for that matter.  Any help would be immensely appreciated. 

Here's an example of the code and image in pdf.
```
  pdf(file = outFile, width=12, heigh=12)
    circos.par("start.degree" = 90)
    circos.genomicInitialize(chrInfo)
    for (t in types){
        bed1 <- m1 %>% filter(type == t) %>% select(1,2,3) %>%
            as.data.frame()
        bed2 <- m2 %>% filter(type == t) %>% select(1,2,3) %>%
            as.data.frame()
        color <- colorsType[which(types == t)]
        circos.genomicLink( bed1, bed2, border=NA, col = color)
    }
    circos.clear()

```
![image](https://user-images.githubusercontent.com/57679796/82925345-32ac4f80-9f43-11ea-9a4e-241dead867fb.png)

**Comment by jokergoo** [comment]
@askol-lurie , for your case, I would suggest also to add `border = color`. Links are actually drawn as polygons. When the polygons are very thin, the links will look ugly if the borders are removed.

**Comment by Lamm-a** [comment]
@jokergoo Is there anyway to only show lables on column segments? Without having to remove row names in the input dataframe that is.

**Comment by jokergoo** [comment]
You can first turn off all the labels by setting `annotationTrack` argument, then later manually add the labels by `circos.track()`. See examples at:

https://jokergoo.github.io/circlize_book/book/advanced-usage-of-chorddiagram.html#customize-sector-labels

For your case, you can test whether the current sector corresponds to the "columns" in your data frame in the `panel.fun`.

**Comment by Lamm-a** [comment]
From what I understand it is  `CELL_META$sector.index` which is the actualy text lable that `circos.text` is applying. I just don't know how to limit that to only columns and the tutorial shows no examples of adjusting what lables are shown, it only seems to show manipulation of lables.

**Comment by jokergoo** [comment]
Check this example:

```
> set.seed(999)
> mat = matrix(sample(18, 18), 3, 6) 
> rownames(mat) = paste0("S", 1:3)
> colnames(mat) = paste0("E", 1:6)
> 
> df = data.frame(from = rep(rownames(mat), times = ncol(mat)),
+     to = rep(colnames(mat), each = nrow(mat)),
+     value = as.vector(mat),
+     stringsAsFactors = FALSE)
> df
   from to value
1    S1 E1     4
2    S2 E1     7
3    S3 E1     9
4    S1 E2    14
5    S2 E2     1
6    S3 E2    10
7    S1 E3    13
8    S2 E3     6
9    S3 E3     3
10   S1 E4    17
11   S2 E4     8
12   S3 E4    16
13   S1 E5     5
14   S2 E5    12
15   S3 E5    11
16   S1 E6     2
17   S2 E6    15
18   S3 E6    18
> 
> 
> chordDiagram(df, annotationTrack = "grid")
> circos.track(track.index = 1, bg.border = NA, panel.fun = function(x, y) {
+     if(CELL_META$sector.index %in% df[, 2]) {
+         circos.text(CELL_META$sector.index, x = CELL_META$xcenter, 
+             y = CELL_META$cell.ylim[2], adj = c(0.5, -0.1))
+     }
+ })
```
![image](https://user-images.githubusercontent.com/449218/83007951-baae5a00-a014-11ea-8e83-a795557a2c2f.png)

**Comment by askol-lurie** [comment]
> @askol-lurie , for your case, I would suggest also to add `border = color`. Links are actually drawn as polygons. When the polygons are very thin, the links will look ugly if the borders are removed.

Thanks for the suggestion. I gave it a try. For some reason the smoothness of the curve seems to be dependent on the line's origin. Are there any additional tricks I could try to improved the smoothness further. I don't know if it's worth noting this, but I'm having the same issue with circosRect. Thanks again for your responsiveness and help. Code and image follow:

`
   ##
    types <- c("Neither", "Germ", "Som", "Both")
    colorsType <- c("gray50", "navyblue", "red", "darkorchid4")
    colors <- colorsType[match(m1$type , types)]
    
    ## PLOTTING STARTS HERE
    pdf(file = outFile, width=7, heigh=7)

    circos.par("start.degree" = 90)

    par(mar = c(1, 1, 1, 1))
    circos.genomicInitialize(chrInfo, plotType = NULL)
    circos.trackPlotRegion(ylim = c(0, .2), panel.fun = function(x, y) {
        chr = get.cell.meta.data("sector.index")
        xlim = get.cell.meta.data("xlim")
        ylim = get.cell.meta.data("ylim")
        circos.rect(xlim[1], 0, xlim[2], 0.02)
         if (chr %in% c(1:22, "X", "Y")) {## if (grepl("\\.", chr) == FALSE){
            print(chr)
            circos.text(mean(xlim), 0.15, chr, cex = 1.5,
                        facing = "clockwise",
                        niceFacing = TRUE)
        }
    }, bg.border = NA)
    
    for (t in types){
        
        bed1 <- m1 %>% filter(type == t) %>% select(1,2,3) %>%
            as.data.frame()
        bed2 <- m2 %>% filter(type == t) %>% select(1,2,3) %>%
            as.data.frame()
        color <- colorsType[which(types == t)]
        circos.genomicLink( bed1, bed2, border=color, col = color)
    }
    circos.clear()
`

![image](https://user-images.githubusercontent.com/57679796/83056716-7d00ff80-a01b-11ea-9c00-17f759c5e020.png)

`  
    ##
    pdf(file = outFile, width = 7, height=7)
    circos.par("start.degree" = 90)

    par(mar = c(1, 1, 1, 1))
    circos.genomicInitialize(chrInfo, plotType = NULL)
    circos.trackPlotRegion(ylim = c(0, .2), panel.fun = function(x, y) {
        chr = get.cell.meta.data("sector.index")
        xlim = get.cell.meta.data("xlim")
        ylim = get.cell.meta.data("ylim")
        circos.rect(xlim[1], 0, xlim[2], 0.02)
        if (chr %in% c(1:22, "X", "Y")) {
            circos.text(mean(xlim), 0.15, chr, cex = 1.5,
                        facing = "clockwise",
                        niceFacing = TRUE)
        }
    }, bg.border = NA)

    ##
    ## plot genes that have issues ##
    ##
    circos.genomicTrack(
        g, ylim=c(.2,1.2),
        panel.fun = function(region, value, ...){

             if (nrow(region) != 0){
                 for (type in unique(value$type)){
                     l = value$type == type
                     color = colorsType[which(types == type)]
                     circos.genomicRect(                         
                         region[l, ,drop = FALSE],
                         ytop = 1.2,
                         ybottom = .2,
                         col = color,
                         border=color)
                 }
             }
        }, bg.border="black", track.height = .1)
    
    circos.genomicTrack(
        b, 
        ylim = c(0.5, n+.3),
        panel.fun = function(region, value, ...) {
            
            for( i in 1:length(cats)){
                c = cats[i]
                l = grepl(c, value$Issue)
                nissue = sum(l)
                
                ## add rectangular tracks to indicate type
                ## of issue
                if (sum(l) > 0){
                    circos.genomicRect(
                        region[l, , drop = FALSE],
                        ytop = n - i + 1 + .5, 
                        ybottom = n - i + 1 - 0.5,
                        col = colors[i], border = colors[i])
                }
            }
        }, bg.border = "black", track.height = 0.4)
    circos.clear()

    dev.off()
`

**Comment by jokergoo** [comment]
Maybe you can try other png implementation, such as https://ragg.r-lib.org/articles/ragg_quality.html?

**Comment by askol-lurie** [comment]
I tried the app_png from ragg and if a plot at an obscene resolution, it does improve, although still some aliasing. I'm happy to share the code here if that'd be useful to others.
