### ISSUE TITLE
Unable to suppress label printing in circos.trackPlotRegion

### ISSUE THREAD

**Issue by askol-lurie** [jokergoo/circlize#178]
Hi, 
  I'm trying to initialize my plot while suppressing the labels for alternative chromosomes. I've tried a couple of different tactics, but none have worked. I don't understand why the following code (and variations of it, doesn't work). Is there something I'm not understanding about the circos.text function. Any help with this would be greatly appreciated.  

Best, 
Andrew

Here's the code:
`  pdf(file = outFile, width=12, heigh=12)
    circos.par("start.degree" = 90)
  
    par(mar = c(1, 1, 1, 1))
    circos.genomicInitialize(chrInfo, plotType = NULL)
    circos.trackPlotRegion(ylim = c(0, .2), panel.fun = function(x, y) {
        chr = get.cell.meta.data("sector.index")
        xlim = get.cell.meta.data("xlim")
        ylim = get.cell.meta.data("ylim")
        circos.rect(xlim[1], 0, xlim[2], 0.02)

        ## chr = if (grepl("\\.", chr)){ chr = ""}
        if (grepl("\\.", chr) == FALSE){
            print(chr)
            circos.text(mean(xlim), 0.15, chr, cex = 1.5,
                        facing = "clockwise",
                        niceFacing = TRUE)
        }
    }, bg.border = NA)
   `
And here is the output:

![image](https://user-images.githubusercontent.com/57679796/82933184-2d550200-9f4f-11ea-9608-f2809754b24d.png)

**Comment by jokergoo** [comment]
Maybe you can change this line

```r
    if (grepl("\\.", chr) == FALSE){
```

to

```r
    if (chr %in% c(1:22, "X", "Y")) {
```

**Comment by askol-lurie** [comment]
My apologies. That code that I posted worked fine. I had been copying and looking at a bmp version instead of the more recent pdf version of the plot. That's embarrassing.

**Comment by jokergoo** [comment]
No problem!
