### ISSUE TITLE
Linear coordinates?

### ISSUE THREAD

**Issue by royfrancis** [jokergoo/circlize#18]
Is it possible to turn off the circular polar coordinates and just plot everything in a straight line? Tracks just  one above the other.

**Comment by jokergoo** [comment]
Hi, only `circos.lines` allows plotting straight lines instead of a circular line. There is a `straight` option in `circos.lines` and you can turn it off.

What do you mean "tracks just one above the other"? Can you give me a more complete example? Maybe there is some other solution for it.

**Comment by royfrancis** [comment]
Sorry for the confusion. This is what I meant to say.
![scheme-01](https://cloud.githubusercontent.com/assets/5083500/15892758/cd87e5de-2d7b-11e6-9ee0-06d5ce27d79e.png)

**Comment by jokergoo** [comment]
circlize package gives circular visualization, which means everything is circular. If you want to plot everything in the normal rectangular coordinate system, I think it is quite easy to use the base graphic system (e.g. `plot()`, ...) or lattice, ggplot2, grid packages. If you want to visualize genomic data in the rectangular coordinate, actually I have another package [gtrellis](https://github.com/jokergoo/gtrellis) which is kind of rectangular version of circlize. It supports multiple tracks.

**Comment by royfrancis** [comment]
`gtrellis` is exactly the sort of tool I was looking for. For shorter regions, the linear layout might be better. Thanks a lot!
