### ISSUE TITLE
Error fetching from github

### ISSUE THREAD

**Issue by Roenbaeck** [jokergoo/circlize#180]
I get the following error when I try to fetch from github: 
```
> library(devtools)
> install_github("jokergoo/circlize")
Error in read.dcf(path) : 
  Found continuation line starting '    colorspace, meth ...' at begin of record.
```

**Comment by jokergoo** [comment]
Can you try it again?

**Comment by Roenbaeck** [comment]
I still got the error, but after upgrading devtools to 2.3.0 I was able to successfully install circlize from the master branch.
