### ISSUE TITLE
Lenght units should be corrected

### ISSUE THREAD

**Issue by JaumePinyol** [jokergoo/circlize#181]
Dear all,

Thank you very much for your impressive work. I've just start using circlize and I noticed that kilobase units are not correctly written in the graph ruler. They appear as "KB" and should be "kb". Please, see https://en.wiktionary.org/wiki/kilobase for proper writing of different base units.

Thank you very much in advance,

Jaume

----------------------------------------------------------
Dr. Jaume Pinyol
Institut de Biotecnologia i Biomedicina
Universitat Autònoma de Barcelona
08193 Bellaterra (Barcelona)
SPAIN
----------------------------------------------------------

**Comment by jokergoo** [comment]
Hi, thank you for this suggestion!

I will use kb, Mb and Gb, which is also used on UCSC genome browser and Ensembl genome browser.

**Comment by JaumePinyol** [comment]
Thank you very much, Zuguang. Congratulations for your work. Circlize is an impressive software!!!

Jaume
