### ISSUE TITLE
No circos.heatmap

### ISSUE THREAD

**Issue by EzicJ** [jokergoo/circlize#182]
Hey man, awesome package.

I'm trying to go through this:

https://jokergoo.github.io/2020/05/21/make-circular-heatmaps/?fbclid=IwAR2dpvZlpc5EK1CU7qwO6Bem8eitltdxZnnSEPHtO99D9bhzC20K1xWbY9s

Installed the latest version of Complexheatmap(2.5.3) and circlize(0.4.10) from the git.
This is what I get when I want to open the function cricos.heatmap:

"Error in fetch(key) : lazy-load database '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/circlize/help/circlize.rdb' is corrupt"

Any idea what to do?

Thanks,

Jasko

**Comment by jokergoo** [comment]
Just restart your R.
