### ISSUE TITLE
Range of the sector ('...') cannot be 0

### ISSUE THREAD

**Issue by Roenbaeck** [jokergoo/circlize#183]
I cannot `circos.initialize()` the following matrix properly to get big and small gaps places where I want them. The groupings I would like are {A}, {B,C}, and {D,E,F,G,H}, but I get the error: 
`>Error: Range of the sector ('F') cannot be 0.` 
```
  A B    C   D  E F    G   H
A 0 0    0   0  0 0 1168   0
B 0 0 2545 278  0 0    0 337
C 0 0    0 817  0 0    0   0
D 0 0    0   0 10 0    0   0
E 0 0    0   0  0 0    0   0
F 0 0    0   0  0 0    0   0
G 0 0  561 326  0 0    0 281
H 0 0   46   8  0 0    0   0
```

Note that this is code that will be run daily in production, and I cannot guarantee that movements always will occur between all categories. In the example above, no movements occur from or to the category F, resulting in it being omitted from the output. Using `gaps.after` I hard-coded the desired result, but this is not a feasible solution since I do not know which categories will be drawn or not. I would also prefer that a solution is not dependent on the ordering of the columns and rows in the matrix. 

Also see the cross-posted question on StackOverflow:
[https://stackoverflow.com/questions/62100993/big-and-small-gaps-using-circlize-in-r](https://stackoverflow.com/questions/62100993/big-and-small-gaps-using-circlize-in-r)

**Comment by jokergoo** [comment]
You can set `circos.par("cell.padding" = c(0.02, 0, 0.02, 0))` before `circos.initialize()` so that there will no expanding on the left and right of each cell.

**Comment by jokergoo** [comment]
Maybe my previous reply cannot answer your question. Can you also attach the code and test data that produce the error?

**Comment by jokergoo** [comment]
Ah, I see, you can do as follows:

1. set `gap.after` as a named vector

```r
gap.after = c("A" = 10, "B" = 2, "C" = 10, "D" = 2, "E" = 2, "F" = 2, "G" = 2, "H" = 10)
```

2. remove the empty row/column from the matrix (`mat` is the one you provided in the post):

```r
empty_row = rowSums(mat) == 0
empty_column = colSums(mat) == 0
mat2 = mat[!empty_row, !empty_column, drop = FALSE] # this removed "F"
```

3. adjust `gap.after` according to `mat2`

```r
grid_order = names(gap.after)
gap.after2 = gap.after[intersect(grid_order, unlist(dimnames(mat2)))]
grid_order2 = names(gap.after2)
```

4. make the chord diagram:

```r
circos.par(gap.after = gap.after2)
chordDiagram(mat2, order = grid_order2)
circos.clear()
```

![image](https://user-images.githubusercontent.com/449218/83357031-1c026000-a36a-11ea-8fc4-bf95c13ba62d.png)

**Comment by jokergoo** [comment]
OK, now if you update the package, the ordering and subsetting of `gap.degree`/`gap.after` are automatic. E.g. for your case:

```r
mat = read.table(textConnection("
  A B    C   D  E F    G   H
A 0 0    0   0  0 0 1168   0
B 0 0 2545 278  0 0    0 337
C 0 0    0 817  0 0    0   0
D 0 0    0   0 10 0    0   0
E 0 0    0   0  0 0    0   0
F 0 0    0   0  0 0    0   0
G 0 0  561 326  0 0    0 281
H 0 0   46   8  0 0    0   0"))
mat = as.matrix(mat)

gap.after = c("A" = 10, "B" = 2, "C" = 10, "D" = 2, "E" = 2, "F" = 2, "G" = 2, "H" = 10)

circos.par(gap.after = gap.after)
chordDiagram(mat, order = LETTERS[1:8])
circos.clear()
```

![image](https://user-images.githubusercontent.com/449218/83358342-2412cd80-a373-11ea-935a-fefe6c504249.png)

**Comment by Roenbaeck** [comment]
Thank you, this makes it easier, but still possibly requires human intervention. Assume that I need the following:
```
gap.after = c("A" = 10, "B" = 2, "C" = 2, "D" = 2, "E" = 2, "F" = 10, "G" = 2, "H" = 10)
```
The desired groupings are {A}, {B,C,D,E,F}, and {G,H}, but since F is empty, its gap is "forgotten". Is `big.gap` and `small.gap` not intended for this scenario, instead of using `gap.after`?

**Comment by jokergoo** [comment]
No, `big.gap` and `small.gap` are basically very similar to `gap.after`. They won't directly modify `gap.after`, but in your case, E should be modified to 10 when F is empty.

I think currently, you need to programmatically construct `gap.after`. 

Assume your grouping are {A}, {B,C,D,E,F}, and {G,H},

```r
group_lt = list(
    group1 = c("A" = 10), 
    group2 = c("B" = 2, "C" = 2, "D" = 2, "E" = 2, "F" = 10), 
    group3 = c("G" = 2, "H" = 10)
)
```

Then you can check which group is lost. Assume the non-empty groups are in `non_empty`,
you can set the last element to 10 in each group after overlapping

```r
group_lt = lapply(group_lt, function(x) {
    x = x[intersect(names(x), non_empty)]
    if(length(x)) x[length(x)] = 10  # you need to check whether x is empty here
})
```

and the adjusted `gap.after` is:

```r
gap.after = unlist(group_lt)
```

**Comment by Roenbaeck** [comment]
I ended up with the following, which works. 
```
big_gap = 10
small_gap = 2
sector_grouping = cbind.data.frame(
  "Sec" = c("A","B","C","D","E","F","G","H"), 
  "Grp" = c("x","y","y","y","y","y","z","z")
)
empty_row = rowSums(mat) == 0
empty_column = colSums(mat) == 0
sector_grouping = sector_grouping[!(empty_row & empty_column),]
for(i in 1:nrow(sector_grouping)) {
  sector_grouping[i,"Gap"] = ifelse(
    sector_grouping[i,2]==sector_grouping[i+1,2],
    small_gap,
    big_gap
  )
}
sector_grouping$Gap[is.na(sector_grouping$Gap)] = big_gap
gap.after = sector_grouping[,3]
names(gap.after) = sector_grouping[,1]
```
Thank you for all the help and your commits that make it possible to use a named vector!

**Comment by jokergoo** [comment]
Hi, I recently updated the package. Now you can group sectors by setting the `group` argument. For following grouping:

```r
group_lt = list(
    group1 = c("A" = 10), 
    group2 = c("B" = 2, "C" = 2, "D" = 2, "E" = 2, "F" = 10), 
    group3 = c("G" = 2, "H" = 10)
)
```

you first construct a grouping variable which is a named vector:

```r
group = c("A" = "group1",
          "B" = "group2",
          "C" = "group2",
          "D" = "group2",
          "E" = "group2",
          "F" = "group2",
          "G" = "group3",
          "H" = "group3"
)
```

and you set `group` argument:

```r
chordDiagram(..., group = group)
```

The gap is automatically set between groups.

The gap between groups and between sectors are set by `big.gap` and `small.gap`.

**Comment by Roenbaeck** [comment]
Thank you very much, this is precisely the functionality I needed!

**Comment by Roenbaeck** [comment]
Does this affect the ”order” parametrar of chordDiagram?

**Comment by jokergoo** [comment]
Yes, it will. You can check https://jokergoo.github.io/2020/06/08/multiple-group-chord-diagram/.

**Comment by Roenbaeck** [comment]
Thanks, setting factor levels works.

However, I still need to do some prep that would be easier if it was taken care of by circlize. In the following example, for G the rowsum = colsum = 0. Because of this, the gap between group 'x' and group 'y' disappears. Would it be possible to detect and adjust for this fact in circlize?
```R
library(devtools)
install_github("jokergoo/circlize")
library(circlize) # chord diagrams

mat = read.table(textConnection("
  A      B    C    D   E   F G   H
A 0      0 1096  544 218 242 0 621
B 0 122373 2975 1421 150 100 0 408
C 0      0    0    0   0   0 0   0
D 0      0    0    0   0   0 0   0
E 0      0    0    0   0   0 0   0
F 0      0    0    0   0   0 0   0
G 0      0    0    0   0   0 0   0
H 0      0    0    0   0   0 0   0"), row.names = 1, col.names = 1)
mat = as.matrix(mat)
diag(mat) = 0

# define groups that should have big.gaps between them
grouping = c(
    "A" = "x",
    "B" = "x",
    "G" = "x",
    "C" = "y",
    "D" = "y",
    "E" = "y",
    "H" = "z",
    "F" = "z"
)
# The order in 'levels' determine the order of the groups in the diagram
grouping <- factor(grouping, levels = c("x", "y", "z"))

# Time to draw the circos
circos.clear()
chordDiagram(mat, group = grouping)
circos.clear()
```

**Comment by jokergoo** [comment]
Thanks! It is fixed.

![image](https://user-images.githubusercontent.com/449218/84591592-1a439c80-ae40-11ea-9cb4-312aaf5f0e63.png)

**Comment by Roenbaeck** [comment]
Thanks! Now it's working precisely as I would like it to :)

**Comment by jokergoo** [comment]
I can put 0.4.10 to CRAN these days. There have already been many improvements for this version.

**Comment by jokergoo** [comment]
Submitted. https://cran.r-project.org/web/packages/circlize/index.html

**Comment by Roenbaeck** [comment]
Thank you for all the help! This is what the end result looks like and what we will be studying for months to come (ignore the pink pen strokes). 
<img width="726" alt="Circos 1" src="https://user-images.githubusercontent.com/8087031/85110944-ebe50900-b213-11ea-86a5-ee5d2d05d5e2.png">
