### ISSUE TITLE
Links on the zoomed chromosome

### ISSUE THREAD

**Issue by sav0016** [jokergoo/circlize#188]
Hey! Really awesome package!

I need your help, please is possible to create links on the zoomed chromosome? I want to visualize some intrachromosomal translocations and I can´t figure out how to do it. Without zooming it´s working.

https://jokergoo.github.io/circlize_book/book/initialize-genomic-plot.html#zooming-chromosomes

These points are working well (points on chromosome 4 are also on the zoomed chromosome 4) but links are not working.

Thanks,

Jakub

**Comment by sav0016** [comment]
I need to visualize these links on chr 4 to the zoomed chr4...

![Zoom_Chr4](https://user-images.githubusercontent.com/48792876/83873151-86811a80-a733-11ea-8963-703271b19d01.png)

**Comment by jokergoo** [comment]
For the regions you draw links on chr4, just use the same regions but use the "extended chromosome names". Assume a link is drawn between following two regions:

```r
df1 = data.frame(
	chr = "chr4",
	start = 10000000,
	end = 10000000
)

df2 = data.frame(
	chr = "chr4",
	start = 50000000,
	end = 50000000
)
circos.genomicLink(df1, df2, ...)
```

To draw the same link on the zoomed chromosome, just replace "chr4" to the "zoomed chromosome" which is "zoomed_chr4":

```r
df3 = data.frame(
	chr = "zoomed_chr4",
	start = 10000000,
	end = 10000000
)

df4 = data.frame(
	chr = "zoomed_chr4",
	start = 50000000,
	end = 50000000
)
circos.genomicLink(df3, df4, ...)
```

**Comment by sav0016** [comment]
Perfect, thank you!
