### ISSUE TITLE
Is it possible to colour the tip of a chord based on its destination?

### ISSUE THREAD

**Issue by Lamm-a** [jokergoo/circlize#189]
Is it possible to colour the tip of a chord based on its origin such that you can see which column the chord is going to? This maight make larger chors diagrams more digestable.

**Comment by jokergoo** [comment]
Is it something like

![image](https://user-images.githubusercontent.com/449218/83850842-c9ca9180-a711-11ea-883b-ff93ad9c5aea.png)

**Comment by Lamm-a** [comment]
Yes exaxtly like that :)

**Comment by jokergoo** [comment]
Can you first check https://jokergoo.github.io/circlize_book/book/a-complex-example-of-chord-diagram.html?

If you still have problems, I can help you.

**Comment by jokergoo** [comment]
I have updated the package. Now for directional Chord diagram, by default, there are bars showing the proportion of target sectors for every source sector:

You don't need to do anything extra, just update the package to version 0.4.11.

![image](https://user-images.githubusercontent.com/449218/85444715-eaf50400-b592-11ea-8f24-8767c00dba20.png)

**Comment by Lamm-a** [comment]
Woo thank you for doing this :) So `directional = TRUE` will now produce the above?

**Comment by jokergoo** [comment]
Currently no.

**Comment by maikeheidemeyer** [comment]
Helo!
I am trying to achieve just the above mentioned, and just tried the code with an example from another issue (https://github.com/jokergoo/circlize/issues/81):

set.seed(999)
mat = matrix(sample(18, 18), 3, 6) 
rownames(mat) = paste0("S", 1:3)
colnames(mat) = paste0("E", 1:6)
par(mfrow = c(1, 2))
circos.par(gap.after = c(1, 1, 10, 1, 1, 1, 1, 1, 10))
chordDiagram(mat, grid.col = grid.col)
title("Default")
chordDiagram(mat, directional = TRUE, scale = TRUE)
title("scale = TRUE")

However, setting directional = TRUE doesn't do anything, but leaves a blank track.

Did I miss anything?

**Comment by maikeheidemeyer** [comment]
Also, the data at http://jokergoo.github.io/data/chromatin_transition.RData seems to be unavailable!

**Comment by jokergoo** [comment]
Sorry, the link should be https://jokergoo.github.io/circlize_book/data/chromatin_transition.RData.
