### ISSUE TITLE
Error: nrow of `region1` and `region2` differ...But they are the same

### ISSUE THREAD

**Issue by RichardShao17** [jokergoo/circlize#193]
Hey!

I'm very new to R and I'm trying to do a circular genomic map with links, linking common genes.
```
df = data.frame(name = c("contig_125", "contig_24", "contig_$24", "contig_255","contig_32", "contig_348","contig_371","contig_458", "contig_464","contig_564","contig_690","contig_788","contig_940","contig_98"),
                start = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0),
                end = c(10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000),
                stringsAsFactors = FALSE)
circos.genomicInitialize(df)
circos.genomicLink(MASTER, MASTER1)
```

Attached is my code but the error says my two databases (MASTER, MASTER1) have different dimensions, which is untrue. Can I send you my database files?

Thanks

**Comment by RichardShao17** [comment]
[MASTER.txt](https://github.com/jokergoo/circlize/files/4754401/MASTER.txt)
[MASTER1.txt](https://github.com/jokergoo/circlize/files/4754402/MASTER1.txt)

**Comment by jokergoo** [comment]
There are chromosomes/contigs in `MASTER` and `MASTER1` that are not in `df`:

```
> sum(MASTER[, 1] %in% df$name)
[1] 8775
> sum(MASTER1[, 1] %in% df$name)
[1] 9130
```
