### ISSUE TITLE
Phylogenetic trees of real data

### ISSUE THREAD

**Issue by xiebb123456** [jokergoo/circlize#195]
Hi,

very good tools, I have some problems on '5.3 Phylogenetic trees' (https://jokergoo.github.io/circlize_book/book/high-level-plots.html#phylogenetic-trees), the demo didn't contain the chromosome track, just the text of each bird, here I want to set the leaves of the dendrogram drawn at center of each sector, then this tree will be more meaningful, how do I achieve that?

circos.par("track.height" = 0.1)
circos.initialize(factors = df$factors, x = df$x)
circos.track(factors = df$factors, y = df$y)
circos.track(ylim = c(0, dend_height), bg.border = NA,
             track.height = 0.4, panel.fun = function(x, y) {
               circos.dendrogram(dend)
             })

the code works fine, but it will draw repeat dendrogram at x of each sector.

Thanks,

**Comment by jokergoo** [comment]
Hi, that is just a demonstration of drawing simple phylogenetic trees. For advanced use, I suggest you refer to the ggtree package.
