### ISSUE TITLE
How to swap link colour to be that of matrix columns and not rows?

### ISSUE THREAD

**Issue by SSE-Group** [jokergoo/circlize#196]
The documentation states 

> By default, link colors are same as the color for the corresponding sectors in the first group.

Is there any way to reverse this?

**Comment by jokergoo** [comment]
No, but you can set the color as a matrix.

**Comment by jokergoo** [comment]
Ha, you can simply transpose your matrix. See https://jokergoo.github.io/circlize_book/book/the-chorddiagram-function.html#set-grid-colors

**Comment by SSE-Group** [comment]
Would this achieve the same result?

**Comment by SSE-Group** [comment]
Oh yes good point!! very simple solution!

**Comment by jokergoo** [comment]
And by the way, you can rotate the circle 180 degrees by setting `circos.par("start.degree" = 180)`.
