### ISSUE TITLE
Legend and  tracks are plotted outside the plotting area. 

### ISSUE THREAD

**Issue by giovanegt** [jokergoo/circlize#199]
Hi all, 
I am trying to plot a chord diagram with cells from 2 groups (ctrl and yn1), going into different clusters (sectors of the chord diagram. However, I am having three problems:
1- the name of the clusters are cut and outside the plotting area
2- Some times even the chord diagram itself is cut,  with part of it outside the plotting area. 
3- some of the legend are going inside the chord diagram plot. 

here is the code I used. 

`library(circlize)`

`chordDiagram(df,  annotationTrack = "grid", directional = -1,
  direction.type = c("arrows", "diffHeight"), 
  diffHeight  = -0.04,
  annotationTrackHeight = c(0.05, 0.1),
  link.arr.type = "big.arrow",
  preAllocateTracks = list(list(track.height = 0.05),
                           list(track.height = 0.05)))
circos.trackPlotRegion(track.index = 1, panel.fun = function(x, y) {
  xlim = get.cell.meta.data("xlim")
  ylim = get.cell.meta.data("ylim")
  sector.index = get.cell.meta.data("sector.index")
  circos.text(mean(xlim), mean(ylim), sector.index, facing = "reverse.clockwise", niceFacing = TRUE)
}, bg.border = NA)
circos.trackPlotRegion(track.index = 2, panel.fun = function(x, y)`

`circos.clear()`

and here is the plot:
![image](https://user-images.githubusercontent.com/58445209/85961341-64b03780-b96f-11ea-9911-68f43aa3f0d1.png)

Can someone help with these issues? 
I am a new user of the package and any help is appreciated.
I wonder if this is a problem with ylim and xlim, but I also think it needs to be prompted to the metadata to get the right legends. 
Once again, any help is appreciated.

**Comment by jokergoo** [comment]
Before making your plot, set `canvas.xlim` and `canvas.ylim` in `circos.par()`:

```r
circos.par(canvas.xlim = c(-1.5, 1.5), canvas.ylim = c(-1.5, 1.5))
```

In the future, I will change the name of `canvas.xlim` and `canvas.ylim` to something more easy to understand.

https://jokergoo.github.io/circlize_book/book/circular-layout.html#graphic-parameters

**Comment by jokergoo** [comment]
I just added the `circle.margin` option in `circos.par()`. Now you just simply do:

```r
circos.par(circle.margin = 0.5)  # margin is 0.5 of the radius of the circle, on the four sides.
# and this is identical to circos.par(canvas.xlim = c(-1.5, 1.5), canvas.ylim = c(-1.5, 1.5))
you plot here...
```

You can update the package from GitHub.

**Comment by giovanegt** [comment]
I thank you very much!
