### ISSUE TITLE
Font family

### ISSUE THREAD

**Issue by asgarhussain** [jokergoo/circlize#201]
Is there any way to use font family while using circlize?

**Comment by jokergoo** [comment]
You can set it by `circos.text()`

```r
circos.initialize(fa = letters[1:8], xlim = c(0, 1))
circos.track(ylim = c(0, 1), panel.fun = function(x, y) {
	circos.text(CELL_META$xcenter, CELL_META$ycenter, "aaaaaa", family = "Times")
})
```
![image](https://user-images.githubusercontent.com/449218/86049296-3192a480-ba52-11ea-8fdf-ed1a41958108.png)

**Comment by asgarhussain** [comment]
Thanks, for quick response.

**Comment by asgarhussain** [comment]
What if I want to use font family for labels.

**Comment by jokergoo** [comment]
What label? If you want to set the font family, you always need to do it manually by `circos.text()`.

**Comment by asgarhussain** [comment]
I want to do it for Genomiclabels.

**Comment by jokergoo** [comment]
Em, this is difficult. I tried to implement it but found the `family` parameter cannot be vectorized, which I mean, in following:

```r
text(x, y, family)
```

The value of `family` can only be a scalar, while not a vector with length > 1, this makes it difficult to work with circlize.

I would say you can only post-edit by some other software e.g. inkscape.
