### ISSUE TITLE
legend color does not match sectors colors in chord diagram. 

### ISSUE THREAD

**Issue by giovanegt** [jokergoo/circlize#202]
First off, 
This is a great too!
 I am in love with it and I am trying to 
use circlize to plot scRNA seq data. 
I problem I am facing is: I cannot match the legend color bar with the sectors colors.
Below is the chord diagram I plot from an specific data fame. Please notice that the sectors colors are different of the legend key color for each respective sector.

![image](https://user-images.githubusercontent.com/58445209/86254539-8f6edb80-bb7b-11ea-99fb-7ffd6501dd6d.png)

 The legend should refer to the colors of the sectors at the bottom half of the chord diagram. but, as seem here it does not.
I have been trying to play around with the `ComplexHeatmap` legend tutorial, but no doghnut for me there.  
it would be greatly appreciated if someone  could help me out with this issue.

here is the code I used for the chord diagram

```r
#plotting Chord diagram
library(circlize)
library(ComplexHeatmap)
```

```r
chordDiagram(dfctrlGO, directional = -1,
  direction.type = c("arrows", "diffHeight"), 
  diffHeight  = -0.04,
  annotationTrack = "grid", 
  annotationTrackHeight = c(0.05, 0.1),
  link.arr.type = "big.arrow", 
  link.sort = TRUE, 
  link.largest.ontop = TRUE,
  transparency = 0.2)
```
 
here is the code for the legend key

```r
#199 attributing labels names 
lgd = Legend(labels = c("metanephric nephron development (GO:0072210)",
"metanephric nephron morphogenesis (GO:0072273)",
"metanephros morphogenesis (GO:0003338)",
"regulation of metanephros development (GO:0072215)",
"cell differentiation involved in kidney development (GO:0061005)",
"regulation of mesonephros development (GO:0061217)",
"metanephros development (GO:0001656)",
"regulation of branching morphogenesis in UB (GO:0090189)",
"positive regulation of kidney development (GO:0090184)",
"mesonephric tubule development (GO:0072164)",
"mesonephric epithelium development (GO:0072163)",
"nephron tubule development (GO:0072080)",
"ureteric bud development (GO:0001657)",
"mesonephros development (GO:0001823)",
"renal tubule development (GO:0061326)",
"renal tubule morphogenesis (GO:0061333)",
"kidney epithelium development (GO:0072073)",
"regulation of kidney development (GO:0090183)",
"positive regulation of collagen biosynthetic process (GO:0032967)",
"nephron epithelium development (GO:0072009)",
"nephron tubule morphogenesis (GO:0072078)",
"nephron epithelium morphogenesis (GO:0072088)",
"nephron morphogenesis (GO:0072028)",
"mesonephric tubule morphogenesis (GO:0072171)",
"positive regulation of epithelial to mesenchymal transition (GO:0010718)",
"positive regulation of collagen metabolic process (GO:0010714)",
"ureteric bud morphogenesis (GO:0060675)",
"branching involved in ureteric bud morphogenesis (GO:0001658)",
"glomerulus development (GO:0032835)",
"negative regulation of animal organ morphogenesis (GO:0110111)",
"outflow tract morphogenesis (GO:0003151)",
"kidney morphogenesis (GO:0060993)",
"nephron development (GO:0072006)",
"positive regulation of organ morphogenesis (GO:0110110)",
"regulation of collagen biosynthetic process (GO:0032965)"),  legend_gp = gpar(row = 1:35, fill =1:35)
```

```r
draw(lgd, x = unit(8, "cm"), y = unit(10, "cm"), just = c("center"))
```

Sorry for the big code, but I am trying to provide as much info as possible.
Thanks in advance for your time and help.

**Comment by jokergoo** [comment]
I am sorry for the late reply.  For your problem, I think you forgot to set colors in `chordDiagram()` so all the colors are actually randomly generated.

**Comment by giovanegt** [comment]
You are probably right. I think I have just assumed the chord diagram would match the first sector color with the first name in the legend. 
I will try to set the color in the chord diagram before call it.

Once again, I thank you very much for your time and for this great tool.
