### ISSUE TITLE
Error in rep(small.gap, n_df1 - 1) : invalid 'times' argument with chord diagram

### ISSUE THREAD

**Issue by lixiaopi1985** [jokergoo/circlize#203]
Hi,

I encountered this error `Error in rep(small.gap, n_df1 - 1) : invalid 'times' argument` with one of my dataset (call it d2). I have compared it to another dataset (d1) which is working fine. d1 and d2 were produced by the same function but with different different groups. I could not debug where went wrong but they look like pretty much the same structurally. I extracted the group I had parsed to the chorddiagram function and ran it as lapply(tg, function(x)c(rep(1, x-1), 2)), no errors shown.

the function and arguments I used:

chordDiagram(df, annotationTrack = "grid", grid.col = sector_colors, col = linkcolors, preAllocateTracks = list(track.height = uh(5, "mm"), track.margin = c(uh(2, "mm"), 0)), group = group, scale = T, big.gap = 2)

my files:

[notworking](https://drive.google.com/file/d/1bKd-zpqYAg8qsV3PaF_2WmUoPnWwQd6N/view?usp=sharing)

[working](https://drive.google.com/file/d/1sqxaMymplnyYhvGVFNXMrCrY-vOizIW0/view?usp=sharing)

those are rds in a list format with df, sector colors, link colors and groups stored.

Thank you!

**Comment by lixiaopi1985** [comment]
It seems coming from `scale` parameter. Turning it off I was able to plot it.

**Comment by jokergoo** [comment]
According to the message:

```r
Error in rep(small.gap, n_df1 - 1) : invalid 'times' argument
In addition: Warning messages:
1: In max(ind1) : no non-missing arguments to max; returning -Inf
2: In min(ind2) : no non-missing arguments to min; returning Inf
```

I guess some group has identical values, so after scaling, all values become `Inf` and they are removed, which causes the incorrect length of `small.gap`.

**Comment by jokergoo** [comment]
There are some groups where there is only one value associated, so, they cannot be scaled.

In future version, I will print a more informative message once the scaling can not be performed.
```
> sort(table(c(as.character(df[, 1]), as.character(df[, 2]))))

  Chytridiomycota_t6  Gemmatimonadetes_t6   Latescibacteria_t0 
                   1                    1                    1 
Mortierellomycota_t0      Mucoromycota_t0       Nitrospirae_t3 
                   1                    1                    1 
              WS2_t3        Firmicutes_t6  Gemmatimonadetes_t1 
                   1                    2                    2 
  Latescibacteria_t1 Mortierellomycota_t1     Bacteroidetes_t6 
                   2                    2                    3 
    Basidiomycota_t0       Chloroflexi_t6        Firmicutes_t0 
                   3                    3                    3 
 Gemmatimonadetes_t0 Mortierellomycota_t6    Actinobacteria_t6 
                   3                    3                    4 
    Bacteroidetes_t1     Basidiomycota_t1     Basidiomycota_t3 
                   4                    4                    4 
    Basidiomycota_t6       Chloroflexi_t0  Gemmatimonadetes_t3 
                   4                    4                    4 
  Patescibacteria_t1        Firmicutes_t1       Nitrospirae_t0 
                   4                    5                    5 
    Acidobacteria_t6        Firmicutes_t3   Verrucomicrobia_t0 
                   6                    6                    7 
       Ascomycota_t6    Actinobacteria_t3     Bacteroidetes_t0 
                   8                   10                   10 
      Chloroflexi_t3     Bacteroidetes_t3       Chloroflexi_t1 
                  11                   13                   13 
       Ascomycota_t3    Actinobacteria_t0     Acidobacteria_t1 
                  14                   16                   21 
       Ascomycota_t0    Actinobacteria_t1    Proteobacteria_t6 
                  22                   24                   24 
    Acidobacteria_t0        Ascomycota_t1     Acidobacteria_t3 
                  25                   30                   34 
   Proteobacteria_t1    Proteobacteria_t0    Proteobacteria_t3 
                  44                   48                   71 
```

**Comment by lixiaopi1985** [comment]
I also checked the one that worked, there were groups with single value but it did not stop the function scaling it. In addition, I removed the entries (from column and to column ) associated with just one value from the df you showed me above, did not work this way, same error message. So I am sorta skeptical about the explanation. 

```
singlets1 = names(table(df[, 1])[table(df[,1]) == 1])
singlets2 = names(table(df[, 2])[table(df[,2]) == 1])


df2 = df %>% filter( (! from %in% singlets1) & (! to %in% singlets2) ) %>%
        droplevels()
```

**Comment by jokergoo** [comment]
Oh, sorry, I made a mistake here. The scaling is applied as `x/sum(x)`, so it won't be affected if there is only one value in the group. I will try to find other reasons.

**Comment by jokergoo** [comment]
Actually, there are two bugs I found :). The scaling should be applied as `x/(sum(abs(x1)) + sum(abs(x2)))`, where `x1` is the total amount of a group in "the first column (the sources)" and `x2` is the total amount of the group in "the second column (the targets)", and `x1` and `x2` should take the absolute values.

Now it is fixed on GitHub.

```r
 chordDiagram(df, annotationTrack = "grid", grid.col = sector_colors, col = linkcolors, scale = T)
```

![image](https://user-images.githubusercontent.com/449218/90308330-04556500-dedf-11ea-84f9-b34e7c17b668.png)

**Comment by lixiaopi1985** [comment]
Sweet! It is working now. Thank you!
