### ISSUE TITLE
circos.genomicLabels() "outside" lines do not reach labels

### ISSUE THREAD

**Issue by nijibabulu** [jokergoo/circlize#206]
When initializing crowded `circos.genomicLabels()`, with the following data set

```
genome <- data.frame(chr=c("chr1", "chr2"), start=1, end=1e8)
bed <- data.frame(chr="chr1", start=seq(5), end=seq(2,6), name="aaaaa")
```

The standard method of adding genomic labels to the inside functions as expected:

```
circos.genomicInitialize(genome, plotType = "axis")
circos.genomicLabels(bed, labels.column = 4, side = "inside")
``` 
[inside_labels.pdf](https://github.com/jokergoo/circlize/files/4992426/inside_labels.pdf)

However when attempting to flip these to the outside, the labels no longer line up:

```
circos.genomicInitialize(genome, plotType = NULL)
circos.genomicLabels(bed, labels.column = 4, side = "outside")
circos.track(track.index = get.current.track.index(), panel.fun = function(x, y) {
  circos.genomicAxis(h = "bottom", direction = "inside")
}, bg.border=NA)
```
[outside_labels.pdf](https://github.com/jokergoo/circlize/files/4992424/outside_labels.pdf)

This is not the case when the label is only one letter long.

**Comment by jokergoo** [comment]
Thanks! This is something I haven't tested. 

Now it is fixed!

```r
par(mfrow = c(1, 2))
circos.genomicInitialize(genome, plotType = NULL)
circos.track(ylim = c(0, 1))
circos.genomicLabels(bed, labels.column = 4, side = "outside")
circos.track(ylim = c(0, 1))


circos.genomicInitialize(genome, plotType = NULL)
circos.track(ylim = c(0, 1))
circos.genomicLabels(bed, labels.column = 4, side = "inside")
circos.track(ylim = c(0, 1))
```

![image](https://user-images.githubusercontent.com/449218/90156819-38b90c00-dd8d-11ea-975b-09dcbe0cc72b.png)

**Comment by nijibabulu** [comment]
Thanks! This seems to have fixed the problems I was having with my plot.
