### ISSUE TITLE
Express axis labels in MB

### ISSUE THREAD

**Issue by elcortegano** [jokergoo/circlize#208]
When a genome is initialized with `major.by > 1000000`, the axis labels are expressed in MB. However, when `major.by = 1000000`, they are still in Kb units. E.g.: see the reproducible example below:

```
library("circlize")
library("tidyverse")
circos.par(start.degree = 90, track.height = 0.10)

# Initialize genome (bed file with genome sizes)
genome <- tibble(chr=c("chr1","chr2"), start = c(1,1), end = c(6000000, 6000000))
circos.genomicInitialize(genome, plotType = c("axis"), major.by = 1000000, axis.labels.cex = 0.75); circos.clear()
```
I think visualization would be much better if these labels would be in MB as soon as major.by gets equal to 1e6 (or even 1e5). Would it be possible to change this behavior, or allow the user to set the units?

**Comment by jokergoo** [comment]
Ha, that should be a bug.

Anyway, you can always self-set the axes breaks and labels by `circos.axis()` or `circos.genomicAxis()`.

**Comment by jokergoo** [comment]
Now it is fixed.

![image](https://user-images.githubusercontent.com/449218/90128409-1f9d6480-dd67-11ea-973b-18dfed626723.png)
