### ISSUE TITLE
Strange bending lines with circos.genomicTrackPlotRegion

### ISSUE THREAD

**Issue by yftang** [jokergoo/circlize#21]
Hi, this is the second question I have posted on this repo.

Yesterday, I tried draw a circos-like figure with this amazing tool, but something strange showed up, and a little help is needed. Part of the figure is as following.
![image](https://cloud.githubusercontent.com/assets/1327096/17612118/b061c032-6080-11e6-929b-d93f9db20fa2.png)

Do you see some bending lines in Chr17, 18, and other chromosomes?

- Species: Zebrafish

- CytoBand: [UCSC FTP](http://hgdownload.soe.ucsc.edu/goldenPath/danRer10/database/cytoBandIdeo.txt.gz)

- Commands used to draw figure:

```R
data <- read.table('/home/sam/*.bed', head=T)
circos.genomicTrackPlotRegion(data, panel.fun=function(region, value, ...) {
    i = getI(...)
    circos.genomicLines(region, value, type='l', col="green")
}, bg.border=NA, track.height=0.1)
```

- BED file format (all values are positive, end pos is always >= start pos): 
```
chr	start	end	value1
chr1	32977	34219	1.611885
chr1	36659	39145	1.428755
chr1	27799	32416	1.425769
chr1	11871	16226	1.232793
chr1	120863	121801	1.610041
chr1	67339	69284	1.269779
chr1	39351	44723	1.423464
```

Thanks in advance.

**Comment by jokergoo** [comment]
Hi, you need to sort your bed files first if you set `type = "l"`:

```{r}
data = data[order(data$chr, data$start), ]
```

**Comment by yftang** [comment]
That works really great, thanks.
