### ISSUE TITLE
Proportion of origins in destination grid?

### ISSUE THREAD

**Issue by maikeheidemeyer** [jokergoo/circlize#211]
Helo, is it possible to show the origin proportion in the destination grid, rather than the other way around? I am using directional = -1, but this turns my arrows around too.
Thank you in advance!

**Comment by jokergoo** [comment]
I think that proportion can already be seen by the width of the arrows (in the target sectors).

![image](https://user-images.githubusercontent.com/449218/90490861-6f9d7200-e13f-11ea-82d3-820c18a9e955.png)

**Comment by jokergoo** [comment]
It is better if you can provide me with some data.
