### ISSUE TITLE
Trees with fewer or more than two branches in a dendrogram component

### ISSUE THREAD

**Issue by nykfank** [jokergoo/circlize#213]
I wanted to plots trees with fewer or more than two branches in a dendrogram component. Because your function circos.dendrogram expects exactly two branches at each sub-dendrogram, I modified it to work with any number. Maybe you can add it to your package, because it worked nicely for me like this. And it should also work the same on all the "normal" trees.

[circos_dendrogram_branches.txt](https://github.com/jokergoo/circlize/files/5215236/circos_dendrogram_branches.txt)

**Comment by jokergoo** [comment]
Thanks! I will have a look and support it in the package.
