### ISSUE TITLE
Directional chordDiagram() does not show direction bars/grid

### ISSUE THREAD

**Issue by Diediehop** [jokergoo/circlize#215]
Hi jokergoo,

I'm quite new to circlize and R in general, and I've been trying to create some bi-directional chord diagrams using your package. I really like the package and all the detailed instructions on https://jokergoo.github.io/circlize_book/book/index.html, so a lot of thanks!

However every time I try to create a directional chordDiagram, the additional bars showing the origin of the direction do not plot, as shown on this example below:

`library(circlize)

mat2 = matrix(sample(100, 35), nrow = 5)
rownames(mat2) = letters[1:5]
colnames(mat2) = letters[1:7]
mat2

chordDiagram(mat2, grid.col = 1:7, directional = 1, row.col = 1:5)`

The above code is identical to the one in your book and gives the following plot:
![mat2](https://user-images.githubusercontent.com/71313740/93183349-2985ff00-f73b-11ea-9f2f-36e45935b3eb.png)

I've added the session info to the documents:
[Session_info_chordDiagram.txt](https://github.com/jokergoo/circlize/files/5223393/Session_info_chordDiagram.txt)

So far i've tried to install an older version of circlize and also I tried it on my MacBook, but no succes. I also reinstalled R on both devices. I hope this issue is an easy fix because I would really like to include these plots into my work. Thanks a lot in advance!

Kind regards,

Diediehop

**Comment by jokergoo** [comment]
Maybe you need to update the package? This is a new feature.

```r
library(devtools)
install_github("jokergoo/circlize")
```

**Comment by Diediehop** [comment]
Thank you for your reply. Installing the newer version of the package through github solved the problem. Tanks a lot!!

**Comment by Diediehop** [comment]
So with the new package it does show the bars for directional = -1 or 1, however when I try to plot a bidirectional plot (i.e. directional =2) the bars again do not show. Here is an example:

`
mat2 = matrix(sample(100, 35), nrow = 5)
rownames(mat2) = letters[1:5]
colnames(mat2) = letters[1:7]

chordDiagram(mat2, grid.col = 1:7, directional = 2, row.col = 1:5)
`

![Rplot](https://user-images.githubusercontent.com/71313740/93216947-a67b9d80-f768-11ea-84b3-e69bccda172a.png)

**Comment by jokergoo** [comment]
I am sorry I missed this issue! Yes, I haven't considered this scenario yet. I will fix it.

**Comment by jokergoo** [comment]
Now it is corrected. Thanks for reporting!

![image](https://user-images.githubusercontent.com/449218/95996602-26158e80-0e33-11eb-89d8-7977c1da16c2.png)
