### ISSUE TITLE
Error: Some of your `numeric.column` are not numeric.

### ISSUE THREAD

**Issue by canfeng-HUA** [jokergoo/circlize#216]
I used the following code. However, I got an error. Could you help me to solve it?
```
circos.par("start.degree" = 90)
Genome.file = system.file(package = "circlize", "extdata", "Genome")
circos.initializeWithIdeogram(Genome)

circos.genomicTrackPlotRegion(Peaks_fc, numeric.column = ("value1"),
                              panel.fun = function(region, value, ...) {
  circos.genomicPoints(region, value, pch = 16, cex = 0.5, ...)
})
```
Error: Some of your `numeric.column` are not numeric.

I confirmed that the value in the value1 column was numeric. 
The following picture shows the Peaks_fc.

![image](https://user-images.githubusercontent.com/71436402/93708800-c39adc80-fb6b-11ea-90b3-76c17238ad75.png)

**Comment by jokergoo** [comment]
Can you paste the output of `str(Peaks_fc)`?

**Comment by canfeng-HUA** [comment]
Thanks a lot for your great help! I solved the problem!
