### ISSUE TITLE
circos.genomicLink function with group color functionality

### ISSUE THREAD

**Issue by leiendeckerlu** [jokergoo/circlize#217]
Hi there,

It would be great if the `circos.genomicLink` function would support color grouping of plotted links. Currently, it seems that only one color for all links or one unique color per link is possible.

Let's say this is bed1, and I want to have all links from Sample-185 in red, Sample-184 in blue etc. pp.
![image](https://user-images.githubusercontent.com/26895805/94343206-e10df180-0016-11eb-96c5-27ceb3b0d5b9.png)

Thanks,
Lukas

P.S. Manually, it would of course be possible to set the color for all n elements in bed1 and thereby assign the same color to the same sample group.

**Comment by jokergoo** [comment]
Hi, I think it can be easily done by constructing a color vector:

```{r}
circos.genomicLink(bed1, bed2, col = switch(bed1[, 4], "Sample-185" = "red", "Sample-184" = "blue", ...))
```
