### ISSUE TITLE
circos.track: cell.padding is not applied tangential

### ISSUE THREAD

**Issue by FelixErnst** [jokergoo/circlize#219]
Hi,

I have tried to remove the cell paddings to add a background color for a label track. However, only the radial paddings are getting applied

``` r
library(circlize)
#> ========================================
#> circlize version 0.4.10
#> CRAN page: https://cran.r-project.org/package=circlize
#> Github page: https://github.com/jokergoo/circlize
#> Documentation: https://jokergoo.github.io/circlize_book/book/
#> 
#> If you use it in published research, please cite:
#> Gu, Z. circlize implements and enhances circular visualization
#>   in R. Bioinformatics 2014.
#> 
#> This message can be suppressed by:
#>   suppressPackageStartupMessages(library(circlize))
#> ========================================
fa = c("d", "f", "e", "c", "g", "b", "a")
f1 = factor(fa)
circos.initialize(factors = f1, xlim = c(0, 1))
circos.track(factors = fa,
             x = fa,
             ylim = c(0,1),
             cell.padding = c(0,0,0,0),
             panel.fun = function(x,y){
               circos.rect(xleft = 0, xright = 1,
                           ybottom = 0, ytop = 1,
                           col = "red")
             })
circos.track(factors = fa,
             x = fa,
             ylim = c(0,1),
             panel.fun = function(x,y){
               circos.rect(xleft = 0, xright = 1,
                           ybottom = 0, ytop = 1,
                           col = "red")
             })
```

![](https://i.imgur.com/ci0gSyg.png)

``` r
circos.clear()
```

<sup>Created on 2020-10-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Any advice on how to set those paddings to zero? Thanks in advance.

Felix

<details><summary>Sessioninfo</summary>
<pre>sessionInfo()
#> R version 4.0.2 (2020-06-22)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19041)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_Germany.1252  LC_CTYPE=English_Germany.1252   
#> [3] LC_MONETARY=English_Germany.1252 LC_NUMERIC=C                    
#> [5] LC_TIME=English_Germany.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] circlize_0.4.10
#> 
#> loaded via a namespace (and not attached):
#>  [1] digest_0.6.25       grid_4.0.2          magrittr_1.5       
#>  [4] evaluate_0.14       highr_0.8           rlang_0.4.7        
#>  [7] stringi_1.5.3       GlobalOptions_0.1.2 rmarkdown_2.4      
#> [10] tools_4.0.2         stringr_1.4.0       xfun_0.17          
#> [13] yaml_2.2.1          compiler_4.0.2      colorspace_1.4-1   
#> [16] shape_1.4.5         htmltools_0.5.0     knitr_1.30</pre></details>

**Comment by jokergoo** [comment]
Hi, the left and right values of `cell.padding` are ignored when it is set in `circos.track()`. If you want to set it globally, you can set it via `circos.par()`:

```r
circos.par(cell.padding = c(0, 0, 0, 0))
circos.initialize(...)
circos.track(...)
```

If you just want to set the background colors, you can do:

```r
circos.initialize(...)
circos.track(..., bg.col = "red")
```

or

```r
circos.initialize(...)
circos.track(..., panel.fun = function(x, y) {
   circos.rect(CELL_META$cell.xlim[1], CELL_META$cell.ylim[1],
               CELL_META$cell.xlim[2], CELL_META$cell.ylim[2],
               col = "red") 
    ....
})
```

**Comment by FelixErnst** [comment]
Thanks for the advice. I thought this was expected behavior, since `circos.par("cell.padding")` retuns 4 values as suggested in `?circos.trackPlotRegion`
