### ISSUE TITLE
Plotting genomicLabels on Zoomed-In chromosome

### ISSUE THREAD

**Issue by moldach** [jokergoo/circlize#231]
Two issues here:

1) `circos.genomicLabels(..., side = "outside")` places the annotation _inside_ the circle:

```
suppressPackageStartupMessages(require(circlize))
ann <- data.frame(chr = "III",
                  exon_start = 8193843,
                  exon_end = 8201217,
                  value = 1,
                  name = "eT1")

df = data.frame(
	chr = c("I", "II", "III", "IV", "V", "X", "zoom_III", "zoom_V"),
	start = c(0, 0, 0, 0, 0, 0, 8200512, 8930425),
	end = c(15072434, 15279421, 13783801, 17493829, 20924180, 17718942, 8201012, 8930925)
)

# normalize in normal chromsomes and zoomed chromosomes separately
sector.width = c(df$end[1:6] / sum(df$end[1:6]) * 0.2, 
                 df$end[7:8] / sum(df$end[7:8]))

circos.par(start.degree = 90, gap.after = c(1, 1, 1, 1, 1, 5, 1, 5))
circos.genomicInitialize(df, sector.width = sector.width)
circos.track(ylim = c(0, 2), 
    bg.col = c("#ACCCDD", # pale yellow
               "#5896AD", # olive yellow 
               "#005C91", 
               "#003C69", 
               "#00254A", 
               "#96AAB5",
               "#005C91",
               "#00254A"), 
    bg.border = NA, track.height = 0.05)

##  Add genomic labels
circos.genomicLabels(ann,labels.column = 5, side = "outside", niceFacing = TRUE)

circos.clear()
```

![et1](https://user-images.githubusercontent.com/5749465/98170753-c77c8700-1eab-11eb-9e78-b320b2de381f.png)

2) I cannot figure out how to use `genomicLabels()` on the **zoomed-in** section of the plot

```

ann <- data.frame(chr = "zoom_III",
                  exon_start = 8193843,
                  exon_end = 8201217,
                  value = 1,
                  name = "eT1")

circos.genomicInitialize(df, sector.width = sector.width)
circos.track(ylim = c(0, 2), 
    bg.col = c("#ACCCDD", # pale yellow
               "#5896AD", # olive yellow 
               "#005C91", 
               "#003C69", 
               "#00254A", 
               "#96AAB5",
               "#005C91",
               "#00254A"), 
    bg.border = NA, track.height = 0.05)

##  Add genomic labels
circos.genomicLabels(ann,labels.column = 5, side = "outside", niceFacing = TRUE)

circos.clear()
```

![loop](https://user-images.githubusercontent.com/5749465/98172277-4f639080-1eae-11eb-8f9f-dbe35c9550aa.png)

**Comment by zhangguangxin1234** [comment]
unsubscribe
















At 2020-11-05 05:59:42, "Matthew J. Oldach" <notifications@github.com> wrote:

Two issues here:

`circos.genomicLabels(side = "outside") doesn't seem to be working.

The following places the annotation inside the circle:

suppressPackageStartupMessages(require(circlize))
ann <- data.frame(chr = "III",
                  exon_start = 8193843,
                  exon_end = 8201217,
                  value = 1,
                  name = "eT1")

df = data.frame(
	chr = c("I", "II", "III", "IV", "V", "X", "zoom_III", "zoom_V"),
	start = c(0, 0, 0, 0, 0, 0, 8200512, 8930425),
	end = c(15072434, 15279421, 13783801, 17493829, 20924180, 17718942, 8201012, 8930925)
)

# normalize in normal chromsomes and zoomed chromosomes separately
sector.width = c(df$end[1:6] / sum(df$end[1:6]) * 0.2, 
                 df$end[7:8] / sum(df$end[7:8]))

circos.par(start.degree = 90, gap.after = c(1, 1, 1, 1, 1, 5, 1, 5))
circos.genomicInitialize(df, sector.width = sector.width)
circos.track(ylim = c(0, 2), 
    bg.col = c("#ACCCDD", # pale yellow
               "#5896AD", # olive yellow 
               "#005C91", 
               "#003C69", 
               "#00254A", 
               "#96AAB5",
               "#005C91",
               "#00254A"), 
    bg.border = NA, track.height = 0.05)

##  Add genomic labels
circos.genomicLabels(ann,labels.column = 5, side = "outside", niceFacing = TRUE)

circos.clear()


I cannot figure out how to use genomicLabels() on the zoomed-in section of the plot

ann <- data.frame(chr = "zoom_III",
                  exon_start = 8193843,
                  exon_end = 8201217,
                  value = 1,
                  name = "eT1")

circos.genomicInitialize(df, sector.width = sector.width)
circos.track(ylim = c(0, 2), 
    bg.col = c("#ACCCDD", # pale yellow
               "#5896AD", # olive yellow 
               "#005C91", 
               "#003C69", 
               "#00254A", 
               "#96AAB5",
               "#005C91",
               "#00254A"), 
    bg.border = NA, track.height = 0.05)

##  Add genomic labels
circos.genomicLabels(ann,labels.column = 5, side = "outside", niceFacing = TRUE)

circos.clear()

**Comment by jokergoo** [comment]
The first question, the argument `side` actually means the position of the labels relative to the connection lines. So, when the value is "outside", it means the label is outside of the line. You can simply set it to "inside":

```r
circos.genomicLabels(ann,labels.column = 5, side = "inside", niceFacing = TRUE)
```

![image](https://user-images.githubusercontent.com/449218/98217843-568cac00-1f4b-11eb-87ca-578ec6b64b21.png)

If you want to put the labels outside of the first track, you need to put `circos.genomicLabels()` as the first track. Now here in `circos.genomicInitialize()`, I also set `plotType = NULL` which intializes the plot but draw no track.

```r
circos.par(start.degree = 90, gap.after = c(1, 1, 1, 1, 1, 5, 1, 5))
circos.genomicInitialize(df, sector.width = sector.width, plotType = NULL)
circos.genomicLabels(ann,labels.column = 5, side = "outside", niceFacing = TRUE)
circos.track(ylim = c(0, 2), 
    bg.col = c("#ACCCDD", # pale yellow
               "#5896AD", # olive yellow 
               "#005C91", 
               "#003C69", 
               "#00254A", 
               "#96AAB5",
               "#005C91",
               "#00254A"), 
    bg.border = NA, track.height = 0.05, panel.fun = function(x, y) {
      circos.genomicAxis()
    })

circos.clear()
```

![image](https://user-images.githubusercontent.com/449218/98218074-9b184780-1f4b-11eb-8473-8aec579b5a93.png)

**Comment by jokergoo** [comment]
For the second question, I think the region of the label 

```
data.frame(chr = "zoom_III",
                  exon_start = 8193843,
                  exon_end = 8201217,
```

is far longer (7374bp) than the length of `zoom_III` (500bp)

```
zoom_III 8200512  8201012
```

I think I should better add a warning in `circos.genomicLabels()` when the region of the label is longer than the length of the chromosome.

**Comment by moldach** [comment]
Sorry I never caught that the feature wasn't within the range.

I think you made a type here (but I get the point):

```
data.frame(chr = "zoom_III",
                  exon_start = 8200600,
                  exon_end = 8200700,
```

I've pretty much got what I want now; however, I noticed that the range for `zoom_V` in `df` like this produces a visual artefact in the `circos.link()` - see the tiny white line slashing through the purple:

```
df = read.table(textConnection(
"chr    start   end
I 0 15072434
II 0 15279421
III 0 13783801 
IV 0 17493829
V 0 20924180
X 0 17718942
zoom_III 8193843 8201217
zoom_V 8930610 8930700
"), header = TRUE)

ann <- data.frame(chr = c("III", "zoom_III"),
                  exon_start = c(8193843, 8193843),
                  exon_end = c(8201217, 8201217),
                  value = c(1, 1),
                  name = c("eT1", "eT1")
)

circos.genomicInitialize(df, sector.width = sector.width, labels.cex = 1.2, axis.labels.cex = 0.48, plotType = NULL)

circos.genomicLabels(ann,labels.column = 5, side = "outside", niceFacing = TRUE)
circos.track(ylim = c(0, 2), 
    bg.col = c("#ACCCDD", # pale yellow
               "#5896AD", # olive yellow 
               "#005C91", 
               "#003C69", 
               "#00254A", 
               "#96AAB5",
               "#005C91",
               "#00254A"), 
    bg.border = NA, 
    track.height = 0.05, 
    panel.fun = function(x, y) {
      circos.genomicAxis()
    })


circos.link("III", c(8200762, 8200762 - 57), "V", c(8930675, 8930675 - 43), col = "#5F4B8BFF")
circos.link("zoom_III", c(8200762, 8200762 - 57), "zoom_V", c(8930675, 8930675 - 43), col = "#5F4B8BFF", inverse = TRUE)

circos.clear()
```

![artefact](https://user-images.githubusercontent.com/5749465/98274682-f26ce680-1f50-11eb-8d8d-7bf8fd04678f.png)

**Comment by moldach** [comment]
Also why am I see this error. To me it looks like the range is fine:

> `df`: `zoom_III 8193840 8201220`

& 

> `ann`: `zoom_III 8193843 8201217`


```
> circos.genomicLabels(ann,labels.column = 5, side = "outside", niceFacing = TRUE)
Warning messages:
1: Some of the regions have end position values larger than the end of the chromosomes. 
2: Some of the regions have end position values larger than the end of the chromosomes. 
``

This warning suggest the end position of the `ann` = `8201217` is > than the end of the chromosome (for `III` and `zoom_III`).

But `8201220` is > than `8201217`

To confirm this, If you made the end of `zoom_III` smaller (`8201210`) you get the following error:

```
Warning messages:
1: Some of the regions have end position values larger than the end of the chromosomes. 
2: Some of the regions have end position values larger than the end of the chromosomes. 
3: Some of the regions have end position values larger than the end of the chromosomes. 
```

Not sure why I'm getting this error.

**Comment by jokergoo** [comment]
Hi, both problems are fixed. You can update the package and retry.

**Comment by moldach** [comment]
Works great! Thanks
