### ISSUE TITLE
Concatenating two genomes - genomicLink error

### ISSUE THREAD

**Issue by sav0016** [jokergoo/circlize#232]
Dear Jokergoo,

I would like to ask you for help with the last part of the https://jokergoo.github.io/circlize_book/book/initialize-genomic-plot.html#concatenating-two-genomes 

circos.genomicLink(human_mid, mouse_mid, col = rand_color(19))

This isn´t working for me. I´m still getting error "Error: Your data frame is less than 3 column!."

Thank you very much for your help!

**Comment by jokergoo** [comment]
As it tells, either `human_mid` or `mouse_mid` has less than 3 columns. What is the value of these two variables?

**Comment by sav0016** [comment]
> As it tells, either `human_mid` or `mouse_mid` has less than 3 columns. What is the value of these two variables?

It works after a package update. Thanks for your quick reply.
