### ISSUE TITLE
circos.genomicInitialize

### ISSUE THREAD

**Issue by jinshangkun** [jokergoo/circlize#233]
Hi 
    I am having trouble visualizing the chromosome scale; Strangely, the scale was overlapped; for example, 0Mb overlapped 30Mb. How to resolve it ? 
The code is as follows: 
circos.genomicInitialize(chr,
                         major.by = 30000000)
The file 'chr' format:
chr start end
A01 0 110000000
A02 0 99000000
......

Thanks
Jin

**Comment by jokergoo** [comment]
Please also send me the dataset you used so that I can test on it.

**Comment by jinshangkun** [comment]
[归档.zip](https://github.com/jokergoo/circlize/files/5546060/default.zip)
Thanks！

**Comment by jokergoo** [comment]
Can  you try the newest version fro GitHub? It works fine on my side:

```r
df = read.table("~/Downloads/default/Tanguis_info.txt", header = TRUE)
circos.genomicInitialize(df)
```

![image](https://user-images.githubusercontent.com/449218/99251941-75722480-280e-11eb-9a47-b27d8f072643.png)

**Comment by jinshangkun** [comment]
I am using the newest version(0.4.12) from Github, but it still doesn't work.
> library(circlize)
========================================
circlize version 0.4.12
