### ISSUE TITLE
Is it possible to add Ideogram for the Chord Diagram with circlize?

### ISSUE THREAD

**Issue by venkan** [jokergoo/circlize#236]
I have some data that looks like:

    Genes	     pathway	  values
    ACTA2-AS1	Pathway10	0.996666667
    ACTA2-AS1	Pathway4	0.996533795
    LINC02520	Pathway4	0.996509599
    LINC02520	Pathway10	0.996677741
    LINC02397	Pathway6	0.996960486
    LINC02397	Pathway10	0.996604414
    AL049775.1	Pathway12	0.996031746
    WARS2-IT1	Pathway6	0.997546012
    LINC01754	Pathway5	0.997214485
    LINC01754	Pathway6	0.997572816

This is the link to download original data file named [Egdata.csv][1]

I'm trying to create a `circos plot` using `circlize` from the above data to show the links between genes and pathways.

I tried like below:

    data <- read.csv("Egdata.csv")
    
    library(circlize)
    chordDiagram(data, annotationTrack = "grid", preAllocateTracks = list(track.height = 0.1),
                 big.gap = 30)
    circos.trackPlotRegion(track.index = 1, panel.fun = function(x, y) {
      xlim = get.cell.meta.data("xlim")
      xplot = get.cell.meta.data("xplot")
      ylim = get.cell.meta.data("ylim")
      sector.name = get.cell.meta.data("sector.index")
      if(abs(xplot[2] - xplot[1]) < 10) {
        circos.text(mean(xlim), ylim[1], sector.name, facing = "clockwise",
                    niceFacing = TRUE, adj = c(0, 0.5))
      } else {
        circos.text(mean(xlim), ylim[1], sector.name, facing = "clockwise",
                    niceFacing = TRUE, adj = c(0.5, 0))
      }
    }, bg.border = NA)

And the output looks like in this link [Output Figure with the above code][2]

I would like to add the cytoband information to the figure. And it should look like the image in the below link:

[I want the Figure to be looked like this][3]

Is it possible to do with `circlize`?

  [1]: https://easyupload.io/z7mlkn
  [2]: https://i.imgur.com/0OxADM7.png
  [3]: https://i.stack.imgur.com/8mQv4.jpg

**Comment by jokergoo** [comment]
You need positions for genes and set the 'Pathway' as a fake-chromosome and put each pathway as "genes" evenly positions on this chromosome. Then it is a matter of `circos.link()` or `circos.genomicLink()`.

**Comment by venkan** [comment]
@jokergoo Hi, thanks a lot for the reply. I'm a little confused. I have these two files here [https://easyupload.io/m/piyfqd](url) Could you please check that and tell me with an example. thanq.

**Comment by jokergoo** [comment]
Hi, I just wrote a blog on it. You can find how to implement it from https://jokergoo.github.io/2020/11/27/visualize-relations-between-genes-and-pathways/.

**Comment by venkan** [comment]
Wow @jokergoo Thanks a ton Zuguang. This is awesome.
