### ISSUE TITLE
Adding row names pushes out column name in heatmap

### ISSUE THREAD

**Issue by TamarJ** [jokergoo/circlize#237]
Hi Jokergoo,

I am having some issues with the text formatting on a circular heatmap with two sections.

When I add the row names to the figure the column names are pushed out of the frame.

Software and Pack Information:
- R version 4.0.3
- circlize version 0.4.11
- ComplextHeatmap version 2.6.2

The dataset:
[dfm.txt](https://github.com/jokergoo/circlize/files/5606962/dfm.txt)

The Script (without row names) :
> col_fun1 = colorRamp2(c(-30, -20, -10, -5, 0, 5, 10, 20, 30), c("midnightblue",  "deepskyblue4", "cyan3", "springgreen4", "bisque3", "darkmagenta", "orange", "firebrick", "black"))
> sectors = rep(letters[1:2], times = c(109, 6))
> circos.clear()
> circos.par(gap.after = c(35, 5))
> circos.heatmap(dfm, split = sectors, col = col_fun1, dend.side = "inside")
> circos.track(track.index = 1, panel.fun = function(x, y) {
   if(CELL_META$sector.numeric.index == 1) 
     cn = colnames(dfm)
     n = length(cn)
     circos.text(rep(CELL_META$cell.xlim[2], n) + convert_x(1, "mm"), 
                 1:n - 0.5, cn, 
                 cex = 0.5, adj = c(0, 0.5), facing = "inside")
   }
 }, bg.border = NA)
> lgd = Legend(title = "Log Fold Change", col_fun = col_fun1)
> grid.draw(lgd)
> circos.clear()

The error :
> col_fun1 = colorRamp2(c(-30, -20, -10, -5, 0, 5, 10, 20, 30), c("midnightblue",  "deepskyblue4", "cyan3", "springgreen4", "bisque3", "darkmagenta", "orange", "firebrick", "black"))
> sectors = rep(letters[1:2], times = c(109, 6))
> circos.clear()
> circos.par(gap.after = c(35, 5))
> circos.heatmap(dfm, split = sectors, col = col_fun1, dend.side = "inside")
> circos.track(track.index = 1, panel.fun = function(x, y) {
   if(CELL_META$sector.numeric.index == 1) { # the last sector
     cn = colnames(dfm)
     n = length(cn)
     circos.text(rep(CELL_META$cell.xlim[2], n) + convert_x(1, "mm"), 
                 1:n - 0.5, cn, 
                 cex = 0.5, adj = c(0, 0.5), facing = "inside")
   }
 }, bg.border = NA)
**Note: 4 points are out of plotting region in sector 'a', track '1'.**
> lgd = Legend(title = "Log Fold Change", col_fun = col_fun1)
> grid.draw(lgd)
> circos.clear()

The Output:
![image](https://user-images.githubusercontent.com/59629416/100433780-78f98b80-30eb-11eb-89a8-f4ca9f8cbdb7.png)

**Adding rownames.side**

The script:
>col_fun1 = colorRamp2(c(-30, -20, -10, -5, 0, 5, 10, 20, 30), c("midnightblue",  "deepskyblue4", "cyan3", "springgreen4", "bisque3", "darkmagenta", "orange", "firebrick", "black"))
>sectors = rep(letters[1:2], times = c(109, 6))
>circos.clear()
>circos.par(gap.after = c(35, 5))
>circos.heatmap(dfm, split = sectors, col = col_fun1, dend.side = "inside", rownames.side = "outside", track.height = 0.05)
>circos.track(track.index = 1, panel.fun = function(x, y) {
  if(CELL_META$sector.numeric.index == 1)
    cn = colnames(dfm)
    n = length(cn)
    circos.text(rep(CELL_META$cell.xlim[2], n) + convert_x(1, "mm"), 
                1:n - 0.5, cn, 
                cex = 0.5, adj = c(0, 0.5), facing = "inside")
  }
}, bg.border = NA)
>lgd = Legend(title = "Log Fold Change", col_fun = col_fun1)
>grid.draw(lgd)
>circos.clear()

The error (same as above):
>col_fun1 = colorRamp2(c(-30, -20, -10, -5, 0, 5, 10, 20, 30), c("midnightblue",  "deepskyblue4", "cyan3", "springgreen4", "bisque3", "darkmagenta", "orange", "firebrick", "black"))
> sectors = rep(letters[1:2], times = c(109, 6))
> circos.clear()
> circos.par(gap.after = c(35, 5))
> circos.heatmap(dfm, split = sectors, col = col_fun1, dend.side = "inside", rownames.side = "outside", track.height = 0.05)
> circos.track(track.index = 1, panel.fun = function(x, y) {
   if(CELL_META$sector.numeric.index == 1)
     cn = colnames(dfm)
     n = length(cn)
     circos.text(rep(CELL_META$cell.xlim[2], n) + convert_x(1, "mm"), 
                 1:n - 0.5, cn, 
                 cex = 0.5, adj = c(0, 0.5), facing = "inside")
   }
 }, bg.border = NA)
**Note: 4 points are out of plotting region in sector 'a', track '1'.**
> lgd = Legend(title = "Log Fold Change", col_fun = col_fun1)
> grid.draw(lgd)
> circos.clear()
> 

The output - the first column name is now in the top right hand corner of the image (see below):
![image](https://user-images.githubusercontent.com/59629416/100432919-31becb00-30ea-11eb-9e0b-6bfe94792248.png)

Any assistance would be much appreciated.

Thanks,
Tamar

**Comment by jokergoo** [comment]
1. "Note: 4 points are out of plotting region in sector 'a', track '1'." does not mean an error. It is because the four month names are drawn outside of the cell and in your case, it is completely fine.

2. This is something I didn't make clear in the documentation, 

In  your case, the track where you add column names are the second track, because the row names are in the first track. So in the following code you wrote, `track.index` should be set to 2,
```r
circos.track(track.index = 1, panel.fun = function(x, y) {
```
Or more safely, change to `get.current.track.index()`.

```r
circos.track(track.index = get.current.track.index(), panel.fun = function(x, y) {
```
