### ISSUE TITLE
Question on how to change radius of internal circle

### ISSUE THREAD

**Issue by mat10d** [jokergoo/circlize#238]
I am plotting a circos plot with a number of tracks, but I am having a problem with the genomic labels. As you can see, I have >300 of these, and they are hardly visible. If the radius of the internal circle (where the genomic links lie) was far smaller (ie tracks were closer to the center) then there would be a greater circumference over which to plot the labels, and I could make them larger. Is there any way of doing this? I can include my code if required, but generally based on various tutorials online I couldn't find a way of changing this

![image](https://user-images.githubusercontent.com/53015428/101262988-22560800-3710-11eb-88d9-84395f748298.png)

**Comment by jokergoo** [comment]
You can set `circle.margin` option in `circos.par()` before making the plot:

```r
circos.par(circle.margin= c(1, 1, 1, 1))
circos.initialize(...)
```

It is only supported in recent versions.

**Comment by mat10d** [comment]
Thank you so much. I ended up solving this using a changed connection_height. I was wondering now if there is a way to set the location of the chromosome labels in `initializeWithIdeogram` (to be closer to the center of the circle)? Currently my code:

`circos.initializeWithIdeogram(species = "mm10", 
                              plotType = "labels",
                              labels.cex = 5)
circos.genomicLabels(TD_annotation_final,
                     labels.column = 4, cex = 2.25,
                     side = "outside",
                     line_col = "grey",
                     connection_height = mm_h(100))`

<img width="588" alt="Screen Shot 2020-12-06 at 18 12 56" src="https://user-images.githubusercontent.com/53015428/101295977-cdd58a00-37ee-11eb-8bd0-ba5486ff0d73.png">

**Comment by jokergoo** [comment]
You can first initialize the plot with out drawing anything:

```r
circos.initializeWithIdeogram(..., plotType = NULL)
```

and later you can add the chromosome labels at any track by specifying:

```r
circos.track(track.index = ..., panel.fun = function(x, y) {
    circos.text(...) # chromosome name can be retrieved by CELL_META$sector.index
})
```

In your plot, the ideogram track is the third track, then you can do:

```r
circos.initializeWithIdeogram(species = "mm10", plotType = NULL)
circos.genomicLabels(...)
circos.ideogram(...)
circos.track(track.index =3, panel.fun = function(x, y) {
    circos.text(CELL_META$xcenter, CELL_META$cell.ylim[2], 
        gsub("chr", "", CELL_META$sector.index), adj = c(0.5, -0.4))
})
...
```
 where the chromosome labels are drawn relative to the ideogram track.

**Comment by mat10d** [comment]
Thank you so much!

**Comment by mat10d** [comment]
I had another quick question. Is there any way to set both start and end degree as to leave a gap in the circle (to then insert the legend)? I was hoping to open up an area between chromosome Y and 1 as to do this, but I can't seem to find a way to do it while also ensuring that the entire genome and resulting data is also plotted within that reduced (7/8ths of the circumference of the circle) area. Thank you again.

Matteo

**Comment by jokergoo** [comment]
Yes, set `gap.after` option in `circos.par()`. See https://jokergoo.github.io/circlize_book/book/circular-layout.html#graphic-parameters

It is like:

```r
circos.par(gap.after = c(rep(1, 23), 10))
circos.initialize(...)
...
circos.clear()
```
