### ISSUE TITLE
Add "axis" type to the function "circos.genomicInitialize"

### ISSUE THREAD

**Issue by ttgump** [jokergoo/circlize#24]
Current, we can only create a circle plot in two type: 1. axis + labels 2. labels. It will be better to let user can make a plot with axis and without labels. So I think in the line 193 - 198 in "circos.genomicInitialize" function

`if(all(c("axis", "labels") %in% plotType)) {

  circos.axis(h = 0, major.at = major.at, labels = major.tick.labels, labels.cex = 0.3*par("cex"), labels.facing = "clockwise", major.tick.percentage = 0.2)

  circos.text(mean(xlim), 1.2, labels = sector.names[sector.index], cex = par("cex"), adj = c(0.5, 0), niceFacing = TRUE)

} else if("labels" %in% plotType) {

  circos.text(mean(xlim), 0, labels = sector.names[sector.index], cex = par("cex"), adj = c(0.5, 0), niceFacing = TRUE)

}`

We can add one if statement:

`if(all(c("axis", "labels") %in% plotType)) {

  circos.axis(h = 0, major.at = major.at, labels = major.tick.labels, labels.cex = 0.3*par("cex"), labels.facing = "clockwise", major.tick.percentage = 0.2)

  circos.text(mean(xlim), 1.2, labels = sector.names[sector.index], cex = par("cex"), adj = c(0.5, 0), niceFacing = TRUE)

} else if("axis" %in% plotType) {

  circos.axis(h = 0, major.at = major.at, labels = major.tick.labels, labels.cex = 0.3*par("cex"), labels.facing = "clockwise", major.tick.percentage = 0.2)

} else if("labels" %in% plotType) {

  circos.text(mean(xlim), 0, labels = sector.names[sector.index], cex = par("cex"), adj = c(0.5, 0), niceFacing = TRUE)

}`

**Comment by jokergoo** [comment]
It has been updated according to your suggestion. Thanks!
