### ISSUE TITLE
overlapped labels/circos.text

### ISSUE THREAD

**Issue by sqjin** [jokergoo/circlize#240]
Hi @jokergoo , thanks for the quick reply! I have followed your WeChat account :). Very nice introduction of your excellent tools!! There are also overlapped labels in my case, which is caused by some tiny sectors. I am looking for a solution similar to https://jokergoo.github.io/2020/11/27/visualize-relations-between-genes-and-pathways/. Could you please let me know how I can do it? Another solution might be setting a minimum sector size so that there is no overlapped text. Is it possible to do it ? Thanks!

**Comment by jokergoo** [comment]
Please provide examples and code or error you may have.

**Comment by sqjin** [comment]
I think I could address this issue by increasing the value of parameter `small.gap` in chordDiagram. However, if you have any other solutions, please let me know. Thanks!

**Comment by jokergoo** [comment]
Currently there is no automatic solution, but this is an interesting case. Remember `circos.genomicLabels()` can automatically adjust the positions of text along the circle if the text overlap, I think I may use a similar strategy here. I will put it on my to-do list.

**Comment by sqjin** [comment]
Thanks @jokergoo ! I am sorry I have another question. When I tried to reproduce the [Visualization of traffic intersection loads with Chord diagram](https://jokergoo.github.io/2020/10/13/visualize-traffic-intersection-loads-with-chord-diagram/), I could not exactly reproduce it. For example, for the sector A, I cannot get the blue/green/red colored track. I think this feature is nice when the links become crowded. The figure I got is below. 
![image](https://user-images.githubusercontent.com/32399212/101541714-a5689f80-3956-11eb-9b6b-4cb5ef5c0c41.png)

**Comment by jokergoo** [comment]
Update the package to the newest version.

**Comment by sqjin** [comment]
Thanks @jokergoo , it works when using the newest version.  If I want to hide links associated with one sector, can I also hide the colors in the second track? Basically I want to keep the color of the sector, but do not want to show colors related with any links. An example below is the sector `a`. I am thinking you might can use link.visible to control this color in a similar way. 
![image](https://user-images.githubusercontent.com/32399212/101754129-3e4b0800-3a88-11eb-8563-0b3c44fa439f.png)

**Comment by jokergoo** [comment]
Good point! I forgot to remove these bars when the corresponding is invisible.

**Comment by sqjin** [comment]
> Good point! I forgot to remove these bars when the corresponding link is invisible.

Hi @jokergoo , it seems like this issue has not been solved when I installed the newest version. Could you please take care of it when you get any chance?  Thank you!

**Comment by jokergoo** [comment]
Sorry, now it is fixed.

![image](https://user-images.githubusercontent.com/449218/103914677-7e92ba00-510a-11eb-903c-289b1be3a43a.png)

**Comment by sqjin** [comment]
@jokergoo Thanks so much!
