### ISSUE TITLE
Adding customized clustering methods

### ISSUE THREAD

**Issue by agranado** [jokergoo/circlize#241]
Hi, 
This package is great!
I was wondering what would be the easiest way to add custom clustering methods. For example, to cluster on a user-specified distance matrix, that is not supported by hclust directly e.g., one made using an exponential kernel or cosine distance. 

I checked the code and circos.heatmap.initialize(... ) seems the way to go but I was wondering if you have any advice on this. Thanks!

**Comment by jokergoo** [comment]
Yes, you are right. I forgot that scenario. I will support it.

**Comment by jokergoo** [comment]
Added.

```r
dend = hclust(dist(mat1))
circos.heatmap(mat1, cluster = dend, col = col_fun1, dend.side = "inside")
circos.clear()
```

![image](https://user-images.githubusercontent.com/449218/102193423-5bcf0600-3ebc-11eb-83f5-8ece72139258.png)

When `cluster` is a clustering object, `split` can only be a single number.

```r
circos.heatmap(mat1, cluster = dend, split = 2, col = col_fun1, dend.side = "inside")
circos.clear()
```

![image](https://user-images.githubusercontent.com/449218/102193346-48239f80-3ebc-11eb-9807-159c49b763f7.png)
