### ISSUE TITLE
specify the width of each cell of heatmap using data in circos.heatmap

### ISSUE THREAD

**Issue by caimiao0714** [jokergoo/circlize#242]
Hi Zuguang,

Thank you for creating the `circlize` package in `R`, I found it very powerful and user-friendly compared to the purely command-line based `circos` package.

When I read through the tutorials, I did not find a way to specify the width of each cell of the heatmap using `circos.heatmap`. The following example in the tutorial generates a heatmap with equal width for each cell.

```{r}
set.seed(123)
mat1 = rbind(cbind(matrix(rnorm(50*5, mean = 1), nr = 50), 
                   matrix(rnorm(50*5, mean = -1), nr = 50)),
             cbind(matrix(rnorm(50*5, mean = -1), nr = 50), 
                   matrix(rnorm(50*5, mean = 1), nr = 50))
            )
rownames(mat1) = paste0("R", 1:100)
colnames(mat1) = paste0("C", 1:10)
mat1 = mat1[sample(100, 100), ] # randomly permute rows
split = sample(letters[1:5], 100, replace = TRUE)
split = factor(split, levels = letters[1:5])

library(circlize) # >= 0.4.10
col_fun1 = colorRamp2(c(-2, 0, 2), c("blue", "white", "red"))
circos.heatmap(mat1, split = split, col = col_fun1)
```

Assuming that I have a vector of cell width (`cell_width` below) for the heatmap, I wonder if there is any way to specify the width of each cell using that width?

```
cell_width = runif(nrow(mat1), 0.5, 1)
```

Thank you,
Miao

**Comment by jokergoo** [comment]
This is a good suggestion. I will consider it! Thanks!

**Comment by jokergoo** [comment]
Can you give me a real use case where the cells have different widths? The problem is if the cells have different widths on one heatmap track, they should also have different cell widths on all other heatmap tracks.

**Comment by caimiao0714** [comment]
Thank you! Our team is trying to build the high-dimension health characteristics of COVID-19 positive patients, compared to seasonal flu. Since we have over 300 groups of diagnosis, circos plot excels at showing this high-dimensional outcome. In this plot, we are trying to use the colors of a heatmap to show the hazard ratio (HR) of how likely that specific outcome will occur in COVID-19 patients compared to seasonal flu patients. In the meanwhile, we want to make the width of the cells proportional to the prevalence of these diagnoses. In short words, the colors are showing risk on a relative scale (compared to flu patients), while the width is showing risk on an absolute scale.

**Comment by jokergoo** [comment]
Thanks for the information!

No problem, I will implement it.

**Comment by caimiao0714** [comment]
Thanks a lot!!! BTW, could you also enable that similar function for barplots? I also need to do similar things for inner rings, in which the widths of the bars need to be scaled proportionally to the prevalence too.

**Comment by jokergoo** [comment]
Hi, I have added this new feature. You can find explanations at https://jokergoo.github.io/2021/01/07/set-heatmap-cell-width-in-circos.heatmap-function/.

You can update from GitHub.
