### ISSUE TITLE
self.link = 0

### ISSUE THREAD

**Issue by Roenbaeck** [jokergoo/circlize#243]
I would like to see an option "self.link = 0" (or similar) that works like "self.link = 1" but that does not draw the link. In other words, the mountain-shaped intra-links would just be blank areas (as if only they had link.visible = FALSE). 

The reason for this is that when you have some segments that are largely static the mountain-shapes detract from the visual fidelity when you need to spot actual changes. If there is a workaround to hide these, let me know.

**Comment by Roenbaeck** [comment]
I found a simple workaround in the meantime: 
```
no_self_matrix <- matrix
diag(no_self_matrix) = 0
chordDiagram(
  matrix, 
  link.visible = as.logical(no_self_matrix),
)
```

**Comment by jokergoo** [comment]
If possible, can you give me a runnable example?

**Comment by jokergoo** [comment]
Now I see what you mean. Yes, what you have done is correct. Set `link.visible` to `FALSE` for diagonals of the matrix.
