### ISSUE TITLE
Genomic track position 

### ISSUE THREAD

**Issue by Ariel-TC** [jokergoo/circlize#247]
Hi,
Thanks for your brilliant tool! 
And is there a way we can put the genomic track inside the whole plot? Besides genomicHeatmap, can I have other genomic functions?
Thanks for your fantastic tool again and appreciate for your answer.

Best,
Ariel.

**Comment by jokergoo** [comment]
I think you can first draw the genomic heatmap and then other genomic tracks:

```r
circos.genomicHeatmap(...)
circos.genomicTracks(...)
```

The order of putting these tracks is always from outside to inside.

It would be better if you also attach some code.

**Comment by Ariel-TC** [comment]
Thank you for your patience.
But, emmm, I mean, Can I draw some other plot like circos.genomicLines or something else before I plot the genomic track.
and here's my code , though I haven't find solutions.

` >circos.clear()`
` >set.seed(123)`
` >circos.par("track.height" = 0.08)`
` >circos.par("start.degree" = 90)`
` >circos.par("gap.degree" = c(rep(c(2, 4), 12), 2))`
` >circos.initializeWithIdeogram(plotType = NULL)`
` > circos.genomicTrackPlotRegion(EC,panel.fun = function(region, value, ...){`
` +   circos.genomicLines(region, value, side = "outside", type = "h", col='#DE3163', ...)}) `
` > circos.genomicIdeogram(w)`


> Warning message: Cannot map colors to cytobands. The ideogram won't be drawn.

Best,
Ariel.

**Comment by jokergoo** [comment]
The code looks fine.

Can you send me the data for `EC` and `w` so that I can have a try?

**Comment by Ariel-TC** [comment]
yes, sure.
EC dataset is my plot dataset and w is the cytobandideo data.
` > head(EC)`
`1 chr1   144500   145000   0.76`
`2 chr1   124500   125000   0.50`
`3 chr1 11872500 11873000   0.00`
`4 chr1 19366000 19366500   0.86`
`5 chr1 49379000 49379500   0.46`
`6 chr1 51049500 51050000   0.00`
` > head(w)`
`  Chromosome ChromStart ChromEnd Band Stain`
`1       chr1          0 59578282 chr1  gneg`
`2       chr2          0 59640629 chr2  gneg`
`3       chr3          0 62628489 chr3  gneg`
`4       chr4          0 78093715 chr4  gneg`
`5       chr5          0 72500376 chr5  gneg`
`6       chr6          0 60270059 chr6  gneg`

Best,
Ariel.

**Comment by jokergoo** [comment]
I mean, give me your full datasets (the complete data frame). You can send to my email address.

**Comment by Ariel-TC** [comment]
OK.  
Thanks a lot for your help.

Best,
Ariel.
