### ISSUE TITLE
Currently there is no automatic solution, but this is an interesting case. Remember `circos.genomicLabels()` can automatically adjust the positions of text along the circle if the text overlap, I think I may use a similar strategy here. I will put it on my to-do list.

### ISSUE THREAD

**Issue by bio-la** [jokergoo/circlize#250]
Currently there is no automatic solution, but this is an interesting case. Remember `circos.genomicLabels()` can automatically adjust the positions of text along the circle if the text overlap, I think I may use a similar strategy here. I will put it on my to-do list.

_Originally posted by @jokergoo in https://github.com/jokergoo/circlize/issues/240#issuecomment-740854062_

**Comment by bio-la** [comment]
Hi @jokergoo thanks for this amazing package! 
I am trying to adapt the circos.genomicLabels to a case where i don't have a bed dataframe to start with, but a link dataframe where the start/end of each sector is calculated from the link dataframe based on how many occurrence of the sender are in the dataframe, using chordDiagram.  

sender | target  |    weight
-------|--------|-----------
ANXA1 TNKcells | TNF_TNKcells | 0.002613754
HLA-DRA TNKcells | TNF_TNKcells | 0.002934061
ITGB2 TNKcells |TNF_TNKcells |0.002922275
ITGB2 TNKcells |TNF_Myelo |0.002922275

this is just the same issue as the original issue i am referencing. the issue was closed but the original problem was not addressed apart from suggesting to use the genomicLabels function. can't figure a way to do this. 
Any pointer please? I was trying to get the CELL_META info for each sector into one dataframe but the function is not built with that purpose in mind.
thanks!

**Comment by jokergoo** [comment]
Hi, it would be great if you can also provide me code and dataset.
