### ISSUE TITLE
genomicTrack - regions counted and rows of bed file don't match

### ISSUE THREAD

**Issue by khuhu** [jokergoo/circlize#253]
Please provide example datasets and the code you use. It will help me to understand your problem and help you!
Hi,

When I try to feed a vector of colors equal to the numbers of rows in my bed input, I get thrown an error telling me the length of my color vector doesn't match the number of regions. 

```
circos.par("track.height"= 0.05) + 
 circos.initializeWithIdeogram(cytoband = cyto_combined_red, sort.chr = FALSE) + 
 circos.genomicTrack(cn_track_bed, ylim = c(-1,1),
                      panel.fun = function(region, value, ...) {
                        circos.genomicLines(region, value,
                                            col = track_color, type = "segment", ...)
                      })

Error: The length of `col` (410) should be equal to 1 or the number of your regions (13).
```

The vector of colors was created using the colorRamp2 function.
The dimensions and length of the input bed and vector of colors respectively:

```
color_cn = colorRamp2(c(-0.5, 0, 0.5), c("#ADD8E6", "#000000", "#FFCCCB"))
track_color <- color_cn(cn_track_bed$cn)

dim(cn_track_bed)
[1] 410   4

length(track_cn)
[1] 410
``` 

I don't understand where the graphing function is getting 13 regions from.

**Comment by jokergoo** [comment]
It is because `panel.fun` is executed for each chromosome, so `col` in `circos.genomicLines()` should only correspond to "current chromosome". You can do in  multiple ways:

1. append `col` to your `cn_track_bed` data frame:

```r
cn_track_bed$col = track_color
 circos.genomicTrack(cn_track_bed, ylim = c(-1,1),
                      panel.fun = function(region, value, ...) {
                        circos.genomicLines(region, value,
                                            col = value$col, type = "segment", ...)
                      })
```

2. or take the subset of `col` that only correspond to current chromosome:

```r
 circos.genomicTrack(cn_track_bed, ylim = c(-1,1),
                      panel.fun = function(region, value, ...) {
                        col =  track_col[cn_track_bed[, 1] == CELL_META$sector.index]
                        circos.genomicLines(region, value,
                                            col = col, type = "segment", ...)
                      })
```

**Comment by khuhu** [comment]
Works perfectly, thanks! I'll take another look at your guide, must've missed the panel.fun specifics.
