### ISSUE TITLE
labels

### ISSUE THREAD

**Issue by testorialessandro** [jokergoo/circlize#255]
Hello! Regarding 12.3 (Labels) from https://jokergoo.github.io/circlize_book/book/high-level-genomic-functions.html#labels : is it possible to have multiple nearby distinct genomic locations point to the same label? Thank you.

**Comment by jokergoo** [comment]
Currently no, but this is a nice suggestion!

**Comment by testorialessandro** [comment]
BTW, I have many labels and it seems to me that if I reduce the font size in circos.genomicLabels(... , **cex = 0.45**, ...), a genomic location that previously (i.e.: without the cex parameter and thus with a bigger font size) pointed to labels A and B now points to label A only, leaving label B without a connection line: could that be? Thank you.
