### ISSUE TITLE
Not an issue. Just wanted to say thank you!

### ISSUE THREAD

**Issue by JBarsotti** [jokergoo/circlize#256]
Hi Dr. Gu,

Your circlize package has been a lifesaver for me!!!!

I am currently working through it with the hopes of using it in some research I am doing. If any papers/presentations ever come of it, I would like to make sure I give you the credit you rightfully deserve for all your hard work! I know you give a reference in the documentation:

Gu, Z. (2014) circlize implements and enhances circular visualization in R. Bioinformatics. DOI: 10.1093/bioinformatics/btu393

Just wondering if there is anything else you would like included as far as acknowledgments go?

Thanks again for your package,

John

**Comment by jokergoo** [comment]
Hi John,

I am happy it helps you! And thank you for (will) citing the paper, that is enough for supporting this project! :)

Zuguang

**Comment by PippintheFoolhardy** [comment]
Hi Dr Gu,

Okay. I will make sure to do that in the event my research every amounts to anything (which is no certain thing right now)! 
:)
