### ISSUE TITLE
error in circos.genomicHeatmap function

### ISSUE THREAD

**Issue by Yunuuuu** [jokergoo/circlize#257]
Hi, Zuguang, Thanks you for developing such good package!

I came across an error when using circos.genomicHeatmap without providing the parameter col, which gave me an error:
`Error in seq.default(min(na.rm = TRUE), max(mat, na.rm = TRUE), length = 3) : 
  'from' must be a finite number`

I checked the source code of  circos.genomicHeatmap, there presented such bulk codes:
```
    if (missing(col)) {
        col = colorRamp2(seq(min(na.rm = TRUE), max(mat, na.rm = TRUE), 
            length = 3), c("blue", "#EEEEEE", "red"))
    }
```

Maybe there lacks a numeric  argument like `mat` for `min` function?

The version of circlize I used is circlize_0.4.12. which is the newest.

**Comment by jokergoo** [comment]
What is the value of `min(na.rm = TRUE)`?

**Comment by Yunuuuu** [comment]
Yeah, I think so, The source code of circos.genomicHeatmap is wrong for missing such argument, I'm not familiar with github and I don't know how to present code for this package.

The ComplexHeatmap and circlize both are very helpful to me. Appreciate you!

**Comment by jokergoo** [comment]
Ah, thank you! That was a mistake there!

I have updated the package.
