### ISSUE TITLE
no arrow in circos.link

### ISSUE THREAD

**Issue by maikeheidemeyer** [jokergoo/circlize#258]
Hello, I am having troubles getting an arrowhead from the circos.link command. Ive tried any possible combinations from the chordiagram function. It does create a link, but no arrow.
Please help!

Ive applied the usage details, from the package without any luck.
Thank you for looking into it

Please provide example datasets and the code you use. It will help me to understand your problem and help you!
circos.link(
sector.index1="Costa Rica",
c(0,920),
sector.index2="Hong Kong",
c(0,1200),
h.ratio = 0.5,
col = "black",
lwd = par("lwd"),
lty = par("lty"),
border = col,
directional = 0,
arr.length = ifelse(arr.type == "big.arrow", 0.02, 0.4),
arr.width = arr.length/2,
arr.type = "triangle",
arr.lty = lty,
arr.lwd = lwd,
arr.col = col,
reduce_to_mid_line = FALSE)

**Comment by jokergoo** [comment]
Only directional links can have arrows. You need to set `directinoal = 1` or -1.

**Comment by maikeheidemeyer** [comment]
Do, this makes totally sense. Thank you!
