### ISSUE TITLE
line type of arrows with circos.link 

### ISSUE THREAD

**Issue by maikeheidemeyer** [jokergoo/circlize#259]
Hey again,
thanks for your quick reply earlier. Im dealing with circos.links and want to create big.arrows with dotted or dashed border, but don't seem to manage:

circos.link("a", c(i-0.07, i-0.05), "a", c(i + 0.05, i+0.1), directional=-1, col = "blue",  lwd = par("lwd"), lty = par("lty"), border = col, arr.type = "big.arrow", arr.lwd = lwd, arr.lty = lty, arr.col = col)

How can I adjust both arrow color (fill) and border color as line type?
Thank you

**Comment by jokergoo** [comment]
`col` controls the filled color and `lty` controls the line type. Also you better set `border` to a different value from `col`.
