### ISSUE TITLE
adding a title to chordDiagram

### ISSUE THREAD

**Issue by akzaidi** [jokergoo/circlize#26]
Thanks for the awesome package! Is there a way to add titles to the visualizations? Moreover, the value returned from `chordDiagram` is a matrix, is there any way to store the image itself?

**Comment by jokergoo** [comment]
The circlize package is built under the base graphic system in R, which means you can add the title by `title()`. If you want to save the image into a file, you can use functions link `png()`, `jpeg()`, `pdf()`, ... You can type "?device" for help.

**Comment by akzaidi** [comment]
Ah okay, completely forgot how base plots through `graphics` worked. I had a map that made many `chordDiagrams`, so adding a `recordPlot` in the function allowed me to save them for later. Thanks !
