### ISSUE TITLE
not enough space for cells at track index '8'

### ISSUE THREAD

**Issue by ykm7788** [jokergoo/circlize#260]
Just got this error when I tried to plot 8th circle. Does it mean I can only plot 7 trace max ?

**Comment by jokergoo** [comment]
You can reduce the track height by setting `track.height` either in `circos.track()` or globally by `circos.par(track.height = ...)`.

**Comment by ykm7788** [comment]
> You can reduce the track height by setting `track.height` either in `circos.track()` or globally by `circos.par(track.height = ...)`.

Thank you for your advice, problem solved.
