### ISSUE TITLE
Add lines from the center to the outer circumference

### ISSUE THREAD

**Issue by SimonaSecomandi** [jokergoo/circlize#261]
Hello,

I'm trying to add lines that goes from the certer of the circle to the outer circumference in order to compare different values among the different tracks.

Is it possible to do that with circlize?

Many thanks,

Simona

**Comment by jokergoo** [comment]
It is not easy to directly connect graphics in different tracks. As shown in the circlize book:

https://jokergoo.github.io/circlize_book/book/circular-layout.html#coordinate-transformation

there are several coordinate systems. You can convert between these coordinate systems as in the following example:

```r


library(circlize)
circos.initialize(sectors = letters[1:6], xlim = c(0, 1))
circos.track(ylim = c(0, 1))
circos.track(ylim = c(0, 1))

## connect [0.5, 0.5] in sector "a", track 2 to [0.2, 0.8] in sector "c", track 1

pt1 = circlize(0.5, 0.5, sector.index = "a", track.index = 2)
pt1 = circlize:::polar2Cartesian(pt1)

pt2 = circlize(0.2, 0.8, sector.index = "b", track.index = 1)
pt2 = circlize:::polar2Cartesian(pt2)

lines(c(pt1[1, 1], pt2[1, 1]), c(pt1[1, 2], pt2[1, 2]))
```

![image](https://user-images.githubusercontent.com/449218/128051301-48d2bf78-bd43-45bc-9d64-2748b6c2c4e8.png)
