### ISSUE TITLE
Font Type

### ISSUE THREAD

**Issue by pascoawaf** [jokergoo/circlize#262]
Hi there, I´m pascoawaf. Please someone know how to change RStudio font to Times New Roman? TKS...

**Comment by jokergoo** [comment]
Maybe this link helps?

https://stackoverflow.com/questions/27689222/changing-fonts-for-graphs-in-r

**Comment by pascoawaf** [comment]
Well, exactly, I need to edit Chord Chart diagram with Times New Roman font... Thank You!
