### ISSUE TITLE
canvas.xlim,canvas.ylim set to -0.5,0.5 plot show not completely

### ISSUE THREAD

**Issue by zhangjun-123** [jokergoo/circlize#264]
Thank you for your this powerful package Circlize.I set  canvas.xlim = c(-0.5,0.5), canvas.ylim = c(-0.5,0.5) , but the plot in the rstudio not show completely. Can you give some advice to solve this problem ? Thank you very much!

**Comment by jokergoo** [comment]
What's the purpose of setting `canvas.xlim = c(-0.5,0.5), canvas.ylim = c(-0.5,0.5)`? The circle is dawn in an area of [-1, 1] on x-axis and [-1, 1] on y-axis. Of course setting to [-0.5, 0.5] only shows part of the plot.
