### ISSUE TITLE
add border and line parameters to circos.heatmap() function

### ISSUE THREAD

**Issue by imcoleman** [jokergoo/circlize#270]
Hello,
Love the circlize package, thanks for creating it!  I was wondering if it would be possible to add the border and line parameters (which are in the circos.genomicHeatmap() function) to the circos.heatmap() function?
Thanks,
Ilsa

**Comment by jokergoo** [comment]
Now I added three arguments `cell.border`, `cell.lty` and `cell.lwd` in `circos.heatmap()`:

```r
circos.heatmap(mat1, split = split, col = col_fun1, cell.border = "black", cell.lty = 3)
circos.heatmap(mat1, split = split, col = col_fun1, cell.border = "white")
circos.heatmap(mat1, split = split, col = col_fun1)
```
![image](https://user-images.githubusercontent.com/449218/133755739-34ac600b-c9f7-4a8a-a732-d052eca299f6.png)
