### ISSUE TITLE
Comparison of 3 bacterial genomes 

### ISSUE THREAD

**Issue by ghs101** [jokergoo/circlize#276]
Hi, 

this is not an issue, but rather a question. 

I want to compare 3 bacterial genomes using a circular visualisation. Is it possible to have each bacteria with labels for virulence factors as a ring?  

kind regards

**Comment by jokergoo** [comment]
I think you can combine the tree virus genomes as a "fake genome" with three chromosomes.

**Comment by ghs101** [comment]
thank you for the suggestion I got it working. However, I still have troubles labeling my genes of interest in my 3 genomes.  I would like use labels with locations generated with a different program. The issue is that the locations do not full match the position of genes that was fed into circos.genomicInitialize.  I use a different dataframe with the specified locations and I get the following error. Is there a way to bypass this problem? 


```

str(all_genome)
'data.frame':	2685 obs. of  6 variables:
 $ new       : chr  "test_1" "test_1" "test_1" "test_1" ...
 $ start     : num  204 1863 2216 2497 2699 ...
 $ end       : num  1583 2219 2401 2685 3334 ...
 $ strand    : chr  "-" "+" "+" "-" ...
 $ attributes: chr  "putative transport protein YifK" "hypothetical protein" "hypothetical protein" "hypothetical protein" ...
 $ seqname   : chr  "1" "1" "1" "1" ...

circos.genomicInitialize(all_genome,plotType = c("axis", "labels"), sector.names = names)


str(anno)
tibble [168 x 4] (S3: tbl_df/tbl/data.frame)
 $ new  : chr [1:168] "test_1" "test_1" "test_1" "test_1" ...
 $ start: num [1:168] 104370 106216 107712 108661 199132 ...
 $ end  : num [1:168] 105680 107145 108659 109638 201931 ...
 $ value: chr [1:168] "sbi" "hlgA" "hlgC" "hlgB" ...

circos.genomicLabels(anno, labels.column = 4, side = "outside")

Error in names(sector.data) <- colnames(.SECTOR.DATA)[-1] : 
  'names' attribute [6] must be the same length as the vector [0]
```

**Comment by jokergoo** [comment]
Why the positions are different between `all_genome` and `anno`? Can you make some transformations to make them consistent, e,g to subtract some offset?

**Comment by ghs101** [comment]
All_genome is based on prokka annotations for the whole genome of bacteria and anno is virulence factors and their positions found with Abricate within the genome. There seems to be some discrepancy between the 2 methods for some genes and their positions. However it's not in a systematic difference  so I can't offset anno.

**Comment by kullrich** [comment]
Hi, are there plans to integrate multiple genomes in one view, meaning each of the three genomes has its own circle. So far I have not seen it and it would be really nice to have. This feature is even not in the original circos software nor in the BioCircos.js.
Of course there are a lot of circos like tools where you can just create a "fake genome" with just listing all chromosomes in one genome, but this is not what I mean. I really would like to see the three genomes objects, that I can link. This will of course break the section/track like structure (which should be kept for each genome).
Thank you in anticipation for your suggestions on it
