### ISSUE TITLE
do not auto-adjust link-order

### ISSUE THREAD

**Issue by yingzhangpnnl** [jokergoo/circlize#277]
Hi, I want to plot using chordDiagram() according to the default order in the data.frame, without auto adjust of the link order. I notice there's an option of link.auto, but in the R documentation, it says the option is ignored. I wonder if there's way to turn off the  link order auto adjust, so that I can manually adjust the row order in the input data.frame and plot by the default order? 
I know that there's link.sort and link.decreasing options. Those are very helpful, but do not give me what I want in my case. 
Thank you.

**Comment by jokergoo** [comment]
Can you give me an example with code and data?

**Comment by yingzhangpnnl** [comment]
Yes. Please see attached data, and the script below. Thank you.
[example_data.csv](https://github.com/jokergoo/circlize/files/7260469/example_data.csv)
```
library(dplyr)
library(stringr)
library(circlize)
library(RColorBrewer)
library(flipChartBasics)
library(tibble)

dat_circular<-as_tibble(read.csv('example_data.csv')) %>% select(-X)
dat_circular<-dat_circular %>% filter(REG_im=="World",flow>0) %>% 
  arrange(flow) %>% 
  bind_rows(dat_circular %>% 
              filter(REG_im=="World",flow<0) %>% 
              arrange(flow)) %>% 
  bind_rows(dat_circular %>% 
              filter(REG_im!="World",flow<0) %>% 
              arrange(flow)) %>% 
  bind_rows(dat_circular %>% 
              filter(REG_im!="World",flow>0) %>% 
              arrange(desc(flow))) 

linkcol<- dat_circular %>% filter(REG_im=="World") %>% 
  mutate(linkcol1=if_else(flow<0,"#C70039FF","#41D302FF")) %>% 
  bind_rows(dat_circular %>% 
              filter(REG_im!="World") %>%
              mutate(linkcol1=if_else(flow<0,"#C7008E","#02D390FF"))) 
linkcol1<-as.character(linkcol$linkcol1)


png(file = "Figure_example.png", width = 3500, height = 3500, res = 500)
chordDiagram(as.data.frame(dat_circular),link.sort = T,link.decreasing = F,
             transparency = 0.5,
             directional = 1,
             direction.type = c("diffHeight", "arrows"), 
             diffHeight = -uh(2, "mm"),
             link.arr.type = "big.arrow"
             , col = linkcol1
             , grid.col = "#CEC4C3FF"
             ,annotationTrack = c("grid")
             ,preAllocateTracks = list(list(track.height = c(0.3))
                                       ,list(track.height = c(0.035))
             ))

circos.track(track.index = 3, panel.fun = function(x, y) {
  circos.axis(h = 1, labels.cex = 0.8)   
}, bg.border = NA)

circos.track(track.index = 1,
             panel.fun = function(x, y) {
               xlim = get.cell.meta.data("xlim")
               xplot = get.cell.meta.data("xplot")
               ylim = get.cell.meta.data("ylim")
               sector.name = get.cell.meta.data("sector.index")
               
               circos.text(mean(xlim), ylim[1], sector.name, facing = "clockwise",
                           niceFacing = TRUE, adj = c(0, 0.5), col = "black",
                           cex = 1)
               
             }, bg.border = NA)

dev.off() #dump

```

**Comment by jokergoo** [comment]
Is there any reason that you don't like the default order (not setting `link.sort`)?

![image](https://user-images.githubusercontent.com/449218/135615624-cd306d51-6d61-481c-928c-b2d5c4f9ea68.png)

**Comment by jokergoo** [comment]
Currently, the implementation only allows either doing the default ordering (which actually makes the plot look nice) or ordering the links by their widths. I think it might be necessary to allow for more flexible controls of ordering, but I need to think of a proper implementation for this.

**Comment by jokergoo** [comment]
You can update the package from GitHub and set `link.sort = "asis"`. Check whether this is what you expect.

**Comment by yingzhangpnnl** [comment]
Thank you! There's no strong reason why I don't like the default order, or the sorted order. They are very nice and useful. The initial reason why I asked about manually order the links is for replicating a figure, which none of the options does for a 100% replication. So I wondered whether the function can be more flexible.

**Comment by yingzhangpnnl** [comment]
May I ask how do I update the package from GitHub? I tried "update.packages('circlize')" and it didn't seem to recognize the new change. Thank you.

**Comment by jokergoo** [comment]
```r
library(devtools)
install_github("jokergoo/circlize")
```

**Comment by yingzhangpnnl** [comment]
The resultant figure is not really what I want. Here's what I want:

![example](https://user-images.githubusercontent.com/57912913/135680414-3a01fd0a-a120-49cd-8352-87bb5e67f179.png)

I wonder how does the function order links according to the order of rows in the input data.frame?

**Comment by jokergoo** [comment]
It is a matter of how you order your data frame. In your data frame:

```
> dat_circular
# A tibble: 16 x 3
   REG_ex        REG_im            flow
   <chr>         <chr>            <dbl>
 1 N. Africa     World            8.74
 2 W. Africa     World           10.2
 3 M. East       World           18.7
 4 USA           World          -91.7
 5 Other regions World          -63.0
 6 Australia_NZ  World          -45.3
 7 Brazil        World          -44.6
 8 Argentina     World          -43.2
 9 World         Other regions -140.
10 World         M. East        -71.4
11 World         N. Africa      -32.0
12 World         W. Africa      -30.5
13 World         Australia_NZ     8.71
14 World         USA              7.56
15 World         Brazil           6.63
16 World         Argentina        0.948
```

The first link from `N. Africa` should go to `World` and it should locate at the beginning of `World` (the reciever part). Also for links coming out from `world`, the links should be ordered as `Other regions`, `M.East`, .... Both scenarios do not fit the plot you attached (your order is `USA`, `Brazil`, ...).

**Comment by jokergoo** [comment]
Try this code, this gives the order you want:

```r
chordDiagram(dat_circular[c(8,7,6,5,4,3,2,1, 14,13,16,12,11,10,9),],directional =T, link.sort = "asis", direction.type = c("diffHeight", "arrows"), link.arr.type = "big.arrow",link.target.prop =F,diffHeight = -uh(2, "mm"), order = c(unlist(dat_circular[1:9, 1]))
```

![image](https://user-images.githubusercontent.com/449218/135730898-ff32c0d6-1f73-4eed-899d-d7527e731387.png)
