### ISSUE TITLE
plot error points

### ISSUE THREAD

**Issue by Sisov** [jokergoo/circlize#28]
Dear  jokergoo:
while I use my data run the circlize to plot the genomic Points track,It appear some Unexpected errors.all the points are gathered into several scaffold and some points out of track.the errors is that:
 Note:6822 points are out of plotting region in sector 'scaffold_1', track '3'.

Note:7642 points are out of plotting region in sector 'scaffold_2', track '3'.

Note:7608 points are out of plotting region in sector 'scaffold_3', track '3'.

my bed1 files only have three column which only include chromosome and position and code is that： circos.genomicInitialize(bed1)

circos.genomicTrackPlotRegion(ylim=c(0,1),bg.col=rainbow(nrow(bed1)),track.height=0.1)

circos.genomicTrackPlotRegion(bed2,track.height=0.1,ylim = c(-1,1),panel.fun = function(region, value, ...) {circos.genomicPoints( region, value, pch = 16, cex = 0.1,...)})

Can anyone could how to explain it ?I am a new to plot the circos picture,Any help will be appreciated

Thanks

**Comment by jokergoo** [comment]
Hi, that's most probably because of the format of `bed1` and `bed2`. Can you send me `bed1` and `bed2` (or a subset of the data) to my email (z.gu@dkfz.de) so that I can test on them?

Cheers

**Comment by Sisov** [comment]
Yeah,Thanks ,It has solved ,It'S my data appear some errors,
Thank you
