### ISSUE TITLE
chordDiagram is it possible to have have portions of a sector that don't connect to anything?

### ISSUE THREAD

**Issue by Mike-L-V** [jokergoo/circlize#282]
I don't know if this was made with circlize but it shows what I'm looking for in Figure 2 from this paper: https://www.cell.com/ajhg/fulltext/S0002-9297(17)30497-4

In particular I'd like the chords/links at the start of each sector and then the empty section as the last part of each sector, just like in the above figure. Is this possible using chordDiagram? Thank you.

[edit] I'm able to do this somewhat by using the new option link.sort = "asis" along with using self-links with transparent colors (adding "00" to the end of the color hex code) for the portion of a sector I want to be blank.

**Comment by jokergoo** [comment]
Yes, you just set those links to be fully transparent.

See https://jokergoo.github.io/circlize_book/book/the-chorddiagram-function.html#highlight-links
