### ISSUE TITLE
Chord diagram customization: Same width for sectors

### ISSUE THREAD

**Issue by vikramshenoyhandiru** [jokergoo/circlize#286]
Hi,

First of all, thank you very much for developing this awesome package! Clearly, it's a very powerful tool for visualization. 
With a great package comes a great deal of customization :) Coming to the question, is there any way we can customize the sector width to be equal? As of now, the default setting is that the sector width is proportional to the number of connections. 

Another question: Is the "strength" of the connection reflected by the color code as well as the thickness? Because, in my graph, there are some connections that are thin but dark-colored, and there are some thick but light-colored as well. I don't know what's that supposed to mean. I've attached the image for your reference. In this image, I want the right and left hemispheres to be symmetrical. How do I achieve this? 

 
![circlize-brainConnectivity](https://user-images.githubusercontent.com/30717056/138911237-8c4075d7-a1f8-4fa7-b43c-97a2083a0a26.png)

-
Vikram

**Comment by jokergoo** [comment]
1. Is there any reason why you want all the sectors to have the same width? 
2. Can you also show me the code on how you set the colors?

Regarding to the first point, yes it is possible, but it is not straightforward. As you can see, if all sectors have the same width, a link would have different widths for its two ends. If you can manage to calculate (or to scale) proper values for the widths of every link's ends, then you can use a data frame as input for `chordDiagram()`, but now with four columns. The last two columns correspond to the width of two ends of every link. See https://jokergoo.github.io/circlize_book/book/the-chorddiagram-function.html#unequal-width-of-the-link-ends.

**Comment by vikramshenoyhandiru** [comment]
Hi, 

The reason for the same width sectors is to have the symmetric appearance of all the sectors (left vs. right halves to be the mirror images of each other). 

Regarding my second question about the color and thickness of the links, can you please comment on why there are some connections that are thin but dark-colored, and there are some thick but light-colored? 

I apologize if the code below doesn't make sense/not well written, I'm relatively new to R.
`# Housekeeping here (loading all the libraries, initializing filepaths)
library(Matrix)
library(rmatio)
library(R.matlab)
library(ggplot2)
library(colorspace)
library(RColorBrewer)
library(extrafont)
library(circlize)

# load the connectivity matrix "mat"
m=read.mat("~folder containing the file~/theta_TBIvsHC.mat") # reading from MATLAB file
mat = m$conn  

# min-max normalization to scale the values from 0 to 1
X = (mat-min(mat))/(max(mat)-min(mat)) 

# row names and column names
rownames(mat) =c("cing.gyr.R","mid.front.gyr.R","sup.fron.gyr.R","paracent.lob.R","precentral.gyr.R",
                 "postcentral.gyr.R","precuneus.R","sup.par.lob.R","mid.temp.gyr.R","mid.occip.gyr.R",
                 "mid.occip.gyr.L","mid.temp.gyr.L","sup.par.lob.L","precuneus.L","post.cent.gyr.L",
                  "precentral.gyr.L","paracent.lob.L","sup.fron.gyr.L","mid.front.gyr.L","cing.gyr.L")
colnames(mat) = rownames(mat)

# Rotate the chord diagram so that the appearance is bihemispheric (left vs. right)
circos.par(gap.after = c(rep(4, nrow(mat)/2-1),20, rep(4, ncol(mat)/2-1), 20))
circos.par(start.degree = 75)

# Data frame initialization 
df = data.frame(from = rep(rownames(X), times  = ncol(X)),
                to = rep(colnames(X), each = nrow(X)),
                value = as.vector(X),
                stringsAsFactors =  FALSE)
# converting the lower triangular to symmetric matrix
X  = X+ t(X) 

# color coding the connectivity values based on the range
rr <-range(colSums(X))
svals <- (colSums(X)-rr[1])/diff(rr)
f <- colorRamp(c("lightyellow","darkred"))
gridColors <- rgb(f(svals)/255)

# Chord diagram settings 
chordDiagram(df, directional = FALSE, grid.col = gridColors,annotationTrack = "grid",big.gap = 20, link.visible = df[[3]]>0.02, preAllocateTracks = list(track.height = max(strwidth(unlist(dimnames(mat))))))

# we go back to the first track and customize sector labels
circos.track(track.index = 1, panel.fun = function(x, y) {
  circos.text(CELL_META$xcenter, CELL_META$ylim[1], CELL_META$sector.index, 
              facing = "clockwise", niceFacing = TRUE, adj = c(0, 0.5), cex= 1.6)
}, bg.border = NA) 

dev.off()
circos.clear()`

**Comment by jokergoo** [comment]
For the color of the links, according to your code, the links have the same color as the "source sector", e.g. the links from "paracent.lob.R" are all dark brown, which is the same as the color for sector "paracent.lob.R".
