### ISSUE TITLE
Fix "partial argument match" warnings

### ISSUE THREAD

**Issue by bersbersbers** [jokergoo/circlize#287]
Using `circlize_0.4.13` and `ComplexHeatmap_2.10.0`, with
```r
options(
  showWarnCalls = TRUE,
  warnPartialMatchArgs = TRUE,
  warnPartialMatchAttr = TRUE,
  warnPartialMatchDollar = TRUE
)
ComplexHeatmap::Heatmap(matrix(c(0, 0, 1, 1), nrow=2))
```

I am getting this
> Warning message:
In seq.default(min(x), max(x), length = 3) :
  partial argument match of 'length' to 'length.out'
Calls: <Anonymous> -> default_col -> colorRamp2 -> seq

I don't quite see where `colorRamp2` uses `seq`, though (https://github.com/jokergoo/circlize/blob/620a1ad899d9db044bde4132c45eb5f2cc582295/R/utils.R).

Then again, this could certainly be fixed here:
https://github.com/jokergoo/circlize/blob/620a1ad899d9db044bde4132c45eb5f2cc582295/R/utils.R#L1196
https://github.com/jokergoo/circlize/blob/620a1ad899d9db044bde4132c45eb5f2cc582295/R/utils.R#L1204
https://github.com/jokergoo/circlize/blob/620a1ad899d9db044bde4132c45eb5f2cc582295/R/utils.R#L1212
https://github.com/jokergoo/circlize/blob/620a1ad899d9db044bde4132c45eb5f2cc582295/R/utils.R#L1220
https://github.com/jokergoo/circlize/blob/feccef4f5f25f0ad389ccb6d3e36a2e6813ad7a8/man/col2value.Rd#L31

Closely related: https://github.com/jokergoo/ComplexHeatmap/issues/781

**Comment by jokergoo** [comment]
Thanks!
