### ISSUE TITLE
y-axis labels wrong alignment when counter-clockwise

### ISSUE THREAD

**Issue by ms-gx** [jokergoo/circlize#289]
If I set `circos.par(start.degree = 90, gap.degree = 25, clock.wise = FALSE, xaxis.clock.wise = FALSE)` the y-axis labels (via `circos.yaxis()`) on my tracks will be aligned wrongly. They seem to be anchored at the right position, but then are aligned right instead of left.

When I had the whole orientation as standard (`clock.wise = TRUE` and `xaxis.clock.wise = TRUE`) everything was fine.

See image.

![y-labels](https://user-images.githubusercontent.com/45788632/141456881-f7a4ae88-fd94-435a-b3bf-5213296b5905.png)

**Comment by jokergoo** [comment]
That might be a bug. Can you also post some example code so that I can test it?

**Comment by ms-gx** [comment]
Sure.

This one looks good:

`
library(circlize)

sector <- rep(1,1000)
pos <- 1:1000
value <- c(1:500,401:900)
df<- data.frame(sector, pos, value)


circos.clear()

circos.par(start.degree = 90, gap.degree = 25, track.height = 0.12)

circos.initialize(df$sector, x = df$pos)

circos.trackHist(df$sector, df$value, bin.size = 1)
circos.yaxis("right", labels.cex = 1.0, at = c(0,2))
circos.axis(sector.index = "1", labels.cex = 1.0, minor.ticks = 0, labels.facing = "inside", labels.niceFacing = FALSE)
  
circos.clear()`

And if I add `clock.wise = FALSE, xaxis.clock.wise = FALSE` then the problem arises:

`sector <- rep(1,1000)
pos <- 1:1000
value <- c(1:500,401:900)
df<- data.frame(sector, pos, value)


circos.clear()

circos.par(start.degree = 90, gap.degree = 25, track.height = 0.12, clock.wise = FALSE, xaxis.clock.wise = FALSE)

circos.initialize(df$sector, x = df$pos)

circos.trackHist(df$sector, df$value, bin.size = 1)
circos.yaxis("right", labels.cex = 1.0, at = c(0,2))
circos.axis(sector.index = "1", labels.cex = 1.0, minor.ticks = 0, labels.facing = "inside", labels.niceFacing = FALSE)

circos.clear()`

**Comment by ms-gx** [comment]
Great, your bugfix works for me. Thanks much!
