### ISSUE TITLE
cannot pass desired `ylim` to `circos.genomicDensity`

### ISSUE THREAD

**Issue by lydiayliu** [jokergoo/circlize#291]
I would like to create two tracks of `circos.genomicDensity` with `count_by = 'number'` that have the same y-axis. I tried to pass in `ylim` to `circos.genomicDensity` and saw that it had no effect. 

Looking into the code it is clear that no matter what `ylim` is inputted, it is overwritten and automatically set to be the `c(0, max(value))` where `value` is from the output of `genomicDensity()` on the single or list of regions provided as input.

```
    if (ylim.force && count_by == "percent") {
        ymax = 1
    }
    else {
        ymax = max(sapply(df, function(gr) max(gr[[4]])))
    }
    if (length(df) == 1) {
        circos.genomicTrackPlotRegion(df[[1]], ylim = c(0, ymax), 
            panel.fun = function(region, value, ...) {
                circos.genomicLines(region, value, col = col, 
                  lwd = lwd, lty = lty, type = type, border = border, 
                  area = area, baseline = baseline)
            }, ...)
    }
    else {
        circos.genomicTrackPlotRegion(df, ylim = c(0, ymax), 
            panel.fun = function(region, value, ...) {
                i = getI(...)
                circos.genomicLines(region, value, col = col[i], 
                  lwd = lwd[i], lty = lty[i], type = type[i], 
                  border = border[i], area = area[i], baseline = baseline[i])
            }, ...)
    }
```

I don't think this feature is clearly explained in the README, and I had to create a modified version of the function that only uses `ylim=c(0, ymax)` if no `ylim` argument has been given.

**Comment by jokergoo** [comment]
You are right. I will make setting of `ylim` more flexible.
