### ISSUE TITLE
Gridlines

### ISSUE THREAD

**Issue by kokyriakidis** [jokergoo/circlize#293]
Hi! 

Is there an easy way to add gridlines to a track that contains barplots?

**Comment by jokergoo** [comment]
No, you need to manually add them with `circos.segments()` or `circos.lines()`, just two more lines of code:

```r
circos.initialize(sectors = letters[1:8], xlim = c(0, 10))
circos.track(ylim = c(0, 10), panel.fun = function(x, y) {
	circos.segments(CELL_META$cell.xlim[1], 0:10, CELL_META$cell.xlim[2], 0:10, col = "grey")
	circos.segments(0:10, CELL_META$cell.ylim[1], 0:10, CELL_META$cell.ylim[2], col = "grey")
})
```

![image](https://user-images.githubusercontent.com/449218/146656637-6d57cd57-85ce-4022-b9d6-d21f6d8bda81.png)

**Comment by kokyriakidis** [comment]
Thank you so much!
