### ISSUE TITLE
chordDiagram error  'scale = TRUE'

### ISSUE THREAD

**Issue by julama** [jokergoo/circlize#294]
hey,

I'm getting an error when using `chordDiagram()` with the parameter `scale=TRUE`

```
Error in rep(small.gap, n_df1 - 1) : invalid 'times' argument
In addition: Warning messages:
1: In max(ind1) : no non-missing arguments to max; returning -Inf
2: In min(ind2) : no non-missing arguments to min; returning Inf
```

The same function call works fine without the `scale` parameter, so it's not clear what is issue here. 

  ```chordDiagram(mat, group = group, big.gap = 20, annotationTrack = "grid", preAllocateTracks = 1, directional = 1, grid.col = grid.col, direction.type = c("diffHeight", "arrows"), link.arr.type = "big.arrow", scale = TRUE)```

The input is a sparse binary matrix. 

Any ideas?

**Comment by jokergoo** [comment]
Can you also send me the object `mat`? `scale` is less used so it is less tested.

**Comment by julama** [comment]
I found a solution. By using the original matrix `mat` instead of the dataframe `df` the error does not occur.
Code to reproduce the error:

```
set.seed(999)
mat = matrix(rbinom(225, 1, 0.1), 15, 15)
rownames(mat) = paste0(range(1,15), 1:15)
colnames(mat) = paste0(range(1,15), 1:15)

df = data.frame(from = rep(rownames(mat), times = ncol(mat)),
    to = rep(colnames(mat), each = nrow(mat)),
    value = as.vector(mat),
    stringsAsFactors = FALSE)

chordDiagram(df, scale=TRUE, big.gap = 20, annotationTrack = "grid", preAllocateTracks = 1, directional = 1, direction.type = c("diffHeight", "arrows"), link.arr.type = "big.arrow")
chordDiagram(df)
```

**Comment by jokergoo** [comment]
I found the reason. In `df` there are many rows having zero in the `value` column. These zero values are automatically removed for matrix, but are not filtered out yet with the data frame as input. If you manually remove rows with zero values, there won't be error any more. I will fix this bug in the next version.

```r
df = df[df[, 3] > 0, ]
chordDiagram(df, scale=TRUE, big.gap = 20, annotationTrack = "grid", preAllocateTracks = 1, directional = 1, direction.type = c("diffHeight", "arrows"), link.arr.type = "big.arrow")
```

![image](https://user-images.githubusercontent.com/449218/152407830-689981ff-7967-46b5-806c-09056b16bafd.png)
