### ISSUE TITLE
Visualize multiple group intersections (similar to a multi group Venn diagram)

### ISSUE THREAD

**Issue by tilofreiwald** [jokergoo/circlize#296]
Hi, 

I was wondering if it is possible to create a chord diagram where each group can intersect with multiple other groups like the red chords in the picture? (We created this one with a tool called Circa)
<img width="200" alt="image" src="https://user-images.githubusercontent.com/3132968/153423332-56a8f75b-f7b3-45a9-90d3-b6a99989ec98.png">
If I define multiple end points for a same start point in the adjacency list for `chordDiagram` it get's split into multiple elements on the circle instead of overlapping chords.
The question is somewhat related to a previous question that was raised: https://github.com/jokergoo/circlize/issues/158

Many thanks
Tilo

**Comment by OliverPStuart** [comment]
I see that this has been listed as completed; are there any instructions yet on how to achieve this for chord diagrams?

**Comment by jokergoo** [comment]
No, haven't done yet...
