### ISSUE TITLE
highlight.sector works weird in a symmetrical matrix base chordDiagram

### ISSUE THREAD

**Issue by xiayh17** [jokergoo/circlize#298]
Here is a minimal example.
```R
library(circlize)
df <- merge(paste0("S", 1:3),paste0("S", 1:3))
df$value <- 1
df <- df[which(!df$x == df$y),]

mat <- reshape2::acast(
  df,x~y
)

chordDiagram(df,symmetric = T)
highlight.sector("S1", col = NA, border = "green",  track.index = 1,
                 lwd = 2, padding = c(0, 0.01, 0, 0.01))
highlight.sector("S2", col = NA, border = "green",  track.index = 1,
                 lwd = 2, padding = c(0, 0.01, 0, 0.01))
circos.clear()
```

I try to maintain a consistent expansion across different sectors, but something wrong happened.
I checked my data, only for my data is a symmetrical matrix like this

```
   S1 S2 S3
S1 NA  1  1
S2  1 NA  1
S3  1  1 NA
```

<img width="684" alt="image" src="https://user-images.githubusercontent.com/17431830/155960838-f9419028-89bc-4ecd-9693-5058d9f638c2.png">

Thank You for your excellent work of `circlize` !

**Comment by jokergoo** [comment]
That was a bug and I have fixed it now.

<img width="895" alt="image" src="https://user-images.githubusercontent.com/449218/158977596-fb67f83c-2a6e-455f-ad24-d3410c204fcc.png">


I added a new feature for controlling `padding`. In the old versions, values in `padding` are the relative proportions of the range on x-axis and y-axis. If you highlight sectors one by one, and when the widths of sectors are different, the padding for different sectors may be different. See the following example:

```r
> df[2, 3] = 10
> df
   x  y value
2 S2 S1     1
3 S3 S1    10
4 S1 S2     1
6 S3 S2     1
7 S1 S3     1
8 S2 S3     1
> set.seed(1234)
> chordDiagram(df,symmetric = T)
highlight.sector("S1", col = "#FF000040", border = "green", track.index = 1,
                 lwd = 2, padding = c(0, 0.1, 0, 0.1))
highlight.sector("S2", col = "#FF000040", border = "green", track.index = 1,
                 lwd = 2, padding = c(0, 0.1, 0, 0.1))
circos.clear()

> highlight.sector("S1", col = "#FF000040", border = "green", track.index = 1,
+                  lwd = 2, padding = c(0, 0.1, 0, 0.1))
> highlight.sector("S2", col = "#FF000040", border = "green", track.index = 1,
+                  lwd = 2, padding = c(0, 0.1, 0, 0.1))
> circos.clear()
```

<img width="862" alt="image" src="https://user-images.githubusercontent.com/449218/158978183-a51f0cc9-8d3f-4ed1-b6f7-49d926cdf452.png">

Now S1 is longer than S2, and if extending the highlight lines by 10% of the correspond sector, the extended line will also be longer for S1 than S2.

Now argument `padding` supports setting the padding **by the absolute values measured in the sectors**. Note, in the sectors, although their widths are different, but the axes are always consistent between sectors, which means the same difference measured by x-axes on different sectors always have the same difference measures in degree on the circle. 

To use this new feature, simply wrap the vector set to `padding` with `I()`:

```r
set.seed(1234)
chordDiagram(df,symmetric = T)
highlight.sector("S1", col = "#FF000040", border = "green", track.index = 1,
                 lwd = 2, padding = I(c(0, 0.2, 0, 0.2)))
highlight.sector("S2", col = "#FF000040", border = "green", track.index = 1,
                 lwd = 2, padding = I(c(0, 0.2, 0, 0.2)))
```

<img width="873" alt="image" src="https://user-images.githubusercontent.com/449218/158979346-7c3f36aa-c36d-4b8e-9b1a-07d460a22d7e.png">

And the expression `padding = I(c(0, 0.2, 0, 0.2))` now means, to extend the left and right sides of the highlighted line by absolute values of 0.2 and 0.2 (S1 has a range 0-13 and S2 has a range 0-4).

**Comment by xiayh17** [comment]
Sorry for replying so late. Many Thanks!
