### ISSUE TITLE
Circos.heatmap not displaying zero values

### ISSUE THREAD

**Issue by Lamm-a** [jokergoo/circlize#299]
I have a wide dataframe of a single row with a binary present absence dataset encoded in 1s and 0s:
```
dim(preMicroCazyme_wide)
[1]    1 1970
```
I am wanting to do this as i will layer several `circos.heatmaps` to show the presence absence in different systems. However the plots just come out all one colour and seemingly ignore the 0 values:

Each of the below have the same dimensions just different profiles of 1s and 0s.
```
cols1 = colorRamp2(c(0, 1), c("white", "blue"))
cols2 = colorRamp2(c(0, 1), c("white", "pink"))

circos.heatmap(preMicroCazyme_wide, cols1 = cols, split = FALSE, cluster = FALSE)
circos.heatmap(wide_termite_cazy, col = cols2, split = FALSE, cluster = FALSE)

# Showing the output is not correct for some reason
length(preMicroCazyme_wide[preMicroCazyme_wide == 0])
[1] 281
> length(wide_termite_cazy[wide_termite_cazy == 0])
[1] 1289
```

Yet the resulting plot looks like this:
![image](https://user-images.githubusercontent.com/49655395/156374431-bfc2fe31-2692-4bae-a68f-d7680a43c74b.png)

This looks like the 0 values are either being ignored or coloured in regardless. Any idea how I can fix this?

**Comment by Lamm-a** [comment]
I had the data frame wide when i needed it to be long `t(my_df)` solved the issue!

**Comment by jokergoo** [comment]
Yes, the matrix should be a "long" matrix.
