### ISSUE TITLE
how  to add labels between two sector index

### ISSUE THREAD

**Issue by Sisov** [jokergoo/circlize#30]
Dear authors:
I am confused about how to add labels between two sector index

**Comment by jokergoo** [comment]
Hi,

Do you mean the figure on the left or on the right?

![test](https://cloud.githubusercontent.com/assets/449218/25170247/24b8e9fa-24ea-11e7-8aac-8471849875a8.png)

You need to install the newest version to run following code:

```{r}
devtools::install_github("jokergoo/circlize")

library(circlize)
par(mfrow = c(1, 2))
circos.par(gap.after = 5)
circos.initialize(letters[1:8], xlim = c(0, 1))
circos.track(ylim = c(0, 1))
circos.info(plot = TRUE)
set.current.cell(sector.index = "g", track.index = 1)
circos.text(CELL_META$cell.xlim[1] - ux(2, "mm"), CELL_META$ycenter,
	        'fooooooo', facing = "clockwise")
circos.clear()

circos.initialize(letters[1:8], xlim = c(0, 1))
circos.track(ylim = c(0, 1), track.height = 0.1, bg.border = NA)
circos.track(ylim = c(0, 1))
highlight.sector(sector.index = c("f", "g"), track.index = 1, 
	text = "fooooooo", col = NA)
circos.clear()
```

**Comment by Sisov** [comment]
![image](https://cloud.githubusercontent.com/assets/22792569/25170987/f42e45ac-251e-11e7-9422-39f0e133e6d8.png) while appear install error ,GlobalOptions' 0.0.11 is loaded and the version 0.0.12 needed,and I try to install GlobalOptions 0.0.12,but can't find it now

**Comment by jokergoo** [comment]
then you can first run:

```
devtools::install_github("jokergoo/GlobalOptions")
```

**Comment by Sisov** [comment]
Yeah, It's works well ,while another problem when we plot the heatmap use your circlize ,Do you think it need to normalization?

**Comment by jokergoo** [comment]
Actually, normalization is related to data processing which is a first step before visualization. Whether to normalize the data depends on what kind of information you want to see. If you want to see relative changes compared to global mean, you may need to scale your data. Or if you have multiple datasets and you want to compare between them, normalization is also necessary.

**Comment by Sisov** [comment]
OK，Thanks,The circlize plot a  beautiful picture
