### ISSUE TITLE
hcl_palette not working in circlize 0.4.14

### ISSUE THREAD

**Issue by lorbaer** [jokergoo/circlize#305]
Hi,
I read your blog https://jokergoo.github.io/2022/03/01/support-hcl-colormaps-in-complexheatmap/ and tried to use the hcl_palette argument.
However even with your sample code I got
`colorRamp2(c(-2, 0, 2), hcl_palette = "Blue-Red 2")`
> Error in colorRamp2(c(-2, 0, 2), hcl_palette = "Blue-Red 2") : 
  unused argument (hcl_palette = "Blue-Red 2")

Session info clearly shows
```
ComplexHeatmap_2.10.0
circlize_0.4.14   
```
deinstalled and reinstalled circlize, but didn't help.
Do github and cran version match?

best

**Comment by jokergoo** [comment]
Now I pushed the update to GitHub. Its version is 0.4.15. You can try with the version from GitHub.

**Comment by lorbaer** [comment]
Thanks,
that's working now.

best
