### ISSUE TITLE
Example Plot Replication .RData files

### ISSUE THREAD

**Issue by Keaan95** [jokergoo/circlize#31]
Dear author,

Thank you for putting together this terrific package.

I've been looking around in github and the documentation book for the .RData file required to build this plot:
http://zuguang.de/circlize/example/otu.html

I was hoping it was still available.

Thanks :)

**Comment by jokergoo** [comment]
Hi, I have deleted one file by accident. Now it is recovered.

**Comment by Keaan95** [comment]
Thanks found it :)
