### ISSUE TITLE
Error: range of `ylim` should be different.

### ISSUE THREAD

**Issue by ShixiangWang** [jokergoo/circlize#312]
Hi @jokergoo, I want to plot some data with frequency value. Sometimes, the values are same, so the circlize return errors, similar to the following example. Is it possible to draw such data? Or should I use another function to do this?

```r
library(circlize)
circos.par("track.height" = 0.1)
circos.initializeWithIdeogram(plotType = NULL)

bed = generateRandomBed(nr = 100)
bed$value1 = 0.1
circos.genomicTrack(bed, panel.fun = function(region, value, ...) {
  circos.genomicLines(region, value, area = TRUE)
})
circos.clear()
```

Best,

Shixiang

**Comment by ShixiangWang** [comment]
I found in such case, I have to set `ylim` by hand.

```
circos.genomicTrack(bed, ylim = c(0, 0.1), panel.fun = function(region, value, ...) {
  circos.genomicLines(region, value, area = TRUE, baseline = 0)
})
```

It works :)

<img width="357" alt="image" src="https://user-images.githubusercontent.com/25057508/165428249-4afe3f9a-1eea-4f90-a4c9-cf10b79abb3f.png">

Maybe post an error `Please set ylim by hand` is more informative than `Error: range of `ylim` should be different.`

**Comment by jokergoo** [comment]
Yes, it will be helpful if a more informative message is printed!
