### ISSUE TITLE
chordDiagram: Color gradients between groups

### ISSUE THREAD

**Issue by LeclercqNico** [jokergoo/circlize#313]
I wonder if there is a possibility to color the links between the different groups with a smooth color gradient of the two groups using the 'chorDiagram function. We set the colors of the groups with the 'grid.col' argument and the colors of the links with the 'col' argument.

I've seen that this is doable in other programs than R but I wonder if anyone could help do that in R. Here is an example of what I am trying to obtain. 
![image](https://user-images.githubusercontent.com/90458471/165522786-4a8ffc6b-1abc-4a03-976e-3920ee63d878.png)

**Comment by jokergoo** [comment]
Unfortunately no. 

What additional information does this color gradient provide from the plot?

**Comment by LeclercqNico** [comment]
Thank you for your response. 
Here, my issue is not to add information using the colors but making it clearer for the readers. My data is the pairwise beta-diversities between regions. Having such gradient would allow to directly see which two regions share the beta-diversity value, in my opinion, in a better way than the directional option in the function. I will deal with this in Illustrator. Thanks.

**Comment by jokergoo** [comment]
OK, I will put it into my to-do list.

**Comment by LeclercqNico** [comment]
Thank you very much! I am sure it would be useful to many.
