### ISSUE TITLE
Add histograms to the circos 

### ISSUE THREAD

**Issue by Sisov** [jokergoo/circlize#32]
Dear authors
I want to add the histogram and density to the circos picture,while it can't work well,the picture like this 
![1](https://cloud.githubusercontent.com/assets/22792569/25344668/62f5f3e8-2945-11e7-9e3a-3c718f465d48.png),and my commands like that :
circos.clear()
circos.par(gap.after=c(rep(3,6),7,rep(3,6),7),start.degree=90)
circos.genomicInitialize(bed1,track.height=0.05)
circos.trackHist(factors = bed2$chr, x = bed3$value, track.height = 0.1, col = "#999999", border = "#999999")

**Comment by jokergoo** [comment]
Hi,

You can check following code.

The first track just plots a normal histogram track for which each bar represents number of regions in an interval while in the second track, the width of the bar corresponds to the width of the genomic region.

```{r}
circos.initializeWithIdeogram()

bed = generateRandomBed(1000)
circos.trackHist(factors = bed$chr, x = (bed$start + bed$end)/2, 
	bin.size = 1e7)

bed = generateRandomBed(100)
circos.genomicTrack(bed, ylim = range(bed[[4]]), 
	panel.fun = function(region, value, ...) {
		circos.genomicRect(region, value, ytop = value[[1]], 
			ybottom = 0, col = ifelse(value[[1]] > 0, "red", "green"))
})
```

![test](https://cloud.githubusercontent.com/assets/449218/25375434/f450f4f4-29a0-11e7-9870-3bc74de702cf.png)

**Comment by Sisov** [comment]
OK,the next questions ,if I want to plot the values histogram density while the values [[i]]>0,how to show it in the picture.
