### ISSUE TITLE
There is no space to allocate sectors.

### ISSUE THREAD

**Issue by syj1997104** [jokergoo/circlize#320]
Hi,
I want to plot Chord diagram and add links between objects. But when I run the code:
 `chordDiagram(interdata,scale = FALSE,col="#F59630")`
there is an error:Maybe your `gap.degree` is too large so that there is no space to allocate sectors.
I guess my dataframe is too large to plot the Chord diagram. The dim of interdata is 15534*4. So I want to know that is there any method to solve this problem?
Thanks!

**Comment by jokergoo** [comment]
I think you have too many categories in your data. Check `length(unique(union(interdata[, 1], interdata[, 2])))`.

**Comment by syj1997104** [comment]
Thank you for replying to me，
It‘s true that I have too many categories in my data, because i want to show interactions between gene fragments， but it seems that I  cannot submit such large data. So how many how many how many classifications it can handle it can handle？
Thanks！

**Comment by jokergoo** [comment]
You need to think this question before making the plot: can I really clearly read the plot if I put so many categories on the plot?

**Comment by syj1997104** [comment]
Thank you! This is a question worth considering, I will find another way to solve my promble. Thanks again！
