### ISSUE TITLE
Plot genome density 

### ISSUE THREAD

**Issue by Sisov** [jokergoo/circlize#33]
Hi jokergoo;
I'm so sorry to trouble you again,can the circlize plot the Gene density like that? using a gradient color plot the Optical marker and gene density
Thanks
Alex
![lz awqp wq c_ _c4442s9f](https://cloud.githubusercontent.com/assets/22792569/25419483/94c47430-2a85-11e7-87e9-b525a56b7a31.png)

**Comment by cjy8709** [comment]
Hi sorry to come back to an old closed thread but I was wondering the same thing of this post. I dug through the manual but couldn't find a good way... I was thinking of drawing rectangles but maybe theres a better way?

**Comment by jokergoo** [comment]
It is basically a one-row heatmap (or one-column, depends how you look). You need to calculate the "density" in advance and then use a color mapping function. See example here: https://jokergoo.github.io/circlize_book/book/high-level-genomic-functions.html#genomic-heatmap
