### ISSUE TITLE
Disable polar coordinate transformation.

### ISSUE THREAD

**Issue by RubD** [jokergoo/circlize#34]
Is there a way to disable the coordinate transformation so that you can see the normal rectangular plotting area? I know this is not the purpose for Circlize, but we would like to make some additional zoomed-in figures where we want the plotting areas not to be curved. I can plot part of a circle, but there is always a small curvature left. In addition, it would then also be an excellent tool to plot genomic (or other kinds of) data in a rectangular format.

Thanks,
Ruben

**Comment by jokergoo** [comment]
Hi Ruben,

I have another package [gtrellis](https://github.com/jokergoo/gtrellis) which makes genomic plot in the regular rectangular coordinates, but I don't know how to combine it with circlize.

**Comment by RubD** [comment]
Hi Zugang,

I’ve never seen your other package before and it looks good, however it does not seem to be able to draw genomic links (arcs) and that’s what we need.

My current hack is to create many segments and then only display / zoom in on the first, if you do that then it’s almost rectangular.
If I have somewhat more time in the future, I might try to find a better solution.

Thanks,
Ruben
