### ISSUE TITLE
reducing gap with set_gap_track issue 

### ISSUE THREAD

**Issue by avnd6** [jokergoo/circlize#340]
Hello,

I am using circlize heatmap and I am trying to reduce gap between two tracks in order to get them as if they were in the same track (I had to separate them because the color function were different for the two). I tried to use the set_gap_track function and succed in increasing the gap, but nothing happen when I try to reduce the gap. Please find, below a reproducible example of my problem (in the example, I want to reduce gap between data dd and data ee

when I am using set_track_gap(cm_h(20)), I obtain this

<img width="639" alt="Capture d’écran 2022-10-06 à 19 49 27" src="https://user-images.githubusercontent.com/115181098/194385001-8fc56990-98b2-4cd8-bb5c-2f7753a71d7c.png">

when I am using set_track_gap(cm_h(0)), I obtain this (
I also tried set_track_gap(cm_h(0.005)) and other small values)

<img width="631" alt="Capture d’écran 2022-10-06 à 19 58 52" src="https://user-images.githubusercontent.com/115181098/194385454-951706f3-ce7c-44e2-9ba0-21f02695ab13.png">

.

`
# data
aa=data.frame(aa=sample(1:50, 35))
bc=data.frame(bb=sample(c("yes", "no"), 35, replace=TRUE), cc=sample(c("yes", "no"), 35, replace = TRUE))
dd=data.frame(dd=sample(1:50, 35))
ee=data.frame(ee=sample(1:50, 35))

# color function
col_aa = colorRamp2(c(1, 25,50), c("grey", "white", "black"))
col_bc = c("yes" = "red", "no" = "blue")
col_dd =colorRamp2(c(1, 25,50), c("pink", "white", "yellow"))
col_ee=colorRamp2(c(1, 25,50), c("orange", "white", "cyan"))

# circle heatmap

circos.par(gap.after = c(5,5,5,5,30))

circos.heatmap(aa, split=split, col = col_aa, track.height = 0.09, cell.border=TRUE,cluster = FALSE, na.col = "white")

circos.track(track.index = get.current.track.index(), panel.fun = function(x, y) {
  if(CELL_META$sector.numeric.index ==5) { # the last sector
    cn = colnames(aa)
    n = length(cn)
    circos.text(rep(CELL_META$cell.xlim[2], n) + convert_x(1, "mm"), 
                1:n - 0.5, cn, 
                cex = 2, adj = c(0, 0.5), facing = "inside")  }
}, bg.border = NA)

circos.heatmap(bc, col = col_bc, track.height = 0.090, cell.border=TRUE,cluster = FALSE, na.col="white")

circos.track(track.index = get.current.track.index(), panel.fun = function(x, y) {
  if(CELL_META$sector.numeric.index ==5) { # the last sector
    cn = colnames(bc)
    n = length(cn)
    circos.text(rep(CELL_META$cell.xlim[2], n) + convert_x(1, "mm"), 
                1:n - 0.5, cn, 
                cex = 2, adj = c(0, 0.5), facing = "inside")  }
}, bg.border = NA)

circos.heatmap(dd, col = col_dd, track.height = 0.045, cell.border=TRUE ,cluster = FALSE, na.col="white")

set_track_gap(cm_h(20))

circos.track(track.index = get.current.track.index(), panel.fun = function(x, y) {
  if(CELL_META$sector.numeric.index ==5) { # the last sector
    cn = colnames(dd)
    n = length(cn)
    circos.text(rep(CELL_META$cell.xlim[2], n) + convert_x(1, "mm"), 
                1:n - 0.5, cn, 
                cex = 2, adj = c(0, 0.5), facing = "inside")  }
}, bg.border = NA)

circos.heatmap(ee, col = col_ee, track.height = 0.045 , cell.border=TRUE, cluster = FALSE, na.col="white")

circos.track(track.index = get.current.track.index(), panel.fun = function(x, y) {
  if(CELL_META$sector.numeric.index ==5) { # the last sector
    cn = colnames(ee)
    n = length(cn)
    circos.text(rep(CELL_META$cell.xlim[2], n) + convert_x(1, "mm"), 
                1:n - 0.5, cn, 
                cex = 2, adj = c(0, 0.5), facing = "inside")  }
}, bg.border = NA)

`

**Comment by avnd6** [comment]
Hello,

Problems solved thanks to a colleague by using set_gap_track with negative value

**Comment by mariazanti** [comment]
Hello. I have the same issue with reducing the gap. What do you mean by using a negative value? because I tried for example setting the parameter to set_track_gap(gap = -0.1)
and I get the error: Error: Track overlaps with previous track.
