### ISSUE TITLE
Track

### ISSUE THREAD

**Issue by medbenamine** [jokergoo/circlize#346]
Hi, 

can you help me to transform the track of RNAseq from IGV to the circular plot. Thanks

**Comment by jokergoo** [comment]
Sorry I cannot help you. The question is too general.

**Comment by medbenamine** [comment]
![Rplot](https://user-images.githubusercontent.com/108426616/198833248-8c5b263b-5278-47a5-951a-8afa14fe66de.png)
![Rplot](https://user-images.githubusercontent.com/108426616/198833251-94ae54f7-3f15-43e5-9d6c-74f377d1a7bc.png)

**Comment by medbenamine** [comment]
![Rplot](https://user-images.githubusercontent.com/108426616/198833272-91eafaba-5b83-4672-9d63-1db452f74d2e.png)
![Picture1](https://user-images.githubusercontent.com/108426616/198833279-83695100-3e63-43d1-b05c-fb41f4ebc8f5.png)

**Comment by medbenamine** [comment]
I want to fill the second track of EGFR in circular lot with the peaks from IGV.
