### ISSUE TITLE
How to add a error bar to circos.barplot?

### ISSUE THREAD

**Issue by liujilei2233** [jokergoo/circlize#361]
Hello,
 I want to add a error bar to ```circos.barplot```.How can I finish it?

Thanks!

**Comment by jokergoo** [comment]
No easy way, you have to add it manually.

**Comment by liujilei2233** [comment]
Yeah,the ```circos.connect```  module could achieve this goal, but it is too complex. So, expect ```circlize``` team to encapsulate this functionality.
Thanks!

**Comment by jokergoo** [comment]
Error bars are basically segments. Let me give you an example:

```r


circos.initialize(letters[1:4], xlim = c(0, 10))
circos.track(ylim = c(0, 1.2), panel.fun = function(x, y) {
    value = runif(10)
    mid = 1:10 - 0.5
    circos.barplot(value, mid, col = 1:10)

    error = value*0.2

    circos.segments(mid, value, mid, value + error)
    circos.segments(mid - 0.1, value + error, mid + 0.1, value + error)
})
circos.clear()
```

<img width="909" alt="image" src="https://user-images.githubusercontent.com/449218/217509573-a606adda-20a7-4462-bbd7-cfa0e98862f0.png">

**Comment by liujilei2233** [comment]
Thanks！It's a simple implementation.
