### ISSUE TITLE
how to change sector character in png firgue 

### ISSUE THREAD

**Issue by mimisikai** [jokergoo/circlize#37]
When I need export into png with high resolution (dpi = 600) as (width = 20, height = 20,res = 600,units = "in"), the labeled character is so small, and sector width is also shrinking. 
How can I fix this problem? 
I have tried par() to adjust but doesn't work at all.

**Comment by jokergoo** [comment]
I think the size of the plot is too huge (20inche x 20inche, which is 12000x12000 in pixels under 600 dpi) which makes it look weird if you look it with zoomed size.

How about first save as a PDF file with normal size and then convert to the high resolution PNG?
