### ISSUE TITLE
Link width in chord diagram of symmetric matrix with diagonal

### ISSUE THREAD

**Issue by knh11545** [jokergoo/circlize#4]
Thank you for providing a great package and for your help!

I stumbled across an issue with a special case of chord diagrams. Links on the diagonal of a symmetric matrix return to the originating segment. The width of the link symbolizes the strength of the relationship. For the returning links this width weighs in doubly on a segment (outbound and inbound). Therefore, these segments as well as the links appear broader than they should. At least to may understanding.

In addition, it would look nicer if a returning chord  would not arch the segment but rather return next to itself basically forming a "hill". Would it be feasible and possible to change the place where the cord returns? I very much like a diagram produced with D3.js where this is done: http://bl.ocks.org/mbostock/1046712

**Comment by jokergoo** [comment]
Thanks! This is an issue that I haven't considered yet.

Following figure is wrong because the width of the self link is calculated twice (e.g. the link coming from sector 'a' and also ending at sector 'a'). The consequence is that the length of the sector 'a' reflect wrongly on how much sector 'a' is interacted with all sectors. 
![wrong](https://cloud.githubusercontent.com/assets/449218/6572193/9426b270-c710-11e4-9836-060769489e72.png)

I made a fixed on this issue. If there is a self-link, the 'hill' will be put at the beginning of the corresponding sector. Now the length of sector 'a' is sum(interactions that come out from 'a') + sum(interactions that end at 'a') + self-interaction
![correct](https://cloud.githubusercontent.com/assets/449218/6572192/9425cdb0-c710-11e4-9cdc-e4e4ff7d70b7.png)

**Comment by knh11545** [comment]
Thank you for the quick fix and improvement to the layout!

I installed the package from github and tested it. It worked fine and as expected when calling `chordDiagram(df4)`. 

However, a bug may have sneaked in. When calling chordDiagram with the option `symmetric = TRUE` I get the error:
```
Error in chordDiagram(df3, symmetric = TRUE) : 
  Is `mat` really a symmetric matrix?
```
Here is some code to test the behaviour.

```R
# Create a chord diagram of a symmetric contingency table
library(circlize)
library(dplyr)

# We have items thare are mapped to subject classes. Every item belongs to 
# one or more classes. 
# Putting it the other way round, classes may share items with other classes 
# this way relating them to these classes. We want to illustrate this
# pairwise relationship as a chord diagram.

# Create a data frame where items are mapped to classes in a 1:n relationship
df1 <- data.frame(item.id = c(1:10, 1:2, 1:3, 1:5), 
                  class = c(letters[1:10], rep("h", 2), rep("i", 3), rep("j", 5)),
                  stringsAsFactors = TRUE)
# Sort by item.id
df1 <- 
  df1 %>%
  arrange(item.id)

# See what we created.
str(df1)
df1

df1 %>% arrange(class)

# View frequency of items in classes
df1 %>% 
  group_by(class) %>%
  summarise(item.count = n())
# or
table(df1$class)

# In a  flat contingency table of items and classes we see again that each item
# belongs to 1:n classes.
ftable(df1)

# Create a contingency table relating classes to classes----------------------------------------------

# Make a self-join relating the classes to classes based on shared items.
# At this stage we have twice as many relationships when class.x != class.y.
# We will get rid of that later in the contingency table.
# In SQL we would have joined on an additional condition "AND class.x >= class.y" 
# or the like. I wouldn't know how to do this here.
df2 <- 
  df1 %>%
  inner_join(df1, by = "item.id")
df2

# View the data ordered by class
arrange(df2, class.x, class.y)

# Create a symmetric contingency table
df3 <- table(df2$class.x, df2$class.y)
df3

# Create chord diagram ----------------------------------------------------

par(mar = c(1, 1, 1, 1))

# This chord diagram looks initially o.k. Unfortunately, the diagonal of the
# matrix is missing. In our case this means that classes (i.e. segments) that
# don't share items with other classes are missing from the diagram. In
# addition, items unique to a class are missing, too.
# 
# An issue with our data might be that we still have to many relationships 
# due to our inperfect joining. See above.
chordDiagram(df3, symmetric = TRUE)
## After the fix we get the error
## Error in chordDiagram(df3, symmetric = TRUE) : 
##   Is `mat` really a symmetric matrix?

# We set the upper triangle of the matrix to 0 (this will remove our
# surplus relationships) and use the default setting symmetric = FALSE. 
# 
# Now all classes are present. Also items unique to
# a class are present as a link/chord returning to the same class (segment).
# Here the fix yields exactly the result we wanted to have!
df4 <- df3
df4[upper.tri(df4)] <- 0
df4
chordDiagram(df4)

```

**Comment by jokergoo** [comment]
Basically I fixed the bug. Also I added a new argument `keep.diagonal` in `chordDiagram()`.

```{r}
chordDiagram(df3, symmetric=TRUE, keep.diagonal=TRUE)
```

which is the same as

```{r}
chordDiagram(df4)
```

**Comment by knh11545** [comment]
Great, works nicely!
Thank you again.
