### ISSUE TITLE
How to create a link with color half gray and half yellow?

### ISSUE THREAD

**Issue by ajing** [jokergoo/circlize#40]
I try to add more colors to the col attribute, but that doesn't seem to work. Is that possible to create a link with color yellow from the source and gradually change to gray?

![image](https://user-images.githubusercontent.com/1566338/27528686-5dabfce2-5a06-11e7-8d56-e0f887ddf926.png)

**Comment by jokergoo** [comment]
Sorry, it is not possible to do it in circlize.

**Comment by ajing** [comment]
Is that possible to modify circos.link() function to make it possible?

**Comment by jokergoo** [comment]
No, I think it is difficult.
