### ISSUE TITLE
circos.genomicLabels, Label position issue

### ISSUE THREAD

**Issue by xtmgah** [jokergoo/circlize#42]
Hello, I am try to plot a simple circos plot with few genes labeled on each chrome. I am trying the circos.genomicLabels(), but the lines are almost overlap and there should be enough space between each label lines.. Could you let me know how to fix this. Here is the method for circos.genomicLabels(): 

circos.genomicLabels(bed_gene, labels.column = 4, side = "outside",col=bed_gene_col,cex = 0.5)

Thanks so much. 
[test_fusion.pdf](https://github.com/jokergoo/circlize/files/1152936/test_fusion.pdf)

**Comment by jokergoo** [comment]
That might be a bug because it is a new function I added to the package. Can you send me the value of `bed_gene`?

**Comment by xtmgah** [comment]
Sure. Here is the bed file. If i selected top 12 row, it's working perfect, but add more will mess up... 
[tmp.bed.zip](https://github.com/jokergoo/circlize/files/1153697/tmp.bed.zip)


Please help to fix this as soon possible... I am waiting for this submit our manuscript. Thanks. We will cited circlize paper... I like this package so much...

**Comment by jokergoo** [comment]
A quick fix without updating the package is as follows:

```
od = order(as.numeric(gsub("chr", "", bed_gene[[1]])))
circos.genomicLabels(bed_gene[od, ], labels.column = 4, side = "outside", cex = 0.5)
```

The reason the order of chromosomes in `bed_gene` is not same as the order on the plot, so currently you need to manually adjusted it, but in the future this should be automatic.

**Comment by xtmgah** [comment]
working perfect. Thanks so much...
