### ISSUE TITLE
What does circos.genomicDensity function plot?

### ISSUE THREAD

**Issue by Anupriya014** [jokergoo/circlize#43]
Hello all,

I'm new to circos plots. Recently, I've been trying to plot fold enrichment of peaks I got from Chip-seq data. My peak file looks like a BED file. When I give this file to circos.genomicDensity function it gives me peaks plot, But what does these peaks represent? In manual it says "genomic density track". I don't know what's that ..

Please help me out. Can I use circlize for plotting Fold enrichment of Chip-seq data?

Thank you.

Best,
Anupriya

My file: 
seqnames	start	end	width	strand	length	pileup	X.log10.pvalue.	fold_enrichment	X.log10.qvalue.
Chromosome	161	3260	3100	*	3101	439.26	8.57279	1.31034	6.89738
Chromosome	4351	6741	2391	*	2392	521.45	6.97062	1.24202	5.44819
Chromosome	7841	11754	3914	*	3915	525.47	7.98465	1.25315	6.42158
Chromosome	14344	16848	2505	*	2506	460.84	5.40914	1.22931	3.99265
Chromosome	22050	22541	492	*	493	381.45	2.35655	1.14413	1.3518
Chromosome	27196	28557	1362	*	1363	382.71	2.45203	1.14792	1.43171
Chromosome	29741	31278	1538	*	1539	392.39	3.2509	1.17687	2.11031
Chromosome	32860	33309	450	*	451	390.46	2.84085	1.16303	1.75883
Chromosome	36419	39678	3260	*	3261	434.3	4.054	1.19718	2.79769

**Comment by jokergoo** [comment]
The `circos.genomicDensity()` function splits the genome by windows with a certain size and calculates how much each window is overlapped by the input regions (so kind like density distribution of input regions). Basically when you see a peak in that track, it means there are more regions in that area compared to other areas in the genome, so in your chipseq data, a peak means there are more regions with significant fold change of chipseq signals.

**Comment by Anupriya014** [comment]
Thank you for the reply.
If there a way I can plot just fold enrichment column for the position I have in BED file across the whole genome? With any other function?

**Comment by jokergoo** [comment]
Something like track C in http://zuguang.de/circlize_book/book/modes-of-input.html#fig:genomic-application-lines or track D in http://zuguang.de/circlize_book/book/modes-of-input.html#fig:genomic-application-rect?

**Comment by Anupriya014** [comment]
Both are useful to me. In track D, I can show sample on upside & control on downside & in track C, I can get much resolution if peaks are many. How can I get full circle instead of segment ?

**Comment by jokergoo** [comment]
The code which adds tracks are independent to how many chromosomes you have. Try following code:

```{r}
bed = generateRandomBed(1000, fun = runif)
circos.initializeWithIdeogram()
circos.genomicTrack(bed, 
    panel.fun = function(region, value, ...) {
        circos.genomicLines(region, value, type = "h")
})
bed = generateRandomBed(1000, fun = rnorm)
circos.genomicTrack(bed, 
    panel.fun = function(region, value, ...) {
        circos.genomicLines(region, value, type = "h", baseline = 0,
        	col = ifelse(value > 0, "red", "blue"))
})
```

![image](https://user-images.githubusercontent.com/449218/28438611-09deb9e0-6d9f-11e7-8c17-e82a0282dbc7.png)

**Comment by Anupriya014** [comment]
Thank you so much! I used following commands : 

bed_file2 = read.csv("/trial/chipseq_trial/uniq.bed", header = TRUE, sep = "\t")  #Example BED file is shown in previous comments.
annoData <- genes(txdb)
annoData1 <- as.data.frame(annoData)

value <- bed_file2[4]
region <- bed_file2[,2:3]
pdf(file="/trial/chipseq_trial/circos_unique_list.pdf",width=10,height=10)  
par(mar = c(1, 1, 1, 1))
circos.genomicInitialize(annoData1)
circos.genomicTrack(bed_file2, numeric.column = 4,
    panel.fun = function(region, value, ...) {
        circos.genomicLines(region, value, type = "h", numeric.column = 1, col =c("#008000"))
})
legend("bottomright", legend = c("trial"), col=c("#008000"), cex = 1.5, fill = c("#008000"))
title("trial_circos")

dev.off()

I got this image : 
![imipramin-treated_circos_unique_list](https://user-images.githubusercontent.com/24602680/28450249-b68c585a-6e03-11e7-82d5-760084466562.jpg)

So this plot is finally showing fold change?

Regards,
Anupriya

**Comment by jokergoo** [comment]
Yes. Since you only have one chromosome, you can also increase the gap (at around theta = 0) a little bit and add a y-axis there. You can refer to following link:

http://zuguang.de/circlize_book/book/graphics.html#fig:circlize-yaxis

**Comment by Anupriya014** [comment]
Thank you so much for solving my problem . Now it's perfect!
