### ISSUE TITLE
species='hg38'

### ISSUE THREAD

**Issue by Ahhgust** [jokergoo/circlize#46]
Hi!
When I try:
circos.initializeWithIdeogram(species='hg38')
I get:
Error in stop_wrap("Maybe your `gap.degree` is too large so that there is no space to allocate sectors.") : 
  Maybe your `gap.degree` is too large so that there is no
space to allocate sectors.

I'm not entirely sure what the issue is (it sounds like it's grabbing the file from UCSC), but it might be nice if this worked (right out the box that is).
Thank you!
-August

**Comment by jokergoo** [comment]
This is because there are too many chromosomes which are not autosomes or sex chromosomes. You can try `read.cytoband(species = "hg38")` which is used internally by `circos.initializeWithIdeogram()`.

To solve this problemn you can set `chromosome.index` argument in the function.

```
circos.initializeWithIdeogram(species='hg38', chromosome.index = paste0("chr", c(1:22, "X", "Y"))）
```

**Comment by endrebak** [comment]
How about adding that to the error message so people do not have to google it? Or create a special rule for hg38, it is becoming more and more common to use.

Anyways, thanks for the great package :) !

**Comment by jokergoo** [comment]
Now I manually select chromosomes for the commonly used genomes:

https://github.com/jokergoo/circlize/blob/f4d93ac884a989df1fc4ca6a16d5647ac944c59c/R/genomic_utils.R#L216-L229
