### ISSUE TITLE
genomicHeatmap bug when plotting 1 column

### ISSUE THREAD

**Issue by Ahhgust** [jokergoo/circlize#47]
It looks like there's a bug when you try and make a genomic heatmap from a 4-columns bed file.
Works fine:
col_fun = colorRamp2(c(-1, 0, 1), c("green", "black", "red"))
bed <- generateRandomBed(100, 2)
circos.initializeWithIdeogram()
circos.genomicHeatmap(bed, col=col_fun, side='inside', border='white')

Breaks:
col_fun = colorRamp2(c(-1, 0, 1), c("green", "black", "red"))
bed <- generateRandomBed(100, 1)
circos.initializeWithIdeogram()
circos.genomicHeatmap(bed, col=col_fun, side='inside', border='white')

With error message:
Error in apply(mat, 2, "is.numeric") : dim(X) must have a positive length

-August

**Comment by jokergoo** [comment]
Hi August,

I forgot to add `drop = FALSE` when subsetting matrix columns somewhere in the code. Now I have updated it. 

Thanks!
