### ISSUE TITLE
[FR] Add text to links 

### ISSUE THREAD

**Issue by pank** [jokergoo/circlize#5]
Hi,

For some types of chart it would be useful to have text associated with an edge, say the *value* of the edge.  I did not find a way to do this using `circlize`/`ChordDiagram`.  While this is to some extend visible through the graph, sometimes making it explicit is better (in particular with arrows).

Thanks,
Rasmus

**Comment by jokergoo** [comment]
Hi, thanks for the suggestion. Can you provides some examples to explain what exactly the "associated text" is? If it is about the value of the edge, is it something like axis? (but axis is already supported in the package). Or is it kind of annotation text (or other graphical marks) which can be added to the plot to explain what the specific part in the plot is?

**Comment by pank** [comment]
Zuguang Gu <notifications@github.com> writes:

> Hi, thanks for the suggestion. Can you provides some examples to
> explain what exactly the "associated text" is? If it is about the
> value of the edge, is it something like axis? (but axis is already
> supported in the package). Or is it kind of annotation text (or other
> graphical marks) which can be added to the plot to explain what the
> specific part in the plot is?

I'd imagine a text along the path, potentially at position zero (the root)
or one (the end).  In the terminology above it would be an annotation
relevant to a specific path.  It could be the numerical value.  In a "time
series network" it could be the change in the value of the edge compared
to the last instance of the network.

Thanks for working on this package!

Rasmus

-- 
Slaa Patienten ihjel, saa siger Feberen Pas

**Comment by jokergoo** [comment]
I see, you mean you want to add some associated text to explain the link (e.g. the value the link represents)?
By default, for `chordDiagram()`, there are axes on the outside of the circle, and the value of the link can be interpreted from the value on the axis. But if you really want to add text on the link, I guess it would be difficult because it is not easy to provide the position of the all links to users.

**Comment by pank** [comment]
Hi,

I was more thinking in line of providing a data.frame with links and
texts.  E.g.

     Link, label, pos [optional]
     A->B, label, .5

But it would anyway only work when the number of edges is very limited, so
it's perhaps not so interesting...

Rasmus

-- 
Got mashed potatoes. Ain't got no T-Bone. No T-Bone

**Comment by jokergoo** [comment]
Also it is difficult to design an API for adding the labels. I mean, the structure for the input data is not the case, but a friendly API for putting the labels along with the link is not easy.

**Comment by pank** [comment]
> Also it is difficult to design an API for adding the labels. I mean,
> the structure for the input data is not the case, but a friendly API
> for putting the labels along with the link is not easy.

Perhaps I’m misunderstanding, but something along the lines of this seems
rather friendly:

```{r}
data.frame("from" = ·,
           "to" = ·,
           "label" = ·,
           "pos " = ·)
```

Anyway, I don't think such a feature should be high priority.
