### ISSUE TITLE
changing ticklabels in genomicInitialize

### ISSUE THREAD

**Issue by MichelMoser** [jokergoo/circlize#57]
Hello, 
Great tool you got here!! 
I just stared with circlize and would like to use it to visualize 2 genetic maps against each other. 
 
Is it possible to change labels in genomic tracks from default basepairs to something other (centiMorgans, genetic distance for example). What would be the parameters to do that?

And is there the possiblity to add vertical lines at each position of a marker along the x axis? 
Similar to the circos picture shown here? 

![image](https://user-images.githubusercontent.com/4695665/32284034-4373f34a-bf26-11e7-8c46-c07c4e3b0555.png)

Thank you very much, 
Michel

**Comment by jokergoo** [comment]
Hi Michel,

Yes, you can add and customize the axes by `circos.axis()` and `circos.lines()` to add vertical (radical) lines if you know the positions of these lines.

**Comment by MichelMoser** [comment]
thank you
