### ISSUE TITLE
Option to have zero on x-axis plotted without adjustment as in older pacakge versions.

### ISSUE THREAD

**Issue by gjabel** [jokergoo/circlize#59]
https://github.com/jokergoo/circlize/blob/676a157a07b83210e01ac382ca5d1cca88f6774c/R/plot.R#L1341

I have noticed in recent versions that the zero labels on the x-axis are shifted away from the zero-tick. For most of my plots it looks strange and can lead to a misreading of the value. Is there a way to override this behavior when using `circos.axis`?

![image](https://user-images.githubusercontent.com/2735201/32590989-2e067ef0-c558-11e7-809d-ae3eefdc5734.png)

**Comment by jokergoo** [comment]
I am wondering why you have such a large space in front of "0". Normally "0" should be aligned to the first tick to its left. You can see it in following plot:

<img width="119" alt="screen shot 2017-11-09 at 10 59 48" src="https://user-images.githubusercontent.com/449218/32599510-0ec049d8-c53d-11e7-9883-a4cb947a3ee6.png">

However, if you want "0" to be placed right at the first tick, you can do as follows:

```
devtools::install_github("jokergoo/circlize")
chordDiagram(mat, annotationTrack = c("name", "grid"))
circos.track(track.index = 2, panel.fun = function(x, y) {
    circos.axis(labels.cex = 0.6, labels.pos.adjust = FALSE)
})
```
