### ISSUE TITLE
Is there a genomic trackHist function?

### ISSUE THREAD

**Issue by dhb2128** [jokergoo/circlize#61]
Hi,

Great package! Similar to the example, I'm plotting a nested genomic plot. I divide the chromosomes up into gene families and then for each gene in each family, I'm plotting the log10 number of cells that express it. 

```
f1 = function() {
  circos.par(gap.after = 2, start.degree = 90)
  circos.initializeWithIdeogram(chromosome.index = chr_idx, 
                                plotType = c("ideogram", "labels"), ideogram.height = 0.03)
}

f2 = function() {
  circos.par(cell.padding = c(0, 0, 0, 0), gap.after = c(rep(2, nrow(chromBound)-1), 10))
  circos.genomicInitialize(chromBound, plotType = NULL)
  circos.genomicTrack(df_bed, ylim = c(0, 3), 
                      panel.fun = function(region, value, ...) {
                        for(h in seq(0, 3, by = 1)) {
                          circos.lines(CELL_META$cell.xlim, c(h, h), lty = 3, col = "#AAAAAA")
                        }
                        circos.genomicPoints(region, value, pch = 16, cex = 0.5)
                      },
                      bg.col = chr_bg_color[chromBound$chr], track.margin = c(0.02, 0))
  circos.yaxis(side = "left", at = seq(0, 3, by = 1), 
               sector.index = get.all.sector.index()[1], labels.cex = 0.4)
  circos.track(ylim = c(0, 1), track.height = uh(2, "mm"), 
               bg.col = add_transparency(chr_bg_color[chromBound$chr], 0))
}

circos.clear()
circos.nested(f1, f2, corresp, connection_col = chr_bg_color[corresp[[1]]])
```
df_bed is a dataframe with the gene family (the f2 sector names), start and end of each gene, and value = number of cells expressing it
chromBound has the chromosome locations (chrN) and start/end of each gene family (the sectors in f2)

Is there a good way to also add a track with a histogram summarizing the distribution of numCells for each sector in f2? I know there's a genomic density, but that summarizes genome occupancy, which is not what I want. I.e. is there an equivalent of trackHist or way to make trackHist work for this genomic plot?

Thanks!

**Comment by jokergoo** [comment]
You can directly use `circos.genomicRect()`. One example is track D in figure 10.3 in following link:

http://zuguang.de/circlize_book/book/modes-of-input.html#fig:genomic-application-rect

**Comment by dhb2128** [comment]
Hi,

I don't think that's what I'm looking for. It looks like genomicRect still takes in a genomic region. Instead, what I'd like to do is summarize the distribution of genomicPoints in each sector (with a histogram or density plot) using something like trackHist. Is that possible?

**Comment by jokergoo** [comment]
I see. Then you need to calculate the "density" manually and add to the plot by `circos.lines()` function with `area = TRUE`:

```{r}
circos.genomicTrack(..., panel.fun = function(region, value, ...) {
    # calculate density
    circos.lines(x, y, area = TRUE)  # this draws polygons
})
```
