### ISSUE TITLE
rename sectors and 

### ISSUE THREAD

**Issue by MichelMoser** [jokergoo/circlize#64]
Hi, 

Could you tell me how to rename sector names to other than initially set indexes? 
I cant figure out how to handle the "labels" option in circos.text()

i would like to replace "1", "2", "3", "4", "5", "6", "7", "14", "13", "12","11","10","9","8" with  "f2_1" "f2_2" "f2_3" "f2_4" "f2_5" "f2_6" "f2_7" "f7_1" "f7_2" "f7_3" "f7_4" "f7_5" "f7_6" "f7_7"

Right now, it just plots the first item to all of the sectors. 

Another question: 
Is it possible to fill the area under the trackHist density curves? i know the option exists for lines and genomicDensity but could not find it in trackHist. 

Thank you, 

Michel

plot: 
![image](https://user-images.githubusercontent.com/4695665/33008162-4255b9f2-cdd2-11e7-8a89-397f78ef2666.png)

 
code: 

```R
circos.clear()
circos.par("track.height" = 0.1, "gap.degree" = c(rep(4, 6), 10,rep(4, 6),10), start.degree = 90)

fa = c("1", "2", "3", "4", "5", "6", "7", "14", "13", "12","11","10","9","8")

markerbedr1$chrom = factor(markerbedr1$chrom, levels = fa)

circos.initialize(factors = markerbedr1$chrom, x = markerbedr1$V2)

circos.track(factors = markerbedr1$chrom, ylim = c(0,1),
             panel.fun = function(x, y) {
               circos.text(labels = markerbedr1$map, 
                           CELL_META$xcenter, 
                           CELL_META$cell.ylim[2] + 
                             uy(8, "mm"), 
                           CELL_META$sector.index)
               breaks = seq(0, 80, by = 20)
               
               circos.axis(labels.facing = "clockwise", labels.cex = 0.4, minor.ticks = 10, 
                           major.at = breaks, labels = paste0(breaks, " cM"))
             })


#circos.trackText(factors = markerbedr1$chrom, x = CELL_META$center, labels = markerbedr1$map)


circos.trackLines(markerbedr1$chrom, markerbedr1$V3, 
                  rep(1, length(markerbedr1$chrom)), type = "h") 
circos.trackHist(factors = markerbedr1$chrom, x = markerbedr1$V2, draw.density = TRUE, 
                 col = "#999999", border = "#999999")


```

**Comment by jokergoo** [comment]
By default the label for sector in the "sector index" encoded in the first column of `markerbedr1`, but it can be changed to any other labels and put it to `circos.text()`. For your code, you can do as:

```{r}
circos.track(ylim = c(0,1),
             panel.fun = function(x, y) {
               circos.text(labels = gsub("^f\\d_", "", CELL_META$sector.index), 
                           CELL_META$xcenter, 
                           CELL_META$cell.ylim[2] + 
                             uy(8, "mm"), 
                           CELL_META$sector.index)
               breaks = seq(0, 80, by = 20)
               
               circos.axis(labels.facing = "clockwise", labels.cex = 0.4, minor.ticks = 10, 
                           major.at = breaks, labels = paste0(breaks, " cM"))
             })
```

For the filled color under the density lines, I didn't expect there will be people using `circos.trackHist()` function. Now I have added an `area` argument `circos.trackHist()` function. You can update the package to use it:

```{r}
devtools::install_github("jokergoo/circlize")
```

**Comment by MichelMoser** [comment]
thank you so much! 
Amazing!
