### ISSUE TITLE
gene name overlap

### ISSUE THREAD

**Issue by Sisov** [jokergoo/circlize#66]
Hi, jokergoo
I want to  plot some specific genes around the genomic,but some labels overlapped ,did they have any solution to solve it

Thanks
Alex

**Comment by jokergoo** [comment]
Can you attach the plot?

**Comment by Sisov** [comment]
Hi,jokergoo
like this
![1](https://user-images.githubusercontent.com/22792569/33584986-f9bfd688-d99c-11e7-8c9a-f199ed308268.png)
The code is that:
circos.clear()
circos.genomicInitialize(bed1,plotType=NULL)
posTransform.fun = function(region) {
    return(region)
}

circos.genomicTrackPlotRegion(bed3, ylim = c(0, 1), panel.fun = function(region, value, ...) {
    circos.genomicText(region, value, y = 0, labels.column = 1, facing = "clockwise", adj = c(0, 0.5), cex = 0.5, posTransform = posTransform.fun)
	 }, track.height = 0.1, bg.border = NA)

circos.genomicPosTransformLines(bed3, posTransform = posTransform.fun, track.height = 0.1, col =rainbow(15) ,horizontalLine="top")
circos.track(ylim = c(0, 1), panel.fun = function(x, y) {
    chr = CELL_META$sector.index
    xlim = CELL_META$xlim
    ylim = CELL_META$ylim
    circos.rect(xlim[1], 0, xlim[2], 1, col = rand_color(1))
    circos.text(mean(xlim), mean(ylim), chr, cex = 0.7, col = "white",
        facing = "inside", niceFacing = TRUE)
}, track.height = 0.1, bg.border = NA)

**Comment by jokergoo** [comment]
Can you use the newest version of this package? In the new package, there is a new `circos.genomicLabels()` function which does it smarter. Check following link:

http://zuguang.de/circlize_book/book/high-level-genomic-functions.html#labels

**Comment by Sisov** [comment]
OK，I will try
