### ISSUE TITLE
Anti-clockwise arrow not supported?

### ISSUE THREAD

**Issue by shenwei356** [jokergoo/circlize#68]
Dear Zuguang, 

Thanks for developing such a great package!

I just find anti-clockwise arrow not supported without such an option for `circos.arrow`,
and I tried exchange values of x1 and x2 but still failed. 

Best regards,
Wei

**Comment by jokergoo** [comment]
It seems in current version it is forced to be clockwise although I cannot remember why I did so. I will go through the source code and support reverse clockwise arrows.

**Comment by jokergoo** [comment]
Hi, I just figured it out. You can set `arrow.position = "start"` to get the arrows in reversed direction.

```{r}
par(mfrow = c(1, 2))
circos.initialize(letters[1:4], xlim = c(0, 1))
circos.track(ylim = c(0, 1), panel.fun = function(x, y) {
	circos.arrow(0, 1, y = 0.5, width = 0.4, arrow.head.length = ux(1, "cm"), 
		col = "red", tail = ifelse(CELL_META$sector.index %in% c("a", "c"), 
			"point", "normal"))
}, bg.border = NA, track.height = 0.4)

circos.initialize(letters[1:4], xlim = c(0, 1))
circos.track(ylim = c(0, 1), panel.fun = function(x, y) {
	circos.arrow(0, 1, y = 0.5, width = 0.4, arrow.head.length = ux(1, "cm"), 
		arrow.position = "start",
		col = "red", tail = ifelse(CELL_META$sector.index %in% c("a", "c"), 
			"point", "normal"))
}, bg.border = NA, track.height = 0.4)
```

**Comment by shenwei356** [comment]
Great, thank you so much!

So the default value of option `arrow.position` is `"end"`.
