### ISSUE TITLE
[FR] group of sectors

### ISSUE THREAD

**Issue by pank** [jokergoo/circlize#7]
Hi,

It may be that I have not understood the purpose of circlize, if so just close this bug.

I would like to organize my sectors by "meta sectors".  Consider figure 10B in the excellent "Visualize relations by Chord diagram" vignette.  I would like to group together `E1` to `E6`.  They will be part of a group `G_E`.  I would like visualize this by adding an outer arc going from 0 to 180 degrees wit the label `G_E`.  From the "intro to circlize" it's clearly possible, to have outer circles, but I couldn't understand if it's possible to also to have different "span" for outer circles.

Thanks,
Rasmus

**Comment by jokergoo** [comment]
You may try `highlight.sector()` to highlight several sectors which are close to each other. You can follow following steps:

1. allocate an empty track in which the "long arc" will be put by `preAllocateTracks` in `chordDiagram()`
2. adjust your matrix/list which contains the data or set `order` in `chordDiagram()` to put groups that you want to highlight together
3. use `highlight.sector()` to highlight more than one sectors.

You can try following example:

```
mat = matrix(rnorm(36), 6, 6)
rownames(mat) = letters[1:6]
colnames(mat) = LETTERS[1:6]
chordDiagram(mat, preAllocateTracks = list(track.height = 0.05))
highlight.sector(sector.index = c("a", "b", "c"), track.index = 1)
```

**Comment by pank** [comment]
Hi Zuguang,

Zuguang Gu <notifications@github.com> writes:

> You may try `highlight.sector()` to highlight several sectors which
> are close to each other. You can follow following steps:
>
> 1. allocate an empty track in which the "long arc" will be put by `preAllocateTracks` in `chordDiagram()`
> 2. adjust your matrix/list which contains the data or set `order` in
> `chordDiagram()` to put groups that you want to highlight together
> 3. use `highlight.sector()` to highlight more than one sectors.
>
> You can try following example:
>
> ```
> mat = matrix(rnorm(36), 6, 6)
> rownames(mat) = letters[1:6]
> colnames(mat) = LETTERS[1:6]
> chordDiagram(mat, preAllocateTracks = list(track.height = 0.05))
> highlight.sector(sector.index = c("a", "b", "c"), track.index = 1)
> ```

That is a very cool example!  I think I will be able to utilize this.

Thanks,
Rasmus

-- 
Bang bang
