### ISSUE TITLE
circos.genomicDensity in stack mode

### ISSUE THREAD

**Issue by rg-code** [jokergoo/circlize#71]
I am trying to create a circlize plot using circos.genomicDensity in stack mode, 

My bed files look like this - 

```
bed1
chr   start          stop
chr1 36026611 36026612
chr1 155102388 155102389
......

&

bed2
chr   start          stop
chr6 30458601 30458602
chr8 44310445 44310446
....
```

I have tried 
```
circos.initializeWithIdeogram(chromosome.index = paste0("chr", c(1:22, "X", "Y")))
bed_list <-list(hyper, hypo)
circos.genomicTrack(bed_list, stack = TRUE,
                    panel.fun = function(region, value, ...) {
                        i = getI(...)
                        circos.genomicDensity(region,value, col = c("#FF000080"), track.height = 0.1)
                        circos.genomicDensity(region, value, col = c("#0000FF80"), track.height = 0.1)
                    })
```
while produces a plot but this is not stacked.

```
circos.initializeWithIdeogram()
bed_list <-list(hyper, hypo)
circos.genomicDensity(bed_list[[1]], type= "h",col = c("#FF000080"), track.height = 0.1)
circos.genomicDensity(bed_list[[2]], type= "h",col = c("#0000FF80"), track.height = 0.1)
```

I am trying to get hyper and hyper both beds in one track ( example [here](https://user-images.githubusercontent.com/449218/28438611-09deb9e0-6d9f-11e7-8c17-e82a0282dbc7.png))

Any help would be appreciated.

**Comment by jokergoo** [comment]
You can just put `bed_list` in `circos.genomicDensity()` function. It will put two density plots into one track.

```{r}
circos.genomicDensity(bed_list, type= "h", col = c("#FF000080", "#00FF0080"), track.height = 0.1)
```

But I would not suggest to do so because hyper-DMRs and hypo-DMRs have different density distributions and one would be too much lower than the other.

**Comment by rg-code** [comment]
Thanks, this is very helpful and as you said since the density distribution of hypo is lower than hyper DMR it is not a very meaningful plot. 

Maybe I wasn't clear enough but I am trying to make a plot similar to this one [(here)](https://user-images.githubusercontent.com/449218/28438611-09deb9e0-6d9f-11e7-8c17-e82a0282dbc7.png) where hyper and hypo-DMR still share same track and are not overlayed.

Is this possible with `circos.genomicDensity` funtion ?

**Comment by jokergoo** [comment]
In the plot you mentioned, actually it is not genomic density plot, it is just a barplot where height of bars correspond to the methylation difference. Check following example where the fourth column in the two data frames are simulated methylation difference:

```{r}
hyper = generateRandomBed(nr = 1000, fun = runif)
hypo = generateRandomBed(nr = 1000, fun = runif)
hypo[[4]] = -hypo[[4]]

circos.initializeWithIdeogram()
circos.genomicTrack(list(hyper, hypo), panel.fun = function(region, value, ...) {
	i = getI(...)
	circos.genomicLines(region, value, baseline = 0, type = "h", col = ifelse(i == 1, "red", "blue"))
})
circos.clear()
```

**Comment by rg-code** [comment]
That's really helpful, thanks a lot. Please mark this as closed.

**Comment by RajneeshSrivastava** [comment]
> In the plot you mentioned, actually it is not genomic density plot, it is just a barplot where height of bars correspond to the methylation difference. Check following example where the fourth column in the two data frames are simulated methylation difference:
> 
> ```
> hyper = generateRandomBed(nr = 1000, fun = runif)
> hypo = generateRandomBed(nr = 1000, fun = runif)
> hypo[[4]] = -hypo[[4]]
> 
> circos.initializeWithIdeogram()
> circos.genomicTrack(list(hyper, hypo), panel.fun = function(region, value, ...) {
> 	i = getI(...)
> 	circos.genomicLines(region, value, baseline = 0, type = "h", col = ifelse(i == 1, "red", "blue"))
> })
> circos.clear()
> ```

Is it possible to do with circos.genomicDensity?
Like dataA and B **densities** stacked but inversed in the same plot - 

Something which can be drawn with the two densities in one track
```
circos.genomicDensity(bed_list, col = c("#FF000080", "#0000FF80"), track.height = 0.2)
```
...something additional with inversely stacked on the track
