### ISSUE TITLE
Sector Labels plotting

### ISSUE THREAD

**Issue by matteoLorenzini** [jokergoo/circlize#74]
I'm using CIRCLIZE library in order to visualize SPARQL output but the sectors labels (corresponding to the entities and predicates URIs) are going outside the plotting region.

Is there any parameters to fix it? Here the code and a snapshot from the picture

`library(circlize)
library(SPARQL)

endpoint <- "https://virtuoso.parthenos.d4science.org/sparql"

#Enumerate classes linked from a given class and predicates that link instances of the given class and the target classes.

q <- " 
SELECT ?p ?c (COUNT(?p) AS ?pc) {
  ?f a <http://parthenos.d4science.org/CRMext/CRMpe.rdfs/PE13_Software_Computing_E-Service> .
  ?t a ?c .
  ?f ?p ?t .
  FILTER(?c != owl:Class)
} GROUP BY ?p ?c

  "

res <- SPARQL(url=endpoint, q)$results
 
chordDiagram(res, annotationTrack = c("grid", "axis"), preAllocateTracks = list(track.height = 0.3)) 
circos.trackPlotRegion(track.index = 1, panel.fun = function(x, y) {
xlim = get.cell.meta.data("xlim")
ylim = get.cell.meta.data("ylim")
sector.name = get.cell.meta.data("sector.index") 
circos.text(mean(xlim), ylim[1], sector.name, facing = "clockwise",
niceFacing = TRUE, adj = c(0, 0.5)) }, bg.border = NA)

`

[Rplots.pdf](https://github.com/jokergoo/circlize/files/1847495/Rplots.pdf)

**Comment by jokergoo** [comment]
Sorry, I completely forgot this issue. You can 

give short name for each url.
or reduce the font size of the url
or set `circos.par(canvas.xlim = c(-3, 3), canvas.ylim = c(-3, 3))` before `chordDiagram()` (replace 3 and -3 to a value you find proper).
