### ISSUE TITLE
Use percent values for chord diagram

### ISSUE THREAD

**Issue by jokergoo** [jokergoo/circlize#81]
Currently each sector shows the “absolute values” for each connection. Sometimes it is useful to show percent of connections that comes from one sector so that we can see how much percent of sector A goes to sector B and how much percent it is in sector B. 

For real case, when visualizing chromatin state transitions with chromHMM results, Quies, repressive and transcript states are always the majority in the genome while TSS states are too small that they cannot be dustinguished from the chord diagram. But with showing the percent values, interesting patterns can be revealed.

**Comment by jokergoo** [comment]
```
df = data.frame(from = rep(rownames(mat), times = ncol(mat)),
    to = rep(colnames(mat), each = nrow(mat)),
    value = as.vector(mat),
    stringsAsFactors = FALSE)
df$value2 = df$value*2
par(mfrow = c(1, 2))
circos.par(gap.after = c(1, 1, 10, 1, 1, 1, 1, 1, 10))
chordDiagram(df[, 1:3], grid.col = grid.col)
title("one column of values")
chordDiagram(df[, 1:4], grid.col = grid.col, scale = TRUE)
title("two columns of values")
```

![image](https://user-images.githubusercontent.com/449218/42061595-0f367014-7b2b-11e8-9c96-69abbdfcb26b.png)

For the second figure, the end widths for a link are not equal.

**Comment by ALGW71** [comment]
Hi,

I think my question relates to this.

I need to apply my own scale (a normalization of gene frequencies across samples of different size) to each sector on the chord diagram.

Currently my sector size is representative of the number of links, as above, but I want sector size to be representative of it's frequency in the population, not just total count.

I have tried multiplying my input matrix by a normalized matrix of gene frequencies, but this does not work, as it is essentially normalizing the chords, not the sectors. 

Is there anyway to simply apply a new scale to each group of sectors?

My question seems to be similar to this:
https://stackoverflow.com/questions/45090688/set-sector-width-of-chord-diagram-with-circlize

"In your case, Number of people in the category sometimes can be smaller than the total number of co-occurrence to other categories. For example, category B has totally 9 co-occurrence but the number of people is only 8."

Yet I am not dealing with multiple co-occurrences for a given member of a sector, instead I want to scale sectors independently of the occurrences.

The only thing I haven't tried is scaling all co-occurrences in each sample before I group them together. Would this work or is there an easier way?

Hope this makes sense.

**Comment by ALGW71** [comment]
Just an update, I tried scaling co-occurrences prior to plotting and it appears to work.
