### ISSUE TITLE
Create legend for line/link width

### ISSUE THREAD

**Issue by aornugent** [jokergoo/circlize#82]
I have a figure where the links are weighted by some number. Presently this is passed into `circos.link` using the `lwd` argument.

I can't see a way (which doesn't mean there isn't) to generate a legend for linewidth using `ComplexHeatmap::Legend`. An example of what I'm looking for can be generated with ggplot2.

Thanks for your help,
Andrew

```R
library(ggplot2)

df <- data.frame(x = 1:5,
                 y = rnorm(5, 0, 1),
                 width = seq(1, 2, len = 5))

ggplot(df, aes(x, y, size = width)) +
  geom_line() +
  guides(size = guide_legend(keywidth = 5))
```

**Comment by jokergoo** [comment]
Set `lwd` in `legend_gp`:

```
lgd = Legend(at = 1:4, type = "lines", legend_gp = gpar(lwd = 1:4))
grid.draw(lgd)
```
