### ISSUE TITLE
missing bar in histogram when breaks are specified

### ISSUE THREAD

**Issue by anamariaelek** [jokergoo/circlize#87]
There seems to be na issue with plotting histograms when breaks are specified. In these cases, the first bar is always left out.
Here's a reproducible example:
```{r}
x = rnorm(9)
factors = rep(letters[1:3], 2:4)
l <- list(a = c(1,1,2,2,3,3), 
          b = c(1,2,2,2,2,3), 
          c = c(1,2,2,3,3,3))
factors <- as.factor(
  unlist(
    lapply(names(l), function(x) 
      rep.int(x, times = length(l[[x]])))
  )
)
x <- unname(unlist(l))

circos.initialize(factors = factors, x = x)
circos.trackPlotRegion(
  ylim = c(0, 1), 
  track.index = 1,
  panel.fun = function(x,y){
    xlim = CELL_META$xlim
    ylim = CELL_META$ylim
    sector.name = get.cell.meta.data("sector.index")
    circos.text(mean(xlim), mean(ylim), sector.name)
  }
)
circos.trackHist(factors = factors, x = x, col = "lightgray", border = "gray", breaks = 0:3, 
                 track.height = 0.5)
```
![rplot02](https://user-images.githubusercontent.com/20280755/42704580-ab346d80-86d0-11e8-96d4-0b89ce65921e.png)

So, each sector should contain three bars in histogram, counting number of occurences of 1s, 2s and 3s, respectively. However, ones are never shown, i.e. in the a sector, there are bars for the 2s and the 3s (each has height 2); in the b sector, there is a bar for 2s (its height is 4) and a bar for 3s (its height is 1); in the c sector, there are bars for 2s (height 2) and 3s (height 3).

I believe the issue originates in skipping this iteration in the definition of `circos.trackHist()` in `R/plot.R`
```{r}
for(j in seq_along(nx)) {
  if(j == 1) {
    next
  }
```

I made a little workaround to avoid this in my particular use case, but I thought it would also be a good idea to open an issue here.

**Comment by jokergoo** [comment]
The problem here is the range of all three sectors are all `[1, 3]`

```
> tapply(x, factors, range)
$a
[1] 1 3

$b
[1] 1 3

$c
[1] 1 3
```

and the three bars are drawn at `[0, 1]`, `[1, 2]` and `[2, 3]` and that's way the first bar is missing.

If you change xlim to `c(0, 3)`, you will see the first bar.

```
circos.initialize(factors = factors, xlim = cbind(rep(0, 3), rep(3, 3)))
circos.trackPlotRegion(
  ylim = c(0, 1), 
  track.index = 1,
  panel.fun = function(x,y){
    xlim = CELL_META$xlim
    ylim = CELL_META$ylim
    sector.name = get.cell.meta.data("sector.index")
    circos.text(mean(xlim), mean(ylim), sector.name)
  }
)
circos.trackHist(factors = factors, x = x, col = "lightgray", border = "gray", breaks = 0:3, 
                 track.height = 0.5)
```

![image](https://user-images.githubusercontent.com/449218/43129955-cecf40d6-8f35-11e8-9ce6-3e70ea17ced0.png)

**Comment by anamariaelek** [comment]
Oh, I hadn't thought of that. My issue was actually with `circos.genomicInitialize()`, and with the same logic applied to that function, I shifted the bed-like intervals from 1-based to 0-based. It works like a charm now 😄
Thank you for the explanation!
