### ISSUE TITLE
Documentation is down

### ISSUE THREAD

**Issue by oganm** [jokergoo/circlize#88]
It seems like the book linked here is down and cran vignette also directs to that book. Will the documentation come back?

**Comment by jokergoo** [comment]
Can you try it again with http://zuguang.de/circlize_book/book/ or  http://jokergoo.github.io/circlize_book/book/ ?

I changed the domain name settings last Friday, but I don't think it will affect that long.

**Comment by oganm** [comment]
👍 'tis fine now!

**Comment by oganm** [comment]
It turned into a white page again. I can however get the page contents if I do `httr::GET`

**Comment by cpad0112** [comment]
Documentation is not available as of today (IST Aug10,2018- Location: India). Both links are also not accessible

**Comment by cpad0112** [comment]
Documentation link is working now. Thanks.
