### ISSUE TITLE
genomic track of last chromosome does not extend all the way to the end

### ISSUE THREAD

**Issue by fklirono** [jokergoo/circlize#89]
Hello,

when coverage tracks extend all the way close to the end of chromosomes, then the track for the last chromosome plotted is shrunk compared to the actual x-axis range of that chromosome. I have attached a picture which highlights the problem:

![example](https://user-images.githubusercontent.com/21955822/44590407-60d38d00-a7bb-11e8-9585-eda3298c506c.png)

As you can see the coverage of the last plotted chromosome (chrY) does not extend all the way to the x-axis limits but is shrunk.

Here's a working example:

```
library(circlize)
library(data.table)

#  load the cytoBand from the circlize package and convert integers to numeric to avoid overflow
cb<-fread(system.file(package='circlize', 'extdata', 'cytoBand.txt'), header=F, sep='\t', col.names=c('seqnames','start','end','name','gieStain'))[, c('start', 'end'):=list(as.numeric(start), as.numeric(end))]

#  take the first, middle and last positions for each chromosome and define linearly increasing coverage
B<-cb[, .(start=quantile(start, c(0, 0.5, 1)), end=quantile(end, c(0, 0.5, 1)), coverage=c(0, 0.5, 1)), by=.(seqnames)]

#  last chromosome:
B[ seqnames %in% 'chrY' ]                                                                                                                               
>      seqnames    start      end coverage                                                                                                                    
> 1:     chrY        0  2500000      0.0                                                                                                                    
> 2:     chrY 13400000 15100000      0.5                                                                                                                    
> 3:     chrY 28800000 59373566      1.0   

#  draw the plot
circos.clear()
circos.par('start.degree'=90)
circos.initializeWithIdeogram(as.data.frame(cb))
circos.genomicTrackPlotRegion(as.data.frame(B), panel.fun=function(region, value, ...){
    circos.genomicLines(region, value, area=T, baseline=0, col='grey39', border='grey39', ...)
}, track.height=0.1)
highlight.chromosome('chrY')
```

**Comment by jokergoo** [comment]
I am so sorry that I completely missed this issue!

Since `region` contains regions, `circos.genomicLines()` adds lines at the middle of each region, which means, the x and y vector are `(region[, 1] + region[, 2])/2` and `value` for drawing lines. If you add one addtional line to `B`:

```
     chrY  59373566  59373566      1.0
```

You will see now chromosome Y is completely filled:

![image](https://user-images.githubusercontent.com/449218/55424333-4f880580-5580-11e9-9669-71b6e96a6ff7.png)

If you want to draw both the start and end for the regions, you can use `circos.genomicRect()`.

Hope it is still useful!
