### ISSUE TITLE
eps support for "genomicRainfall" function

### ISSUE THREAD

**Issue by yftang** [jokergoo/circlize#9]
Hi, you made a great job to generate a "circos"-like graph for human genome. When I try the `genomicRainfall` function via [example page](http://jokergoo.github.io/circlize/example/railfallplot.html), it shows the figure.
But when I tried to output as a eps file, adding `postgres("test.eps")` before `par()` command, the `genomicRainfall` command outputs an error as the following figure:

![screenshot from 2015-10-23 17 45 19](https://cloud.githubusercontent.com/assets/1327096/10691866/4ccf5ed8-79bf-11e5-914a-74f77f30c584.png)

My environment:
* Ubuntu: 15.04;
* R: 3.1.2;
* Circlize: 0.3.2.

**Comment by jokergoo** [comment]
I think it is because EPS format does not support semi-transparency. You can change `#FF000080` and `#0000FF80` to `#FF0000` and `#0000FF` for the `col` argument in `circos.genomicRainfall()`.

**Comment by yftang** [comment]
Man! Shame for such a newbee question. Thanks!

**Comment by jokergoo** [comment]
No problem : )
