### ISSUE TITLE
R CRAN package not found

### ISSUE THREAD

**Issue by andyjslee** [jokergoo/circlize#91]
It seems there is a problem in your package as I am not able to found the R package using install.packages("circlize"). It would be great if you could please make the necessary fixes to the bugs. Thank you!

**Comment by jokergoo** [comment]
What is your R version and what is the error message?

Or you can directly install the package from the link:

```
install.packages("https://cran.r-project.org/src/contrib/circlize_0.4.4.tar.gz", repo = NULL)
```
