### ISSUE TITLE
Error in chordDiagram with self.link = 1

### ISSUE THREAD

**Issue by rntq472** [jokergoo/circlize#92]
Hi, great work with this package.

I am getting an error for a certain combination of inputs to the chordDiagram function when using self.link = 1. The error is:
_Error in od[[nm]] <- order(od[[nm]][l2]) : replacement has length zero_

Reproducible example below:

`
test <- structure(list(from = c("A", "B", "B", "D", "E", "E", "F"), to = c("A", 
"B", "C", "G", "E", "H", "F"), value = c(9, 3, 26, 2, 10, 2, 
2)), row.names = c(NA, -7L), class = "data.frame")

chordDiagram(test, self.link = 2) # This works
chordDiagram(test, self.link = 1) # This doesn't
`

This is using the latest version of circlize on CRAN.

Thanks

**Comment by jokergoo** [comment]
Hi, this is a bug and I have fixed.

Please update the package from github : `devtools::install_github("jokergoo/circlize")`.

![image](https://user-images.githubusercontent.com/449218/46904164-4b87fe80-cee0-11e8-995b-1e6f728e9dde.png)

**Comment by rntq472** [comment]
Hi,

That fixed the previous example but now I have another one.

```
test <- structure(list(from = c("A", "B", "C", "D", "D", "D", "D", "C", 
"E", "D", "F", "G", "H"), to = c("A", "B", "F", "A", "D", "G", 
"H", "C", "A", "E", "C", "G", "A"), value = c(7, 1, 4, 1, 3, 
1, 1, 5, 4, 1, 1, 1, 1)), row.names = c(NA, -13L), class = "data.frame")

chordDiagram(test, self.link = 2) # This works
chordDiagram(test, self.link = 1) # This doesn't
```

Thanks

**Comment by jokergoo** [comment]
Thanks for reporting a new case! I think I've fixed it now.
