### ISSUE TITLE
possible issue with xmax in chordDiagram

### ISSUE THREAD

**Issue by gjabel** [jokergoo/circlize#93]
I am struggling to get `xmax` working in `chordDiagram` - adapting from the example in the help file...

```{r}
set.seed(999)
mat = matrix(sample(18, 18), 3, 6) 
rownames(mat) = paste0("S", 1:3)
colnames(mat) = paste0("E", 1:6)

df = data.frame(from = rep(rownames(mat), times = ncol(mat)),
                to = rep(colnames(mat), each = nrow(mat)),
                value = as.vector(mat),
                stringsAsFactors = FALSE)

n = unique(c(df$from, df$to))
x = rep(100, length(n))
names(x) <- n
```
where `x` is a named vector for maximum on the sector limits
```{r}
> x
#  S1  S2  S3  E1  E2  E3  E4  E5  E6 
# 100 100 100 100 100 100 100 100 100 
```
Passing to `chordDiagram()` gives...
```{r}
chordDiagram(df, xmax = x)
```

![rplot](https://user-images.githubusercontent.com/2735201/47107309-9193e800-d27b-11e8-811d-9dcb8e69558b.png)

i.e. the same plot as  `chordDiagram(df)` ignoring the limits passed to `xmax`. Any suggestion what is going I am doing wrong here?

**Comment by jokergoo** [comment]
Ha, that was a mistake. I forgot to pass `xmax` to inner function. You can do either:

```
chordDiagramFromDataFrame(df, xmax = x)
```

or update the package. I just pushed a fix to github.

**Comment by gjabel** [comment]
Ah great. Thanks for the quick reply.
